<?php
$form = $this->form;
$routeArray = array('action' => $this->formAction);
if (isset($this->menuId)) $routeArray['id'] = $this->menuId;

?>
<div>
    <form class="form form-horizontal"  method="post" action="<?php echo $this->url('admin/menu', $routeArray) ?>">
        <fieldset>
        <legend><?php echo ucwords($this->formAction); ?> Menu Form:</legend>
        <div class="control-group<?php if ($form->get('menu')->getMessages()) echo ' error'; ?>">
            <label class="control-label" for="title">Menu Title:</label>
            <div class="controls">
                <?php echo $this->formInput($form->get('menu')); ?>
                <span class="help-block">
                <?php echo $this->formElementErrors($form->get('menu'), array(
                    'class' => 'unstyled'
                )); ?>
                </span>
            </div>
        </div>
        
        
        <?php echo $this->formElement($form->get('menuId')); ?>
       	
        <input type="hidden" name="action" value="<?php echo $this->formAction; ?>">
        
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary" 
                data-loading-text="Please wait...">Submit</button>
                <button type="button" class="btn btn-warning" 
                data-loading-text="Please wait..." onClick="window.location = '<?php echo $this->url('admin/menu', array(
                        'action' => 'list',
                    )) ?>';">Cancel</button>
            </div>
        </div>
        </fieldset>
    </form>
</div>
