<?php
$form = $this->form;
$routeArray = ['action' => $this->formAction];
if (isset($this->faqId)) $routeArray['id'] = $this->faqId;
?>

<div class="row">
    <form class="form-horizontal col-md-12" method="post" action="<?=$this->url('admin/shop/faq/edit', $routeArray) ?>">
        <fieldset>
            <legend><?=ucwords($this->formAction); ?> F.A.Q</legend>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group<?php if ($form->get('question')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-2 control-label" for="question"><?=$form->get('question')->getLabel();?></label>
                        <div class="col-md-10">
                            <?=$this->formText($form->get('question')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                                <?=$this->formElementErrors($form->get('question'), [
                                    'class' => 'list-unstyled'
                                ]); ?>
                            </span>
                        </div>
                    </div>

                    <div class="form-group<?php if ($form->get('answer')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-2 control-label" for="answer"><?=$form->get('answer')->getLabel();?></label>
                        <div class="col-md-10">
                            <?=$this->formTextarea($form->get('answer')); ?>
                            <span class="help-block">
                                <?=$this->formElementErrors($form->get('answer'), [
                                    'class' => 'list-unstyled'
                                ]); ?>
                            </span>
                        </div>
                    </div>

                </div>

                <div class="col-md-6">

                    <div class="form-group<?php if ($form->get('parent')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="parent"><?=$form->get('parent')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formSelect($form->get('parent')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                                <?=$this->formElementErrors($form->get('parent'), [
                                    'class' => 'list-unstyled'
                                ]); ?>
                            </span>
                        </div>
                    </div>

                    <?=$this->formRow($this->form->get('faqInsertType'));?>

                </div>
            </div>
        </fieldset>

        <?=$this->formHidden($form->get('faqId'));?>
        <input type="hidden" name="action" value="<?=$this->formAction;?>">

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary" data-loading-text="Please wait...">
                    Submit
                </button>
                <button type="button" class="btn btn-warning"  data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('admin/shop/faq') ?>';">
                    Cancel
                </button>
            </div>
        </div>
    </form>
</div>

<?=$this->partial('uthando-admin/partial/tiny-mce');?>
