<?php $this->headTitle('FAQs') ?>
<?php $this->layout()->pageTitle = $this->translate('FAQs');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
    <a href="<?=$this->url('admin/shop/faq/edit', [
        'action' => 'add'
    ]);?>" data-toggle="tooltip" title="<?=$this->translate('Add FAQ');?>" class="btn btn-primary" id="faq-add">
        <i class="fa fa-plus"></i>
    </a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('List Adverts');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'faq',
            'searchInputs'	=> [
                'Search' => 'question-answer',
            ],
        ]);?>
    </div>
    <div id="table-faq" class="admin-table">
        <?=$this->partial('shop/faq/list', [
            'models' => $this->models,
        ]); ?>
    </div>
</div>

<?php $this->placeholder('js-scripts')->captureStart();?>
<script>
    $('#table-productCategory').dataGrid({
        url : 'faq/list',
        query: { sort : 'lft' },
        searchForm : $('#search-faq'),
        paging : 'links',
        columnSort: true,
        //rowClick : admin.product.rowClick
    });
</script>
<?php $this->placeholder('js-scripts')->captureEnd();?>
