<?php $this->headTitle('Edit Country') ?>
<?php $this->layout()->pageTitle = $this->translate('Edit Country');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-country" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/shop/country');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-country',
    'action' => $this->url('admin/shop/country/edit', [
        'id' => $this->model->getCountryId(),
    ]),
]); ?>

<div id="country-edit" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Edit Country');?></h3>
    </div>
    <div class="panel-body">
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="active"><a href="#country" data-toggle="tab">Country</a></li>
            <li><a href="#country-province" data-toggle="tab">Provinces</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="country">
                <div class="clearfix">&nbsp;</div>
                <?=$this->form($this->form);?>
            </div>

            <div class="tab-pane" id="country-province">
                <div class="clearfix">&nbsp;</div>
                <a href="<?=$this->url('admin/shop/country/province', [
                    'action'    => 'add',
                    'id'        => $this->model->getCountryId(),
                ]);?>" id="add-country-province-button" class="btn btn-default">
                    Add Province
                </a>
                <div class="clearfix">&nbsp;</div>
                <div class="country-province-list">
                    <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading
                </div>

            </div>

        </div>
    </div>
</div>

<div class="col-md-12">

    <div class="col-md-6">
        <div id="country-provinces" class="panel panel-info">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <h4 class="panel-title">
                    Provinces
                    <button id="add-province-button" class="btn btn-default btn-xs" data-toggle="modal"
                            data-target="#add-province-model">
                        Add Province
                    </button>
                </h4>
            </div>
            <div class="panel-table">
                <div class="text-center">
                    <i class="fa fa-spinner fa-spin"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="add-province-model" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add Province</h4>
            </div>
            <div class="modal-body">
                <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="add-province-save" type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

<div id="edit-province-model" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit Address</h4>
            </div>
            <div class="modal-body">
                <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="edit-province-save" type="button" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>

<script>
    $(document).ready(function() {
        var provinces = function () {

            admin.ajaxWidgetPanel(
                $('#country-provinces .panel-table'),
                '<?=$this->url('admin/shop/country/province', [
                    'action' => 'list'
                ]);?>',
                {countryId: '<?=$this->model->getCountryId();?>'}
            );
        }

        $('#country-provinces').on('click', '.edit-button', function (event) {
            event.preventDefault();

            var el = $('#edit-province-model');
            var url = $(this).attr('href').replace('-province', '');

            el.on('show.bs.modal', function () {
                $(this).find('.modal-body').load(url);
            });

            el.on('hide.bs.modal', function (e) {
                $(this).find('.modal-body').html('<i class="fa fa-spinner fa-spin"></i>&nbsp;Loading');
                provinces();
                el.off('show.bs.modal hide.bs.modal');
                $('#edit-province-save').off('click');
            });

            $('#edit-province-save').on('click', function () {
                admin.ajaxModalForm(el, url);
            });

            el.modal('show');

        });

        $('#country-provinces').on('submit', 'form', function (event) {
            event.preventDefault();
            var url = '<?=$this->url('admin/shop/country/province', [
                'action'    => 'delete',
            ]);?>';
            var params = $(this).serialize() + '&submit=delete';
            var el = $(this).parent().parent().parent();

            $.ajax({
                url: url,
                data: params,
                type: 'POST',
                success: function (response) {
                    admin.addAlert(response.messages, response.status);
                    $(el).modal('hide');
                    setTimeout('provinces()', 500);
                },
                error: function (response) {
                    admin.addAlert(response.error, 'danger');
                    $(el).modal('hide');
                    setTimeout('provinces()', 500);
                }
            });
        });

        $('#add-province-model').on('show.bs.modal', function () {
            $(this).find('.modal-body').load('<?=$this->url('admin/shop/country/province', [
                'action'    => 'add',
                'id'        => $this->model->getCountryId(),
            ]);?>');
        });

        $('#add-province-model').on('hide.bs.modal', function (e) {
            $(this).find('.modal-body').html('<i class="fa fa-spinner fa-spin"></i>&nbsp;Loading');
            provinces();
        });

        $('#add-province-save').on('click', function () {
            admin.ajaxModalForm('#add-province-model', '<?=$this->url('admin/shop/country/province', [
                'action'    => 'add',
            ]);?>');
        });

        provinces();
    });

</script>
