<?php $this->headTitle('Edit Country') ?>
<?=$this->ztbFlashMessenger()->render(); ?>

<?=$this->partial('partial/add-edit-form', array(
	'form' 			=> $this->form,
	'formAction' 	=> 'edit',
	'primaryKey'	=> $this->model->getCountryId(),
	'formName'		=> 'Country',
	'postRoute'		=> 'admin/shop/country/edit',
	'cancelRoute'	=> 'admin/shop/country',
	'formElements'	=> array(
		'country', 'code', 'postZoneId', 'countryId',
	),
)); ?>
