<?php $this->placeholder('header-buttons')->captureStart();?>
<a href="<?=$this->url('admin/shop/country/edit', [
    'action' => 'add'
]);?>" data-toggle="tooltip" title="<?=$this->translate('Add Country');?>" class="btn btn-primary" id="country-add">
    <i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('Country');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'country',
            'searchInputs'	=> [
                'Country' => 'country-code',
            ],
        ]);?>
    </div>
    <div id="table-country" class="admin-table">
        <?=$this->partial('shop/country/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('#table-country').dataGrid({
            url : 'country/list',
            query: { sort : 'country' },
            searchForm : $('#search-country'),
            paging : 'links',
            columnSort: true,
            //rowClick : admin.product.rowClick
        });
    });
</script>
