<?php $this->headTitle('Countries') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->countries) > 0): ?>

<table id="country-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="countryId">Country Id</th>
			<th data-field="country">Country</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach($this->countries as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getCountryId()); ?></td>
			<td><?=$this->escapeHtml($row->getCountry()); ?></td>
			<td>
                <a href="<?=$this->url('admin/shop/country/edit', array(
                    'id' => $row->getCountryId()
				)); ?>" class="btn">Edit</a>
				&nbsp;
				
				<!-- Button to trigger modal -->
                <a href="#countryModel<?=$row->getCountryId(); ?>" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="countryModel<?=$row->getCountryId(); ?>">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
				    <h3 id="countryModel<?=$row->getCountryId(); ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?=$this->url('admin/shop/country/edit', array(
				        'action' => 'delete',
				    )) ?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this category.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="countryId" value="<?=$row->getCountryId() ?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->countries,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/country/page')
); ?>

<?php else: ?>
<h4>No Countries where returned by search.</h4>
<?php endif; ?>
