<?php $this->headTitle('Countries') ?>

<?php if (count($this->models) > 0): ?>

<div class="panel panel-default">
    <table id="country-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="countryId">Country Id</th>
    			<th data-field="country">Country</th>
    			<th data-field="code">Country Code</th>
    			<th data-field="zone">Post Zone</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    		<?php /* @var $row \Shop\Model\Country */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getCountryId()); ?></td>
    			<td><?=$this->escapeHtml($row->getCountry()); ?></td>
    			<td><?=$this->escapeHtml($row->getCode()); ?></td>
    			<td><?=$this->escapeHtml($row->getPostZone()->getZone()); ?></td>
    			<td>
                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                    	'pk'		=> 'countryId',
                    	'id'		=> $row->getCountryId(),
    		    		'tableName'	=> 'country',
                    	'route'		=> 'admin/shop/country/edit',
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/shop/country/page']
); ?>

<?php else: ?>
<h4>No Countries where returned by search.</h4>
<?php endif; ?>
