<?php $this->headTitle('Countries') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->models) > 0): ?>

<table id="country-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="countryId">Country Id</th>
			<th data-field="country">Country</th>
			<th data-field="zone">Post Zone</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php /* @var $row \Shop\Model\Country */ ?>
		<?php foreach($this->models as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getCountryId()); ?></td>
			<td><?=$this->escapeHtml($row->getCountry()); ?></td>
			<td><?=$this->escapeHtml($row->getZone()); ?></td>
			<td>
                <?=$this->partial('partial/edit-actions', array(
                	'pk'		=> 'countryId',
                	'id'		=> $row->getCountryId(),
		    		'tableName'	=> 'country',
                	'route'		=> 'admin/shop/country/edit',
		    	));?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/country/page')
); ?>

<?php else: ?>
<h4>No Countries where returned by search.</h4>
<?php endif; ?>
