
<h1><?=$this->translate('An error occurred') ?></h1>
<h2><?=$this->message ?></h2>


<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
    <hr/>
    <h2><?=$this->translate('Additional information') ?>:</h2>
    <h3><?=get_class($this->exception); ?></h3>
    <dl>
        <dt><?=$this->translate('File') ?>:</dt>
        <dd>
            <pre class="prettyprint linenums"><?=$this->exception->getFile() ?>:<?=$this->exception->getLine() ?></pre>
        </dd>
        <dt>Message:</dt>
        <dd>
            <pre class="prettyprint linenums"><?=$this->exception->getMessage() ?></pre>
        </dd>
        <dt>Stack trace:</dt>
        <dd>
            <pre class="prettyprint linenums"><?=$this->exception->getTraceAsString() ?></pre>
        </dd>
    </dl>
    <?php
    $e = $this->exception->getPrevious();
    if ($e) :
        ?>
        <hr/>
        <h2>Previous exceptions:</h2>
        <ul class="unstyled">
            <?php while($e) : ?>
                <li>
                    <h3><?=get_class($e); ?></h3>
                    <dl>
                        <dt><?=$this->translate('File') ?>:</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?=$e->getFile() ?>:<?=$e->getLine() ?></pre>
                        </dd>
                        <dt><?=$this->translate('Message') ?>:</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?=$e->getMessage() ?></pre>
                        </dd>
                        <dt><?=$this->translate('Stack trace') ?>:</dt>
                        <dd>
                            <pre class="prettyprint linenums"><?=$e->getTraceAsString() ?></pre>
                        </dd>
                    </dl>
                </li>
                <?php
                $e = $e->getPrevious();
            endwhile;
            ?>
        </ul>
    <?php endif; ?>

<?php else: ?>

    <h3>No Exception available</h3>

<?php endif ?>

<h2>Get Vars</h2>
<pre><?=Zend\Debug\Debug::dump($this->getVars, null, false);?></pre>

<h2>Post Vars</h2>
<pre><?=Zend\Debug\Debug::dump($this->postVars, null, false);?></pre>

<h2>HTTP Request</h2>
<pre><?=Zend\Debug\Debug::dump($this->requestString, null, false);?></pre>

<h2>Session Information</h2>
<pre><?=Zend\Debug\Debug::dump($this->sessionVars, null, false);?></pre>
