<h1><?=$this->translate('An PayPal error occurred') ?></h1>
<h2><?=$this->message ?></h2>

<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
    <hr/>
    <h2><?=$this->translate('Additional Information') ?>:</h2>
    <h3><?=get_class($this->exception); ?></h3>
    <dl>
        <dt><?=$this->translate('File') ?>:</dt>
        <dd>
            <pre><?=$this->exception->getFile() ?>:<?=$this->exception->getLine() ?></pre>
        </dd>
        <dt>Message:</dt>
        <dd>
            <pre><?=$this->exception->getMessage() ?></pre>
        </dd>
        <dt>Stack trace:</dt>
        <dd>
            <pre><?=$this->exception->getTraceAsString() ?></pre>
        </dd>
    </dl>
    <?php
    $e = $this->exception->getPrevious();
    if ($e) :
        ?>
        <hr/>
        <h2>Previous exceptions:</h2>
        <ul class="unstyled">
            <?php while($e) : ?>
                <li>
                    <h3><?=get_class($e); ?></h3>
                    <dl>
                        <dt><?=$this->translate('File') ?>:</dt>
                        <dd>
                            <pre><?=$e->getFile() ?>:<?=$e->getLine() ?></pre>
                        </dd>
                        <dt><?=$this->translate('Message') ?>:</dt>
                        <dd>
                            <pre><?=$e->getMessage() ?></pre>
                        </dd>
                        <dt><?=$this->translate('Stack trace') ?>:</dt>
                        <dd>
                            <pre><?=$e->getTraceAsString() ?></pre>
                        </dd>
                    </dl>
                </li>
                <?php
                $e = $e->getPrevious();
            endwhile;
            ?>
        </ul>
        <?php if ($this->exception->getOrder() instanceof \Shop\Model\Order\OrderModel): ?>
            <hr/>
            <h2><?=$this->translate('Order Information') ?>:</h2>
            <pre><?=Zend\Debug\Debug::dump($this->exception->getOrder(), null, false);?> ?></pre>
        <?php endif; ?>
        <?php if ($this->exception->getPayment() instanceof \PayPal\Api\Payment): ?>
            <hr/>
            <h2><?=$this->translate('Payment Information') ?>:</h2>
            <pre><?=Zend\Debug\Debug::dump($this->exception->getPayment(), null, false);?> ?></pre>
        <?php endif; ?>
    <?php endif; ?>

<?php else: ?>

    <h3>No Exception available</h3>

<?php endif ?>

<h2>Get Vars</h2>
<pre><?=Zend\Debug\Debug::dump($this->getVars, null, false);?></pre>

<h2>Post Vars</h2>
<pre><?=Zend\Debug\Debug::dump($this->postVars, null, false);?></pre>

<h2>HTTP Request</h2>
<pre><?=Zend\Debug\Debug::dump($this->requestString, null, false);?></pre>

<h2>Session Information</h2>
<pre><?=Zend\Debug\Debug::dump($this->sessionVars, null, false);?></pre>
