<?php 

use Zend\Form\Element;

$discontinued = new Element\Checkbox('discontinued', [
    'checked_value' => '1',
    'label' => 'discontinued',
    'use_hidden_element' => false,
]);
$disabled = new Element\Checkbox('disabled', [
    'checked_value' => '1',
    'label' => 'disabled',
    'use_hidden_element' => false,
]);

?>

<form id="product-report">
    <?=$this->formRow($this->formManager(\Shop\Form\Element\ProductCategoryList::class)
        ->setName('productCategoryId')
        ->setEmptyOption('All Categories')
    );?>
    
    <?=$this->formRow($disabled);?>
    <?=$this->formRow($discontinued);?>
    
    <input type="hidden" name="sort" value="<?=$this->shopOption('productsOrderCol');?>">
    
</form>
