<?=$this->doctype();?>
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->	<html> <!--<![endif]-->
    <head>
        <?=$this->headMeta()
            ->setCharset('utf-8')
            // mobile settings
            ->appendName('viewport', 'width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0')
            ->appendName('rating', 'general')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('robots', 'Index, Follow')
        ;?>

        <?=$this->headTitle($this->themeOptions('site_name'))
            ->setSeparator(' - ')
            ->setAutoEscape(false);?>

        <!-- Favicon -->
        <?=$this->headLink([
            'rel'  => 'shortcut icon',
            'href' => $this->basePath('/userfiles/favicon.ico')])
            // WEB FONTS
            ->appendStylesheet('//fonts.googleapis.com/css?family=Open+Sans:300,400,700,800&amp;subset=latin,latin-ext')
            // CORE CSS
            ->appendStylesheet($this->themePath('/assets/plugins/bootstrap/css/bootstrap.min.css'))
            ->appendStylesheet($this->themePath('/assets/css/font-awesome.css'))
            ->appendStylesheet($this->themePath('/assets/css/sky-forms.css'))
            ->appendStylesheet($this->themePath('/assets/css/weather-icons.min.css'))
            ->appendStylesheet($this->themePath('/assets/css/line-icons.css'))
            ->appendStylesheet($this->themePath('/assets/plugins/owl-carousel/owl.pack.css'))
            ->appendStylesheet($this->themePath('/assets/plugins/magnific-popup/magnific-popup.css'))
            ->appendStylesheet($this->themePath('/assets/css/animate.css'))
            ->appendStylesheet($this->themePath('/assets/css/flexslider.css'))
            // REVOLUTION SLIDER
            ->appendStylesheet($this->themePath('/assets/css/revolution-slider.css'))
            ->appendStylesheet($this->themePath('/assets/css/layerslider.css'))
            // THEME CSS
            ->appendStylesheet($this->themePath('/assets/css/essentials.css'))
            ->appendStylesheet($this->themePath('/assets/css/layout.css'))
            //->appendStylesheet($this->themePath('/assets/css/header-default.css'))
            ->appendStylesheet($this->themePath('/assets/css/header-5.css'))
            ->appendStylesheet($this->themePath('/assets/css/footer-default.css'))
            ->appendStylesheet($this->themePath('/assets/css/color_scheme/yellow.css'), 'screen', false, ['id' => 'color_scheme'])
            // SHOP
            ->appendStylesheet($this->themePath('/assets/css/layout-shop.css'))
            // UTHANDO STYLES
            ->appendStylesheet($this->basePath('/css/uthando-styles.css'))
        ;?>

        <?=$this->placeholder('structured-data');?>

        <style>
            /* Theme overrides */
            #header.sticky.affix #topBar {
                display:block;
            }

            #topNav ul.dropdown-menu > li a {
                padding: 10px 20px;
            }

            .shop-item-list {
                height: auto;
            }
            
            .shop-item-list a {
            	text-decoration:none;
            }
            
            .shop-item-list figure {
            	height:150px;
            }

            .shop-item-list span.product-name {
                white-space: initial;
            }

            #barMain .nav>li.quick-cart .quick-cart-items {
                max-height: 300px;
                overflow: auto;
            }
            
            ul.side-nav ul li.list-group-item.active {
                border:0;
                background-color:transparent;
            }
            
            .box-content .item-image {
            	width: 230px;
            	height: 177px
            }
            
            .box-content .item-image img {
            	width: 230px;
            }

            #footer #newsletter_name {
                -webkit-border-top-right-radius: 6px;
                -webkit-border-bottom-right-radius: 6px;
                -moz-border-radius-topright: 6px;
                -moz-border-radius-bottomright: 6px;
                border-top-right-radius: 6px;
                border-bottom-right-radius: 6px;
            }

            #footer .checkbox {
                color: #777;
            }

            .vertical-align {
                display: flex;
                align-items: center;
            }

            .cart-links {
                margin-bottom: 10px;
            }

            .owl-carousel .owl-item div {
                text-align: left;
            }

            .cartContent .tax, .cartContent .total_price {
                float:right;
                width:125px;
                font-size:15px;
                padding:10px;
                line-height:30px;
                text-align:center;
                font-weight:bold;
            }

            .product-info .line-through {
                color: #f00;
            }

        </style>
    </head>

    <!--
        Available body classes:
            smoothscroll			= enable chrome browser smooth scroll
            grey 					= grey content background
            boxed 					= boxed style
            pattern1 ... pattern10 	= background pattern

        Background Image - add to body:
            data-background="assets/images/boxed_background/1.jpg"
    -->
    <body class="smoothscroll">

        <div id="wrapper">
            <div id="header"><!-- class="sticky" for sticky menu -->
                <!-- Top Bar -->
                <header id="topBar" class="styleBackgroundColor">
                    <div class="container">

                        <div id="barMain" class="block text-right">

                            <nav class="nav-second">
                                <?=$this->uthandoNavigation()
                                    ->uthandoTbDbMenu('top-menu')
                                    ->setPartial('uthando-navigation/top-menu')
                                ;
                                ?>
                            </nav>

                            Call Us Today: <strong><a href="tel:<?=$this->contact()->formatPhoneNumber('phone');?>">
                                <?=$this->contact()->formatPhoneNumber('phone', true);?>
                            </a></strong>
							<span class="hide_mobile">
								&bull; <a href="<?=$this->url('contact');?>"><?=$this->contact('details.email');?></a>
							</span>

                        </div>

                        <div id="google_translate_element" style="float:right; padding:7px;"></div><script type="text/javascript">
                            function googleTranslateElementInit() {
                                new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
                            }
                        </script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

                        <!-- Logo -->
                        <a class="logo" href="<?=$this->url('home');?>" style="text-decoration: none;">
                            <img src="<?=$this->basePath('/userfiles/logo.png');?>" height="50" alt="logo">
                            <img src="<?=$this->basePath('/userfiles/charismabeads.png');?>" height="50" alt="logo" >
                        </a>

                    </div><!-- /.container -->
                </header>
                <!-- /Top Bar -->

                <!-- Top Nav -->
                <header id="topNav">
                    <div class="container">

                        <!-- Mobile Menu Button -->
                        <button class="btn btn-mobile" data-toggle="collapse" data-target=".nav-main-collapse">
                            <i class="fa fa-bars"></i>
                        </button>

                        <!-- Search -->
                        <form id="search-catalog" class="search" method="post" action="<?=$this->url('shop/search');?>">
                            <?=$this->formElement(
                                $this->productSearch()
                                    ->get('productSearch')
                                    ->setValue($this->searchData['productSearch'])
                            );?>
                            <button type="submit" class="fa fa-search"></button>
                        </form>
                        <!-- /Search -->

                        <!-- Top Nav -->
                        <div class="navbar-collapse nav-main-collapse collapse">
                            <nav class="nav-main">
                                <?=$this->uthandoNavigation()
                                    ->uthandoTbDbMenu('main-menu')
                                    ->setPartial('uthando-navigation/main-menu');
                                ?>

                            </nav>
                        </div>
                        <!-- /Top Nav -->

                    </div><!-- /.container -->
                </header>
                <!-- /Top Nav -->

            </div>

            <?=$this->placeholder('page-top');?>

            <!-- CONTENT -->
            <section>
                <div class="container">

                    <!-- header -->
                    <?=$this->placeholder('header');?>
                    <!-- /header -->

                    <!-- messages -->
                    <div class="row">
                        <div class="col-md-12">
                            <?=$this->shopAlert();?>
                            <?=$this->tbFlashMessenger()->render(); ?>
                        </div>
                    </div>
                    <!-- /messages -->

                    <?=$this->content;?>
                </div>
            </section>
            <!-- /CONTENT -->

            <!-- FOOTER -->
            <footer id="footer">
                <div class="container">

                    <div class="row">

                        <!-- col #1 -->
                        <div class="logo_footer dark col-md-3">

                            <img alt="<?=$this->themeOptions('site_name');?>" src="<?=$this->basePath('/userfiles/charismabeads.png');?>" height="50" class="logo" />

                            <p class="block">
                                <?=$this->contact()->formatAddress('details.address');?><br />
                                Email:&nbsp;<a href="<?=$this->url('contact');?>">
                                    <?=$this->contact('details.email');?>
                                </a><br />
                                Phone:&nbsp;<a href="tel:<?=$this->contact()->formatPhoneNumber('phone');?>">
                                    <?=$this->contact()->formatPhoneNumber('phone', true);?>
                                </a><br />
                            </p>

                            <p class="block"><!-- social -->
                                <?=$this->socialLinks()->render();?>
                            </p><!-- /social -->

                            <div class="row vertical-align">
                                <div class="col-md-6">
                                    <a href="https://www.positivessl.com" style="font-family: arial; font-size: 10px; color: #212121; text-decoration: none;">
                                        <img src="https://www.positivessl.com/images-new/PositiveSSL_tl_trans.png" alt="SSL Certificate" title="SSL Certificate" border="0" />
                                    </a>
                                </div>
                                <div class="col-md-6">
                                    <a href=' https://siteuptime.com/statistics.php?Id=5561&UserId=a557440f046f802e263a94108a1ee8f5' target="_blank">
                                        <img width=85 height=16 border=0 alt='website uptime' src="https://siteuptime.com/button/genbutton.php?u=195343&m=16033&c=green&p=total">
                                    </a>
                                    <noscript>
                                        <a href='http://www.siteuptime.com/'>website monitoring</a>
                                    </noscript>
                                </div>
                            </div>
                        </div>
                        <!-- /col #1 -->

                        <!-- col #2 -->
                        <div class="spaced col-md-3 col-sm-4">
                            <h4>Recent <strong>Posts</strong></h4>
                            <ul class="list-unstyled">
                            <?php foreach($this->uthandoArticleRecentPosts(3) as $row): ?>
                                <li>
                                    <a class="block" href="<?=$this->url('article', [
                                        'slug'   => $row->getSlug(),
                                    ]);?>"><?=$row->getTitle();?></a>
                                    <?=$this->formatDate($row->getDateCreated(), 'F j, Y');?>
                                
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        </div>
                        <!-- /col #2 -->

                        <!-- col #3 -->
                        <div id="tweet-feed" class="spaced col-md-3 col-sm-4">
                            <div class="text-center">
                                <i class="fa fa-refresh fa-spin fa-3x"></i>
                            </div>
                        </div>
                        <!-- /col #3 -->

                        <!-- col #4 -->
                        <div class="spaced col-md-3 col-sm-4">
                            <h4>About <strong>Us</strong></h4>
                            <p>
                                <?=$this->contact('details.about_us_text');?>
                            </p>
                            <?php $newsletter = $this->formManager(\UthandoNewsletter\Form\SubscriberForm::class); ?>
                            <div id="newsletter_form">
                                <h4><small><strong>Subscribe to our Newsletter</strong></small></h4>
                                <form class="sky-form" id="newsletterSubscribe" method="post" action="<?=$this->url('newsletter/subscribe');?>">
                                    <?=$this->formText($newsletter->get('name')->setAttributes([
                                        'class' => 'form-control',
                                        'id' => 'newsletter_name',
                                        'placeholder' => 'Name',
                                    ]));?>
                                    <div class="input-group">
                                        <?=$this->formEmail($newsletter->get('email')->setAttributes([
                                            'class' => 'form-control',
                                            'id' => 'newsletter_email',
                                            'placeholder' => 'E-mail Address',
                                        ]));?>
                                        <span class="input-group-btn">
                                            <input type="submit" class="btn btn-primary" value="SUBMIT">
                                        </span>
                                    </div>
                                    <?=$this->formMultiCheckbox(
                                        $newsletter->get('subscribe')
                                            ->setLabelOption('disable_html_escape', true)
                                            ->setLabelPrepend(true)
                                            ->setPreSelect(true)
                                            ->setIncludeHidden(false)
                                    );?>
                                </form>
                            </div>
                        </div>
                        <!-- /col #4 -->

                    </div>

                </div>

                <hr />

                <div class="copyright">
                    <div class="container text-center fsize12">
                        Registered at Companies House, register number <?=$this->contact('company.number');?>.<br>
                        Registered office address:
                        <?=$this->contact()->formatAddress('company.address');?>
                       <br>
                        Designed by <a href="http://www.shaunfreeman.co.uk" target="_blank" title="e-commerse websites" class="copyright">
                            Shaun Freeman
                        </a> &bull; All Right Reserved &copy; <?=date('Y');?> <?=$this->themeOptions('site_name');?>. &nbsp;
                        <a href="<?=$this->url('article', [
                            'slug' => 'cookie-policy',
                        ])?>" class="fsize11">Cookie Policy</a> &bull;
                        <a href="<?=$this->url('article', [
                            'slug' => 'terms',
                        ])?>" class="fsize11">Terms of Sale</a>
                    </div>
                </div>
            </footer>
            <!-- /FOOTER -->

            <a href="#" id="toTop"></a>
        </div><!-- /#wrapper -->

        <script>
            window.cookieconsent_options = {
                message: '<?=$this->themeOptions('site_name');?> uses cookies to ensure you get the best experience on our website.',
                dismiss: 'OK',
                learnMore: 'Learn more',
                link : '<?=$this->url('article', [
                    'slug' => 'cookie-policy'
                ]);?>',
                //theme: 'light-bottom',
            };
            var shopBasePath = '<?=$this->basePath();?>';
        </script>
        <!-- JAVASCRIPT FILES -->
        <?=$this->inlineScript()
            ->prependFile($this->basePath('/js/shop.js'))
            ->prependFile($this->themePath('/assets/js/scripts.js'))
            ->prependFile($this->basePath('/js/loading-overlay.min.js'))
            ->prependFile($this->themePath('/assets/js/revolution_slider.js'))
            ->prependFile($this->themePath('/assets/plugins/revolution-slider/js/jquery.themepunch.revolution.min.js'))
            ->prependFile($this->themePath('/assets/plugins/revolution-slider/js/jquery.themepunch.tools.min.js'))
            ->prependFile($this->themePath('/assets/plugins/flexslider/jquery.flexslider-min.js'))
            ->prependFile($this->themePath('/assets/plugins/knob/js/jquery.knob.js'))
            ->prependFile($this->themePath('/assets/plugins/owl-carousel/owl.carousel.min.js'))
            ->prependFile($this->themePath('/assets/plugins/magnific-popup/jquery.magnific-popup.min.js'))
            ->prependFile($this->themePath('/assets/plugins/bootstrap/js/bootstrap.min.js'))
            ->prependFile($this->themePath('/assets/plugins/masonry.js'))
            ->prependFile($this->themePath('/assets/plugins/jquery.isotope.js'))
            ->prependFile($this->themePath('/assets/plugins/jquery-2.1.1.min.js'))
            ->prependFile('//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js')
            ->prependFile($this->themePath('/assets/plugins/respond.js'), 'screen', 'lt IE 9')
            ->prependFile($this->themePath('/assets/plugins/modernizr.min.js'))
        ;?>
    </body>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#tweet-feed').load('<?=$this->url('twitter', [
                'action' => 'twitter-feed',
            ]);?>');

            $('#newsletter_form').on('submit', 'form', function (event) {
                event.preventDefault();

                var params = $(this).serialize();
                var el = $(this).parent();
                var url = $(this).attr('action');

                $.ajax({
                    url : url,
                    data: params,
                    type: 'POST',
                    beforeSend : function() {
                        $(el).html('<div class="text-center"><i class="fa fa-refresh fa-spin fa-3x"></i></div>');
                    },
                    success: function (response) {
                        $(el).html(response);
                    }
                });
            });

            $('#topNav .dropdown-toggle').on('click', function(e){
                var el = $(e.target);
                window.location.href = el.attr('href');
            })
        });
    </script>
</html>
