<!DOCTYPE html>
<!--[if IE 8]>			<html class="ie ie8"> <![endif]-->
<!--[if IE 9]>			<html class="ie ie9"> <![endif]-->
<!--[if gt IE 9]><!-->	<html> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <title><?=$this->themeOptions('site_name');?> - Maintenance</title>
    <meta name="keywords" content="HTML5,CSS3,Template" />
    <meta name="description" content="" />
    <meta name="Author" content="Dorin Grigoras [www.stepofweb.com]" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- mobile settings -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="<?=$this->basePath('/userfiles/favicon.ico');?>" />

    <!-- WEB FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700,800&amp;subset=latin,latin-ext,cyrillic,cyrillic-ext" rel="stylesheet" type="text/css" />

    <!-- CORE CSS -->
    <link href="<?=$this->themePath('assets/plugins/bootstrap/css/bootstrap.min.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?=$this->themePath('assets/css/font-awesome.css');?>" rel="stylesheet" type="text/css" />

    <!-- THEME CSS -->
    <link href="<?=$this->themePath('assets/css/essentials.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?=$this->themePath('assets/css/layout.css');?>" rel="stylesheet" type="text/css" />
    <link href="<?=$this->themePath('assets/css/color_scheme/red.css');?>" rel="stylesheet" type="text/css" id="color_scheme" />
</head>

<body class="grey">

<div class="maintenance">

    <h1>MAINTENANCE MODE</h1>
    <p>

        <!-- custom text -->
        <?=$this->themeOptions('site_name');?> is undergoing some <strong>scheduled</strong> maintenance. <strong>Please</strong> come back <strong>later</strong>!
        <!-- /custom text -->

    </p>

    <hr class="half-margins" />

    <!-- progress bars -->
    <div class="container">
        <div class="row text-left">
            <div class="col-md-8 col-md-offset-2">
                <!-- Logo -->
                <div class="text-center">
                    <a class="logo text-center" href="<?=$this->url('home');?>" style="text-decoration: none;">
                        <img src="<?=$this->basePath('/userfiles/logo.png');?>"  alt="logo">
                        <img src="<?=$this->basePath('/userfiles/charismabeads.png');?>"  alt="logo" >
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- /progress bars -->

    <hr class="half-margins" />

    <!-- socials -->
    <p class="block"><!-- social -->
        <?=$this->socialLinks()->render();?>
    </p><!-- /social -->
    <!-- /socials -->


</div><!-- /maintenance -->

<!-- JAVASCRIPT FILES -->
<script type="text/javascript" src="<?=$this->themePath('assets/plugins/jquery-2.1.1.min.js');?>"></script>
<script type="text/javascript" src="<?=$this->themePath('assets/plugins/bootstrap/js/bootstrap.min.js');?>"></script>

<script type="text/javascript" src="<?=$this->themePath('assets/js/scripts.js');?>"></script>
</body>
</html>