<?php 
/* @var $order \Shop\Model\Order\Order */
$order = $this->order;
/* @var $card \Shop\Model\Payment\CreditCard */
$card = $this->card;
?>
<h2>Credit Card Payment</h2>

<div>
	<table>
	    <caption>Debit/Credit Card Details</caption>
	    <tr>
	        <th>Order No.</th>
	        <td><?=$order->getOrderNumber();?></td>
	    </tr>
	    <tr>
	        <th>Total</th>
	        <td><?=$this->priceFormat($order->getTotal());?></td>
	    </tr>
	    <tr>
	        <th>Name</th>
	        <td><?=$card->getCcName();?></td>
	    </tr>
	    <tr>
	        <th>Card Type</th>
	        <td><?=$card->getCcType();?></td>
	    </tr>
	    <tr>
	        <th>Card Number</th>
	        <td><?=$card->getCcNumber();?></td>
	    </tr>
	    <tr>
	        <th>Expiry Date</th>
	        <td><?=$card->getCcExpiryDate();?></td>
	    </tr>
	    <tr>
	        <th>Card Verification Number</th>
	        <td><?=$card->getCvv2();?></td>
	    </tr>
	    <?php if ($card->getCcIssueNumber() != ''): ?>
	    <tr>
	        <th>Issue Number</th>
	        <td><?=$card->getCcIssueNumber();?></td>
	    </tr>
	    <tr>
	        <th>Start Date</th>
	        <td><?=$card->getCcStartDate();?></td>
	    </tr>
	    <?php endif; ?>
	    <tr>
	        <th>Address Line 1</th>
	        <td><?=$card->getAddress()->getAddress1();?></td>
	    </tr>
	    <?php if ($card->getAddress()->getAddress2()): ?>
	    <tr>
	        <th>Address Line 2</th>
	        <td><?=$card->getAddress()->getAddress2();?>?></td>
	    </tr>
	    <?php endif; ?>
	    <?php if ($card->getAddress()->getAddress3()): ?>
	    <tr>
	        <th>Address Line 3</th>
	        <td><?=$card->getAddress()->getAddress3()?></td>
	    </tr>
	    <? endif; ?>
	    <tr>
	        <th>Town/City</th>
	        <td><?=$card->getAddress()->getCity();?></td>
	    </tr>
	    <tr>
	        <th>County</th>
	        <td><?=$card->getAddress()->getProvince()->getProvinceName();?></td>
	    </tr>
	    <tr>
	        <th>Postcode</th>
	        <td><?=$card->getAddress()->getPostcode();?></td>
	    </tr>
	    <tr>
	        <th>Country</th>
	        <td><?=$card->getAddress()->getCountry()->getCountry();?></td>
	    </tr>
	</table>
</div>

