<?php $cats = $this->category()->getChildCategories();?>
<?php $count = -1; ?>
<?php $maxDepth = count($cats) - 1; ?>
<?php $cats->getHydrator()->addDepth(true); ?>
<?php $arrayCopy = $cats->toArray(); ?>

<!-- SIDE NAV -->
<ul class="side-nav list-group" id="sidebar-nav">

    <?php /* @var $cat \Shop\Model\Product\ProductCategoryModel */ ?>
    <?php foreach ($cats as $cat): ?>
        <?php $count++; ?>
        <?php $liClass = ($cat->hasChildren()) ? ' list-toggle' : ''; ?>

        <?php if ($cat->hasChildren()): ?>
            <li class="list-group-item<?=$liClass;?>"><!-- NOTE: "active" to be open on page load -->
            <a href="#collapse-<?=$count;?>" data-toggle="collapse">
                <?=$this->escapehtml($cat->getCategory()); ?>
            </a>
            <ul id="collapse-<?=$count;?>" class="collapse"><!-- NOTE: "collapse in" to be open on page load -->
        <?php elseif ($cat->getDepth() > 0): ?>
            <li>
            <a href="<?=$this->url('shop/catalog', [
                'categoryIdent' => $cat->getIdent()
            ]); ?>"><i class="fa fa-angle-right"></i> <?=$this->escapehtml($cat->getCategory()); ?></a>
        <?php else: ?>
            <li class="list-group-item">
            <a href="<?=$this->url('shop/catalog', [
                'categoryIdent' => $cat->getIdent()
            ]); ?>"><?=$this->escapehtml($cat->getCategory()); ?></a>
        <?php endif; ?>
        <?php // closures ?>
        <?php if ($cat->getDepth() > 0):?>
            <?php if ($count == $maxDepth): ?>
                <?=str_repeat('</li></ul>', $cat->getDepth()); ?></li>
            <?php elseif ($arrayCopy[$count + 1]['depth'] < $cat->getDepth()): ?>
                <?=str_repeat('</li></ul>', ($cat->getDepth() - $arrayCopy[$count + 1]['depth'])); ?></li>
            <?php else: ?>
                <?php if (!$cat->hasChildren()): ?>
                    </li>
                <?php endif; ?>
            <?php endif; ?>
        <?php else: ?>
            <?php if (!$cat->hasChildren()): ?>
                </li>
            <?php endif; ?>
        <?php endif; ?>

    <?php endforeach; ?>

</ul>
<!-- /SIDE NAV -->
