
<?php $this->placeholder('header')->captureStart();?>
<?=$this->partial('shop/options', [
    'title' => 'Shop Front',
    'bread' => [],
]);?>

<?php $this->placeholder('header')->captureEnd();?>

<div class="row">
    <div class="col-md-3 hidden-sm">
        <?=$this->partial('shop/product-nav');?>
    </div>
    <div class="col-md-9">
        <!-- PRODUCT CATEGORIES -->
        <div class="row">
            <?php /* @var $row \Shop\Model\Product\Category */ ?>
            <?php foreach ($this->cats as $row): ?>
                <div class="col-sm-3 col-md-3"><!-- category -->
                    <div class="box-content thumbnail text-center">
                        <a href="<?php echo $this->url('shop/catalog', [
                            'categoryIdent' => $row->getIdent()
                        ]); ?>" class="item-image"><!-- image -->
                            <img class="img-responsive" src="<?=$this->productImage($row);?>" alt="<?=$this->escapehtml($row->getCategory());?>">
                        </a>
                        <div class="caption text-left"><!-- name -->
                            <h5 class="nomargin elipsis"><?=$this->escapehtml($row->getCategory());?></h5>
                        </div>
                    </div>
                </div><!-- /category -->
            <?php endforeach; ?>
        </div>
    </div>
</div>