
<?php
$this->headTitle('Add Customer');
$this->form->get('firstname')->setAttribute('readonly', '');
$this->form->get('lastname')->setAttribute('readonly', '');
$this->form->get('email')->setAttribute('readonly', '');
?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
    'form' 			=> $this->form,
    'formName'		=> 'New Customer',
    'postUrl'		=> $this->url('admin/shop/customer/edit', [
        'action' => 'add',
    ]),
    'cancelUrl'     => $this->url('admin/shop/customer'),
    'formElements' => [
        'prefixId', 'redirectToEdit', 'firstname', 'lastname', 'email',
    ],
    'formWidth'     => '6',
    'helperOptions' => [
        'labelWidth'    => '4',
        'elementWidth'  => '8',
    ],
]); ?>

<div class="clearfix"></div>
