
<?php
$this->headTitle('Add Customer');
$this->form->get('firstname')->setAttribute('readonly', '');
$this->form->get('lastname')->setAttribute('readonly', '');
$this->form->get('email')->setAttribute('readonly', '');
?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
    'form' 			=> $this->form,
    'formAction' 	=> 'add',
    'formName'		=> 'New Customer',
    'postUrl'		=> $this->url('admin/shop/customer/edit', [
        'action' => 'add',
    ]),
    'cancelUrl'     => $this->url('admin/shop/customer'),
    'formElements' => [
        'prefixId', 'firstname', 'lastname', 'email',
    ],
]); ?>
