
<?php
$this->form->get('firstname')->setAttribute('readonly', '');
$this->form->get('lastname')->setAttribute('readonly', '');
$this->form->get('email')->setAttribute('readonly', '');
?>

<?php $this->headTitle('Edit Customer') ?>
<?php $this->layout()->pageTitle = $this->translate('Edit Customer'); ?>

<?php $this->placeholder('header-buttons')->captureStart(); ?>
<button id="form-customer-submit" form="form-customer" data-toggle="tooltip" title="<?= $this->translate('Save'); ?>"
        class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?= $this->url('admin/shop/customer'); ?>" data-toggle="tooltip" title="<?= $this->translate('Cancel'); ?>"
   class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd(); ?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-customer',
    'action' => $this->url('admin/shop/customer/edit', [
        'id' => $this->model->getCustomerId(),
    ]),
]); ?>

<div class="row">

    <div class="col-sm-6">
        <div id="customer" class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <i class="fa fa-pencil"></i> <?= $this->translate('Edit Customer'); ?>
                    <small>(<?=$this->escapeHtml($this->model->getNumber());?>)</small>
                </h3>
            </div>
            <div class="panel-body">
                <?= $this->form($this->form); ?>
            </div>
        </div>
    </div>

    <div class="col-sm-6">
        <div class="panel-group" id="accordion">
            <div id="customer-addresses" class="panel panel-info">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            Customer Addresses
                        </a>
                        <button id="add-address-button" class="btn btn-default btn-xs" href="<?=$this->url('admin/shop/customer/address', [
                            'action'    => 'add',
                            'id'        => $this->model->getCustomerId(),
                        ]);?>">Add Address
                        </button>
                        <h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse">
                    <div class="panel-body">
                        <div class="text-center">
                            <i class="fa fa-spinner fa-spin"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div id="customer-orders" class="panel panel-info">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                            Customer Orders
                        </a>

                        <button type="submit" id="add-order-button" form="form-create-order" class="btn btn-default btn-xs">
                            Create Order
                        </button>
                        <form id="form-create-order" action="<?=$this->url('admin/shop/order/create', [
                            'action' => 'add',
                        ]); ?>" method="post">
                            <input type="hidden" name="customerId" value="<?=$this->model->getCustomerId();?>">
                        </form>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse in">
                    <div class="panel-table">
                        <div class="text-center">
                            <i class="fa fa-spinner fa-spin"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="clearfix"></div>

<?php $this->inlineScript()
    ->appendFile($this->basePath('js/admin/shop.js'))
    ->appendFile($this->basePath('js/admin/customer-edit.js'));?>

<?php $this->placeholder('js-scripts')->captureStart();?>
<script>
    customer.customerId = '<?=$this->escapeHtml($this->model->getCustomerId());?>';
</script>
<?php $this->placeholder('js-scripts')->captureEnd();?>
