

<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'customer',
	'searchInputs'	=> [
		'Customer'	=> 'firstname-lastname',
		'Address'	=> 'address'
	],
]);?>
	    	
<div id="table-customer">
	<?=$this->partial('shop/customer/list', [
	    'models' => $this->models
	]); ?>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-customer').dataGrid({
	    url : 'customer/list',
	    query: { sort : 'name' },
	    searchForm : $('#search-customer'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->inlineScript()->captureEnd(); ?>

