
<?php $this->headTitle('Customers') ?>
<?php $this->layout()->pageTitle = $this->translate('Customers'); ?>

<?php $this->placeholder('header-buttons')->captureStart(); ?>
<a href="<?= $this->url('admin/shop/customer/edit', [
    'action' => 'add'
]); ?>" type="submit" form="form-customers" data-toggle="tooltip"
   title="<?= $this->translate('Add Customer'); ?>" class="btn btn-primary">
    <i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd(); ?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?= $this->translate('Customer List'); ?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('admin/partial/search', [
            'name'			=> 'customer',
            'searchInputs'	=> [
                'Customer'	=> 'firstname-lastname',
                'Address'	=> 'address1-address2-address3-city-county-postcode-phone'
            ],
        ]);?>
    </div>
    <div id="table-customer" class="admin-table">
        <?=$this->partial('shop/customer/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<?php $this->inlineScript()
    ->appendFile($this->basePath('js/admin/shop.js'))
    ->appendFile($this->basePath('js/admin/customer-list.js'));?>

<?php $this->placeholder('js-scripts')->captureStart();?>
<script>
    $('#table-customer').dataGrid({
        url: 'customer/list',
        query: {sort: 'name'},
        searchForm: $('#search-customer'),
        columnSort: true
    });
</script>
<?php $this->placeholder('js-scripts')->captureEnd();?>
