
<?php if (count($this->models) > 0): ?>
<div class="table-responsive">
    <table id="customer-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="customerId">Customer Id</th>
                <th data-field="number">Customer No.</th>
    			<th data-field="name">Name</th>
    			<th data-field="dateCreated">Date Created</th>
    			<th data-field="dateModified">Date Modified</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    		<?php /* @var $row \Shop\Model\Customer\Customer */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getCustomerId());?></td>
                <td><?=$this->escapeHtml($row->getNumber());?></td>
    			<td><?=$this->escapeHtml($row->getLastNameFirst());?></td>
    			<td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
    			<td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
    			<td>
                    <button type="submit" form="form-create-order-<?=$row->getCustomerId();?>" data-toggle="tooltip" title="<?= $this->translate('Create Order'); ?>"
                            class="btn btn-default">
                        <i class="fa fa-shopping-bag"></i>
                    </button>

                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                    	'pk'		=> 'customerId',
                    	'id'		=> $row->getCustomerId(),
    		    		'tableName'	=> 'customer',
                    	'route'		=> 'admin/shop/customer/edit',
    		    	]);?>
                    <form id="form-create-order-<?=$row->getCustomerId();?>" action="<?=$this->url('admin/shop/order/create', [
                        'action' => 'add',
                    ]); ?>" method="post">
                        <input type="hidden" name="customerId" value="<?=$row->getCustomerId();?>">
                    </form>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/shop/customer/page']
); ?>

<?php else: ?>
<h4>No Customers where returned by search.</h4>
<?php endif; ?>
