<?php $this->headTitle('Customers') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->models) > 0): ?>

<table id="customer-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="customerId">Customer Id</th>
			<th data-field="name">Name</th>
			<th data-field="dateCreated">Date Created</th>
			<th data-field="dateModified">Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php /* @var $row \Shop\Model\Customer */ ?>
		<?php foreach($this->models as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getCustomerId());?></td>
			<td><?=$this->escapeHtml($row->getLastNameFirst());?></td>
			<td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
			<td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
			<td>
                <?=$this->partial('partial/edit-actions', array(
                	'pk'		=> 'customerId',
                	'id'		=> $row->getCustomerId(),
		    		'tableName'	=> 'customer',
                	'route'		=> 'admin/shop/customer/edit',
		    	));?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/customer/page')
); ?>

<?php else: ?>
<h4>No Customers where returned by search.</h4>
<?php endif; ?>
