<?php $this->headTitle('Customers') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->customers) > 0): ?>

<table id="customer-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="customerId">Customer Id</th>
			<th data-field="name">Name</th>
			<th data-field="dateCreated">Date Created</th>
			<th data-field="dateModified">Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach($this->customers as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getCustomerId());?></td>
			<td><?=$this->escapeHtml($row->getLastNameFirst());?></td>
			<td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
			<td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
			<td>
                <a href="<?=$this->url('admin/shop/customer/edit', array(
                    'id' => $row->getCustomerId()
				)); ?>" class="btn">Edit</a>
				&nbsp;
				
				<!-- Button to trigger modal -->
                <a href="#cusomerModel<?=$row->getCustomerId(); ?>" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="customerModel<?=$row->getCustomerId(); ?>">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
				    <h3 id="customerModel<?=$row->getCusomerId(); ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?=$this->url('admin/shop/customer/edit', array(
				        'action' => 'delete',
				    )) ?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this category.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="customerId" value="<?=$row->getCustomerId() ?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->customers,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/customer/page')
); ?>

<?php else: ?>
<h4>No Customers where returned by search.</h4>
<?php endif; ?>
