
<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('layout/page-title', [
    'pageTitle' => 'Order Summary'
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<div class="row">
    <div class="printable"><!-- note class 'printable' - this area is printable only! -->

        <!-- CALLOUT -->
        <div class="alert alert-default fade in">

            <div class="row">

                <div class="col-md-9 col-sm-9"><!-- left text -->
                    <h4><strong>Order</strong> Date</h4>
                    <p>
                        <?=$this->formatDate($this->order->getOrderDate())->setFormat('d/m/Y');?>
                    </p>
                </div><!-- /left text -->


                <div class="col-md-3 col-sm-3 text-right"><!-- right btn -->
                    <a href="#" class="btn btn-primary btn-lg" onclick="window.print();">PRINT</a>
                </div><!-- /right btn -->

            </div>

        </div>
        <!-- /CALLOUT -->

        <div class="divider half-margins"><!-- divider 30px --></div>

        <!-- BILLING and SHIPPING ADDRESS -->
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h5><strong>BILLING ADDRESS</strong></h5>
                <p>
                    <?=$this->customerAddress($this->order)
                        ->includeName()
                        ->includeEmail()
                        ->formatAddress(
                            $this->order->getMetadata()
                                ->getBillingAddress()
                        );?>
                </p>
            </div>

            <div class="col-md-6 col-sm-6">
                <h5><strong>SHIPPING ADDRESS</strong></h5>
                <p>
                    <?=$this->customerAddress($this->order)
                        ->includeName()
                        ->formatAddress(
                            $this->order->getMetadata()
                                ->getDeliveryAddress()
                    );?>
                </p>
            </div>
        </div>
        <!-- /BILLING and SHIPPING ADDRESS -->


        <!-- SUMMARY TABLE -->
        <div class="cartContent margin-top30">
            <!-- cart header -->
            <div class="item head">
                <span class="cart_img"></span>
                <span class="product_name fsize13 bold">PRODUCT NAME</span>
                <span class="total_price fsize13 bold">TOTAL</span>
                <span class="qty fsize13 bold">QUANTITY</span>
                <div class="clearfix"></div>
            </div>
            <!-- /cart header -->

            <?php /* @var $item \Shop\Model\Order\Line */ ?>
            <?php foreach ($this->order->getOrderlines() as $item): ?>
            <!-- cart item -->
            <div class="item">
                <div class="cart_img"><img src="<?=$this->productImage($item->getMetadata()->getImage());?>" alt="" width="60" /></div>
                <div class="product_name">
                    <?=$item->getMetadata()->getName();?> /
                    <?=$item->getMetadata()->getCategory();?> /
                    <?=$item->getMetadata()->getDescription();?>
                </div>
                <div class="total_price"><span><?=$this->priceFormat($item->getPrice());?></span></div>
                <div class="qty"><?=$item->getQty();?> &times; <?=$this->priceFormat($item->getPrice());?></div>
                <div class="clearfix"></div>
            </div>
            <!-- /cart item -->
            <?php endforeach;?>

            <!-- cart total -->
            <div class="total pull-right">
                <small>
                    Shipping: <?=$this->priceFormat($this->order->getShipping());?>
                </small>

                <span class="totalToPay styleSecondColor">
                    TOTAL: <?=$this->priceFormat($this->order->getTotal());?>
                </span>

            </div>
            <!-- /cart total -->

            <div class="clearfix"></div>
        </div>
        <!-- /SUMMARY TABLE -->

    </div>
</div>