
<h1>Change Password</h1>
<form action="<?=$_SERVER['PHP_SELF'];?>" method="post">
    <div class="box">
    	<table style="margin-right:auto; margin-left:auto;">
    		<tr>
                <td colspan="3">
                    <div class="captcha_notvalid">
                        <?php foreach ($this->form->getMessages() as $errors):?>
                        	<?php foreach ($errors as $error): ?>
                        	<p><?=$error;?></p>
                        	<?php endforeach;?>
                        <?php endforeach;?>
                    </div>
                </td>
            </tr>
			<tr>
				<td class="<?php if ($this->form->get('password')->getMessages()) echo ' has-error'; ?>">
					<b><?=$this->form->get('password')->getLabel();?></b>
				</td>
				<td class="<?php if ($this->form->get('password')->getMessages()) echo ' has-error'; ?>">
					<?=$this->formPassword($this->form->get('password'));?>
				</td>
				<td width="130" style="border:1px dashed black;background-color:white;font-weight:bold;text-transform:capitalize;font-size:10px;">
					<p style="margin:0px;background-color:skyblue;text-align:center">strength meter</p>
					<p id="passBar" style="margin:0px;height:14px;width:32px;background-image:url(/admin/images/stat_barreend.png);float:right;">
						<img src="/admin/images/stat_barreend.png" alt="">
						<img id="bar" src="/admin/images/stat_barre.png" alt="" height="14" width="0">
						<img src="/admin/images/stat_barreend.png" alt="">
					</p>
					<p id="passStrength" style="margin:0px;">score: 0/30<br />verdict: </p>
				</td>
			</tr>
			<tr>
				<td colspan="3">
					<small>Use only letters, numbers and ! &pound; $ % &amp; / \ ( ) = ? + * # - . , ; : _ <br />Must between 4 and 20 characters long with no spaces</small>
				</td>
			<tr>
    		<tr class="<?php if ($this->form->get('password-confirm')->getMessages()) echo ' has-error'; ?>">
    			<td>
    				<b><?=$this->form->get('password-confirm')->getLabel();?></b>
   				</td>
   				<td>
   					<?=$this->formPassword($this->form->get('password-confirm'));?>
  				</td>
  				<td>&nbsp;</td>
			</tr>
			<tr>
				<td colspan="3" style="text-align:center;">
					<input type="submit" name="submit" value="Change Password" class="submit"/>
					<?=$this->formHidden($this->form->get('security'));?>
				</td>
			</tr>
    	</table>
    </div>
</form><!-- End of form -->