
<h2>Please us the contact form below to get in touch with us</h2>

<p>If you have a comment about the website or any technical problems relating to the website or the on-line shop then please email the webmaster</p>
<p>If you have any queries about Charisma, the beads or any other things related to the shop and products, then there are three ways you can contact us 
- apart from visiting the shop of course!</p>

<div id="contact-form">
    <form class="captcha" action="<?=$this->https;?>/pages/contacts" method="post">
		<table>
			<tr>
                <td colspan="5">
                    <div class="captcha_notvalid">
                        <?php foreach ($this->form->getMessages() as $errors):?>
                        	<?php foreach ($errors as $error): ?>
                        	<p><?=$error;?></p>
                        	<?php endforeach;?>
                        <?php endforeach;?>
                    </div>
                </td>
            </tr>
			<tr>
				<td align="right" class="<?php if ($this->form->get('name')->getMessages()) echo ' has-error'; ?>"><b><?=$this->form->get('name')->getLabel();?></b></td>
				<td class="<?php if ($this->form->get('name')->getMessages()) echo ' has-error'; ?>"><?=$this->formText($this->form->get('name'));?></td>
				<td>&nbsp;</td>
				<td align="right" class="<?php if ($this->form->get('email')->getMessages()) echo ' has-error'; ?>"><b><?=$this->form->get('email')->getLabel();?></b></td>
				<td class="<?php if ($this->form->get('email')->getMessages()) echo ' has-error'; ?>"><?=$this->formEmail($this->form->get('email'));?></td>
			</tr>
			<tr>
				<td colspan="2" class="errors"><?=$this->formElementErrors($this->form->get('name')); ?></td>
				<td>&nbsp;</td>
				<td colspan="2" class="errors"><?=$this->formElementErrors($this->form->get('email')); ?></td>
			</tr>
            <tr>
                <td align="right" colspan="1" class="<?php if ($this->form->get('phone')->getMessages()) echo '
                has-error'; ?>"><b><?=$this->form->get('phone')->getLabel();?></b></td>
                <td colspan="4" class="<?php if ($this->form->get('phone')->getMessages()) echo ' has-error';?>"><?=$this->formText($this->form->get('phone'));?></td>
            </tr>
            <tr>
                <td colspan="5" class="errors"><?=$this->formElementErrors($this->form->get('phone')); ?></td>
            </tr>
			<tr>
				<td align="right" colspan="1" class="<?php if ($this->form->get('subject')->getMessages()) echo ' has-error'; ?>"><b><?=$this->form->get('subject')->getLabel();?></b></td>
				<td colspan="4" class="<?php if ($this->form->get('subject')->getMessages()) echo ' has-error'; ?>"><?=$this->formText($this->form->get('subject'));?></td>
			</tr>
			<tr>
				<td colspan="5" class="errors"><?=$this->formElementErrors($this->form->get('subject')); ?></td>
			</tr>
			<tr>
				<td align="right" colspan="1" class="<?php if ($this->form->get('department')->getMessages()) echo ' has-error'; ?>"><b><?=$this->form->get('department')->getLabel();?></b></td>
				<td colspan="4" class="<?php if ($this->form->get('department')->getMessages()) echo ' has-error'; ?>"><?=$this->formSelect($this->form->get('department'));?></td>
			</tr>
			<tr>
				<td colspan="5" class="errors"><?=$this->formElementErrors($this->form->get('department')); ?></td>
			</tr>
			<tr>
				<td align="right" colspan="1" class="<?php if ($this->form->get('message')->getMessages()) echo ' has-error'; ?>"><b><?=$this->form->get('message')->getLabel();?></b></td>
				<td colspan="4" class="<?php if ($this->form->get('message')->getMessages()) echo ' has-error'; ?>"><?=$this->formTextarea($this->form->get('message'));?></td>
			</tr>
			<tr>
				<td colspan="5" class="errors"><?=$this->formElementErrors($this->form->get('message')); ?></td>
			</tr>
			<tr>
                <td colspan="2" class="<?php if ($this->form->get('captcha')->getMessages()) echo ' has-error'; ?>">
                	<?php $this->formCaptchaImage()->setSeparator('<br>'); ?>
                	<b><?=$this->form->get('captcha')->getLabel();?></b><br>
                    <?=$this->formCaptchaImage($this->form->get('captcha'));?>
                    <?=$this->formElementErrors($this->form->get('captcha')); ?>
                </td>
                <td>&nbsp;</td>
                <td colspan="2" valign="top">
                    <div class="notes">
                        <h3>Security Measure</h3>
                        <p>Type the characters you see into the blank field, without spaces.</p>
                        <br />
                        <p>This helps <?=$this->merchantName;?> prevent automated login and increases the security of our network.</p>
                    </div>
                 </td>
            </tr>
            <tr>
                <td colspan="5">
                    <p>
                        <input type="submit" name="submit" value="Submit" class="button" />
                        <?=$this->formHidden($this->form->get('security'));?>
                    </p>
                </td>
            </tr>
		</table>
	</form>
</div>