<html>
<head>
<title><?= $this->title; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=uft-8" />
<meta name="Content-Language" content="english" />
<style type="text/css">
body {
	background-color:white;
	font-size:10pt;
}
#merchant {
	text-align:center;
	font-weight:bold;
	font-size:26pt;
}
</style>
</head>
<body> 
<div id="merchant"><?= $this->merchant; ?></div>
<div>
	<table>
	    <caption>Debit/Credit Card Details</caption>
	    <tr>
	        <th>Order No.</th>
	        <td><?= $this->invoiceNumber; ?></td>
	    </tr>
	    <tr>
	        <th>Total</th>
	        <td>&pound;<?= $this->post['total']; ?></td>
	    </tr>
	    <tr>
	        <th>Name</th>
	        <td><?= $this->post['ccName']; ?></td>
	    </tr>
	    <tr>
	        <th>Card Type</th>
	        <td><?= $this->post['ccType']; ?></td>
	    </tr>
	    <tr>
	        <th>Last Four Digits of Card</th>
	        <td><?= substr($this->post['ccNumber'], -4); ?></td>
	    </tr>
	    <tr>
	        <th>Expiry Date</th>
	        <td><?= $this->post['ccExpiryMonth']; ?>/<?= $this->post['ccExpiryYear']; ?></td>
	    </tr>
	    <tr>
	        <th>Card Verification Number</th>
	        <td><?= $this->post['ccCardVerificationNumber']; ?></td>
	    </tr>
	    <? if ($this->post['ccIssueNumber']): ?>
	    <tr>
	        <th>Issue Number</th>
	        <td><?= $this->post['ccIssueNumber']; ?></td>
	    </tr>
	    <tr>
	        <th>Start Date</th>
	        <td><?= $this->post['ccStartMonth']; ?>/<?= $this->post['ccStartYear']; ?></td>
	    </tr>
	    <? endif; ?>
	    <tr>
	        <th>Address Line 1</th>
	        <td><?= $this->post['addressLine1']; ?></td>
	    </tr>
	    <? if ($this->post['addressLine2']): ?>
	    <tr>
	        <th>Address Line 2</th>
	        <td><?= $this->post['addressLine2']; ?></td>
	    </tr>
	    <? endif; ?>
	    <? if ($this->post['addressLine3']): ?>
	    <tr>
	        <th>Address Line 3</th>
	        <td><?= $this->post['addressLine3']; ?></td>
	    </tr>
	    <? endif; ?>
	    <tr>
	        <th>Town/City</th>
	        <td><?= $this->post['city']; ?></td>
	    </tr>
	    <tr>
	        <th>County</th>
	        <td><?= $this->post['county']; ?></td>
	    </tr>
	    <tr>
	        <th>Postcode</th>
	        <td><?= $this->post['postcode']; ?></td>
	    </tr>
	    <tr>
	        <th>Country</th>
	        <td><?= $this->post['country']; ?></td>
	    </tr>
	</table>
</div>
</body>
</html>