<h3 class="center">Reset Your Password</h3>
<p class="center">Enter your email below and your password will be reset.</p>
<div id="captcha">
	<form class="captcha" action="<?=$_SERVER['PHP_SELF']?>" method="post">
		 <table align="center">
	    	<tr>
	        	<td colspan="2">
					<div class="captcha_notvalid">
					<?php foreach ($this->form->getMessages() as $errors):?>
					<?php foreach ($errors as $error): ?>
						<p><?=$error;?></p>
					<?php endforeach;?>
					<?php endforeach;?>
					</div>
				</td>
				
			</tr>
	        <tr>
	        	<td colspan="2">
	        		<table>
			        	<tr class="<?php if ($this->form->get('email')->getMessages()) echo ' has-error'; ?>">
			        		<td class="label"><b><?=$this->form->get('email')->getLabel()?></b></td>
			                <td><?=$this->formEmail($this->form->get('email'));?></td>
			        	</tr>
		        	</table>
	        	</td>
	        </tr>
	        <tr>
				<td class="<?php if ($this->form->get('captcha')->getMessages()) echo ' has-error'; ?>">
				<?php $this->formCaptchaImage()->setSeparator('<br>'); ?>
					<b><?=$this->form->get('captcha')->getLabel();?></b><br>
					<?=$this->formCaptchaImage($this->form->get('captcha'));?>
					<?=$this->formElementErrors($this->form->get('captcha')); ?>
				</td>
				<td valign="top">
					<div class="notes">
						<h3>Security Measure</h3>
						<p>Type the characters you see into the blank field, without spaces.</p>
						<br />
						<p>This helps <?=$this->merchantName;?> prevent automated form submissions and increases the security of our network.</p>
					</div>
				</td>
			</tr>
		</table>
		
		<div class="center"><input class="submit" type="submit" name="submit" value="Reset My Password" /></div>
		<?=$this->formHidden($this->form->get('security'));?>
	    
	</form><!-- End of form -->
</div>