<?=$this->headScript()
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/innovaeditor.js'))
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/jquery.innovaeditor.js'))
    ->appendFile('//ajax.googleapis.com/ajax/libs/webfont/1/webfont.js')
    ->appendFile($this->themePath('/assets/js/LiveEditor/scripts/common/webfont.js'));
?>
<?php $this->headTitle('Edit Article') ?>

<?=$this->partial('uthando-article/article/article-form', [
    'form' => $this->form,
    'formAction' => 'edit',
    'articleId' => $this->model->getArticleId()
]); ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('#article-content-textarea').liveEdit({
            css: [
                'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css',
                'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css',
                'http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css'
            ] /* Apply bootstrap css into the editing area */ ,
            groups: [
                ["group1", "", ["Bold", "Italic", "Underline", "ForeColor", "RemoveFormat"]],
                ["group2", "", ["Bullets", "Numbering", "Indent", "Outdent"]],
                ["group3", "", ["Paragraph", "FontSize", "FontDialog", "TextDialog"]],
                ["group4", "", ["LinkDialog", "ImageDialog", "TableDialog", "Emoticons", "Snippets"]],
                ["group5", "", ["Undo", "Redo", "FullScreen", "SourceDialog"]]
            ] /* Toolbar configuration */ ,
            fileBrowser: '/admin/asset-manager'
        });
        $('#article-content-textarea').data('liveEdit').startedit(); /* Run the Editor */
    });
</script>

