<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <?php echo $this->headTitle('Control Panel')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?> 
        
        <!-- Styles -->
        <?php echo $this->headLink(array(
                'rel'  => 'shortcut icon', 
                'type' => 'img/vnd.microsoft.icon', 
                'href' => $this->basePath() . '/img/favicon.ico')
            )
            ->prependStylesheet('http://fonts.googleapis.com/css?family=Abel')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-extend.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
            ->prependStylesheet($this->basePath() . '/css/adminstyle.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        
        <?php echo $this->headScript()
        	->prependFile($this->basePath() . '/js/bootstrap.min.js')
        	->prependFile($this->basePath() . '/js/admin.js')
        	->prependFile($this->basePath() . '/js/LiveEditor/scripts/common/webfont.js')
        	->prependFile('http://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js')
        	->prependFile($this->basePath() . '/js/LiveEditor/scripts/innovamanager.js')
        	->prependFile($this->basePath() . '/js/LiveEditor/scripts/innovaeditor.js')
        	->prependFile($this->basePath() . '/js/jquery.datatable.js')
        	->prependFile($this->basePath() . '/js/jquery.placeholder.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>
       
    </head>
    <body>
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div id="top-bar-nav" class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">&nbsp;</a>
                    <div class="nav-collapse collapse">
                    	<?php echo $this->aclMenu('Admin\Navigation'); ?>
                    </div><!--/.nav-collapse -->
                    <div class="dropdown">
	                    <ul class="nav pull-right">
	                	    <li>
	                	        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	    					        <?php echo $this->ztbIcon()->user(); ?> <?php echo $this->identity()->getFullName(); ?> 
	    					        <b class="caret"></b>
	    				        </a>
	    				        
	                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
	                                <li>
	                                    <a href="<?php echo $this->url('admin/user/edit', array(
	                                    	'action' => 'edit',
	                	                    'id'     => $this->identity()->userId
	            	                    )); ?>">Edit Profile
	    				                </a>
	                                </li>
	                                <li>
	                                    <a href="<?php echo $this->url('user/logout'); ?>">Logout</a>
	                                </li>
	                            </ul>
	                	    </li>
	                	</ul>
                	</div>
                </div>
            </div>
        </div>
        <div id="main-content" class="container-fluid">
        	<div class="row-fluid">
        		<div class="span12">
        			<?php echo $this->content; ?>
        		</div>
        	</div>
            
            <hr>
            <footer class="container-fluid">
                <div class="row-fluid">
                    <p class="span3">Zend Framework <?php echo \Zend\Version\Version::VERSION ?></p>
                    <p class="span3">Icons from <a href="http://glyphicons.com">Glyphicons</a></p>
                </div>
            </footer>
        </div> <!-- /container -->
        <div class="loading admin-loading"><!-- Place at bottom of page --></div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>

