
<div id="alerts" class="col-md-12">
    <?=$this->tbFlashMessenger()->render(); ?>
</div>

<div class="col-md-12">
    <?=$this->partial('uthando-admin/partial/add-edit-form', array(
        'form' 			=> $this->form,
        'formAction' 	=> 'add',
        'formName'		=> 'Country Province',
        'formElements'	=> array(
            'countryProvinceId', 'countryId', 'countryProvinceCode',
            'provinceName', 'provinceAlternateNames',
        ),
        'helperOptions' => [
            'labelWidth'    => '4',
            'elementWidth'  => '8',
        ],
    )); ?>
</div>
