
<div id="alerts" class="col-md-12">
    <?=$this->tbFlashMessenger()->render(); ?>
</div>

<div class="col-md-12">
    <?=$this->partial('uthando-admin/partial/add-edit-form', [
        'form' 			=> $this->form,
        'formElements'	=> [
            'provinceId', 'countryId', 'provinceCode',
            'provinceName', 'provinceAlternateNames',
        ],
        'helperOptions' => [
            'labelWidth'    => '4',
            'elementWidth'  => '8',
        ],
    ]); ?>
</div>
