<?php $this->headTitle('Add Country Province') ?>
<?=$this->ztbFlashMessenger()->render(); ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', array(
	'form' 			=> $this->form,
	'formAction' 	=> 'add',
	'formName'		=> 'Country Province',
	'postRoute'		=> 'admin/shop/country/province/edit',
	'cancelRoute'	=> 'admin/shop/country/province',
	'formElements'	=> array(
		'countryProvinceId', 'countryId', 'countryProvinceCode',
        'provinceName', 'provinceAlternateNames',
	),
)); ?>
