
<div class="tab-wrap">
<!-- 
	<ul id="countryProvinceTabs" class="nav nav-tabs">
	    <li><a href="#admin-postCost">Post Costs</a></li>
	</ul>
	
	<div id="countryProvinceTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-countryProvince">
	    -->
	    	<div class="row-fluid">
		    	<?=$this->partial('partial/search', array(
		    		'name'			=> 'countryProvince',
		    		'searchInputs'	=> array(
		    			'Province' => 'provinceName',
		    		),
		    	));?>
	    	</div>
	    	
	    	<div id="table-countryProvince" class="row-fluid table-wrap">
		    	<?=$this->partial('shop/country-province/list', array(
		    	    'models' => $this->models
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-countryProvince').dataGrid({
	    url : 'province/list',
	    query: { sort : 'countryCode' },
	    searchForm : $('#search-countryProvince'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->headScript()->captureEnd(); ?>
