
<?php $routeParams = (is_array($this->routeParams)) ? $this->routeParams : []; ?>

<!-- PAGINATION -->
<div class="row">

    <div class="col-md-6 text-left">
        <p class="hidden-xs pull-left nomargin padding20">
            Showing <?=$this->firstItemNumber ?>-<?=$this->lastItemNumber ?> of <?=$this->totalItemCount ?> results.
        </p>
    </div>

    <div class="col-md-6 responsive-text-center text-right">
        <ul class="pagination">
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?=$this->url($this->route, array_merge($routeParams, ['page' => $this->previous])); ?>">
                        <i class="fa fa-chevron-left"></i>
                    </a>
                </li>
            <?php endif; ?>
            <?php if($this->current > 1 && $this->firstPageInRange > 1): ?>
                <li>
                    <a href="<?=$this->url($this->route, array_merge($routeParams, ['page' => $this->first])); ?>">
                        1
                    </a>
                </li>
            <?php endif; ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?=$this->url($this->route, array_merge($routeParams, ['page' => $page])); ?>">
                            <?=$page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="">
                            <?=$page; ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if($this->current != $this->last && $this->last > $this->lastPageInRange): ?>
                <li id="last-in-range">
                    <a href="<?=$this->url($this->route, array_merge($routeParams, ['page' => $this->last])); ?>">
                        <?=$this->last; ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?=$this->url($this->route, array_merge($routeParams, ['page' => $this->next])); ?>">
                        <i class="fa fa-chevron-right"></i>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>

</div>
<!-- /PAGINATION -->