
<?php if ($this->cart()->countItems()): ?>
<table class="table table-condensed table-striped table-bordered">
	<tr>
		<th>Name/Qty</th>
		<th>Cost</th>
	</tr>
	<?php /* @var $item \Shop\Model\Cart\Item */ ?>
	<?php foreach ($this->cart()->getCart() as $item): ?>
		<tr>
			<td><?=$item->getMetadata()->getName();?> X <?=$item->getQuantity();?></td>
			<td><?=$this->cart()->getLineCost($item);?>
		</tr>
	<?php endforeach; ?>
		<tr>
			<th>Total</th>
			<th><?=$this->cart()->getSubTotal();?></th>
		</tr>
</table>

<a href="<?=$this->url('shop/cart', [
	'action' => 'view'
]);?>">View Cart <i class="icon-chevron-right"></i></a>
		
<?php else: ?>
	<p>No Items</p>
<?php endif; ?>
