<?php $checkout = ($this->checkout === true) ?: false; ?>
<div class="panel panel-default">
    <table class="table table-bordered table-striped">
    	<tr>
    		<th>Product</th>
    		<th>Description</th>
    		<th>Price</th>
    		<th>Quantity</th>
    		<th>Total</th>
    		<?php if (!$checkout): ?>
    		<th>&nbsp;</th>
    		<?php endif; ?>
    	</tr>
    	
    	<?php /* @var $item \Shop\Model\Cart\Item */ ?>
    	<?php foreach ($this->cart()->getCart() as $item): ?>
    	<tr>
    		<td><?=$item->getMetadata()->getSku();?></td>
    		<td>
    		  <?=$item->getMetadata()->getCategory();?> / <?=$item->getMetadata()->getName();?>
    		  <?php if ($item->getMetadata()->getPostUnit() > 0): ?>
              &nbsp;(<?=$item->getMetadata()->getPostUnit();?> grams)
              <?php endif; ?>
		    </td>
    		<td><?=$this->cart()->formatAmount($item->getPrice());?></td>
    		<td>
    		    <?php if (!$checkout): ?>
    		    <div class="col-sm-5">
                    <input type="number" name="quantity[<?=$item->getMetadata()->getProductId();?>]" class="form-control" value="<?=$item->getQuantity();?>">
    			</div>
    			<?php else: ?>
    			<?=$item->getQuantity();?>
    			<?php endif; ?>
    		</td>
    		<td><?=$this->cart()->getLineCost($item);?></td>
    		<?php if (!$checkout): ?>
    		<td>
                <a href="<?=$this->url('shop/cart', array(
                    'action'	=> 'remove',
                    'id'		=> $item->getCartItemId()
                ));?>"><i class="glyphicon glyphicon-remove"></i></a>
            </td>
            <?php endif; ?>
    	</tr>
    	<?php endforeach; ?>
    	<?php if ($this->countryId): ?>
    	<tr>
            <td colspan="2">&nbsp;</td>
    	    <th colspan="2"><p class="text-right">Postage:</p></th>
    	    <td><?=$this->cart()->getShippingTotal($this->countryId);?></td>
    	    <?php if (!$checkout): ?>
    	    <td>&nbsp;</td>
    	    <?php endif; ?>
    	</tr>
    	<?php endif; ?>
    	<tr>
            <td colspan="2">&nbsp;</td>
    	    <th colspan="2"><p class="text-right">Total:</p></th>
    	    <td><?=$this->cart()->getTotal();?></td>
    	    <?php if (!$checkout): ?>
    	    <td>&nbsp;</td>
    	    <?php endif; ?>
    	</tr>
    </table>
</div>
