<div class="row">
    <h2>Shopping Cart</h2>
    <?php if ($this->cart()->countItems()): ?>
    <form method="post" action="<?=$this->url('shop/cart', array(
    	'action' => 'update'
    ));?>">
        <?=$this->partial('shop/cart'); ?>
        <div class="text-center">
        	<button name="update" class="btn" value="update">Update Cart</button>
        	<a href="<?=$this->url('shop/checkout');?>" class="btn">Check Out</a>
        	<a href="<?=$this->url('shop/cart', array(
        		'action' => 'empty'
        	));?>" class="btn">Empty Cart</a>
        </div>
    </form>
    <?php else: ?>
    <div>
    	<h4>No Items In Shopping Cart</h4>
    </div>
    <?php endif; ?>
</div>
