
    <h2>Shopping Cart</h2>
    <?php if ($this->cart()->countItems()): ?>
    <form method="post" action="<?=$this->url('shop/cart', [
    	'action' => 'update'
    ]);?>">
        
        <?=$this->partial('shop/cart'); ?>
        
        <div class="text-center">
        	<button name="update" class="btn btn-default" value="update">Update Cart</button>
        	<a href="<?=$this->url('shop/checkout');?>" class="btn btn-primary">Check Out</a>
        	<a href="<?=$this->url('shop/cart', [
        		'action' => 'empty'
        	]);?>" class="btn btn-danger">Empty Cart</a>
        </div>
    </form>
    <?php else: ?>
    <div>
    	<h4>No Items In Shopping Cart</h4>
    </div>
    <?php endif; ?>

