
<?php $this->headTitle('Add Address') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
	'form'         => $this->form,
	'formName'     => 'Add Address',
	'postUrl'      => $this->url('shop/customer/address', [
	    'action'   => 'add-address',
    ]),
	'cancelUrl'    => $this->url('shop/customer/address'),
	'formElements' => [
		'customerAddressId', 'address1', 'address2', 'address3',
        'city', 'provinceId', 'postcode', 'countryId',
        'phone',
	],
]); ?>

<script>
$(document).ready(function(){
    $('#countryId').change(function() {
    	$.ajax({
    		url : '<?=$this->basePath('/shop/country/province');?>',
    		data : {countryId : this.value},
    		type : 'POST'
    	}).done(function(data){
          	$('#provinceId').html( data );
    	});
	});
});
</script>
