
<ul class="nav nav-pills nav-second">
    <?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->uthandoNavigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasChildren(); ?>
        <?php if(!$hasChildren): ?>
            <li class="hidden-xs<?php if ($page->isActive(true)) echo ' active'; ?>">
                <a href="<?=$page->getHref() ?>">
                    <i class="fa fa-angle-right"></i> <?=$page->getLabel() ?>
                </a>
            </li>
        <?php endif ?>
    <?php endforeach ?>
    <li class="quick-cart dropdown pull-right">
        <?=$this->cart()->getSummary('shop/cart/summary'); ?>
    </li>
</ul>