
<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('layout/page-title', [
    'pageTitle' => 'Account Settings'
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<div class="row">

    <div class="col-md-4">
        <?=$this->uthandoNavigation()
            ->uthandoTbDbMenu('user-menu')
            ->setUlClass('side-nav list-group')
            ->setAddClassToListItem();?>
    </div>

    <div class="col-md-8">

        <!-- personal settings -->
        <form action="<?=$this->url('shop/customer');?>" method="post" class="sky-form boxed">
            <header>Personal Settings <span class="pull-right">
                    Cus No: <?=$this->escapeHtml($model->getNumber());?>
                </span>
            </header>

            <fieldset>
                <div class="row">
                    <section class="col col-md-2<?php if ($this->form->get('prefixId')->getMessages()) echo ' state-error'; ?>">
                        <label class="label"><?=$this->form->get('prefixId')->getLabel();?></label>
                        <label class="select">
                            <?=$this->formSelect($this->form->get('prefixId'));?>
                            <i></i>
                        </label>
                    </section>
                    <section class="col col-md-5<?php if ($this->form->get('firstname')->getMessages()) echo ' state-error'; ?>">
                        <label class="label"><?=$this->form->get('firstname')->getLabel();?></label>
                        <label class="input">
                            <i class="icon-append fa fa-user"></i>
                            <?=$this->formText($this->form->get('firstname'));?>
                            <b class="tooltip tooltip-bottom-right">Only latin characters and numbers</b>
                        </label>
                    </section>
                    <section class="col col-md-5<?php if ($this->form->get('lastname')->getMessages()) echo ' state-error'; ?>">
                        <label class="label"><?=$this->form->get('lastname')->getLabel();?></label>
                        <label class="input">
                            <i class="icon-append fa fa-user"></i>
                            <?=$this->formText($this->form->get('lastname'));?>
                            <b class="tooltip tooltip-bottom-right">Only latin characters and numbers</b>
                        </label>
                    </section>
                </div>

                <div class="row">
                    <section class="col col-md-12<?php if ($this->form->get('email')->getMessages()) echo ' state-error'; ?>">
                        <label class="label"><?=$this->form->get('email')->getLabel();?></label>
                        <label class="input">
                            <i class="icon-append fa fa-envelope"></i>
                            <?=$this->formEmail($this->form->get('email'));?>
                            <b class="tooltip tooltip-bottom-right">Valid email address</b>
                        </label>
                    </section>
                </div>

                <div class="row">
                    <section class="col col-md-6<?php if ($this->form->get('billingAddressId')->getMessages()) echo ' state-error'; ?>">
                        <label class="label"><?=$this->form->get('billingAddressId')->getLabel();?></label>
                        <label class="select">
                            <?=$this->formSelect($this->form->get('billingAddressId'));?>
                            <i></i>
                        </label>
                    </section>

                    <section class="col col-md-6<?php if ($this->form->get('deliveryAddressId')->getMessages()) echo ' state-error'; ?>">
                        <label class="label"><?=$this->form->get('deliveryAddressId')->getLabel();?></label>
                        <label class="select">
                            <?=$this->formSelect($this->form->get('deliveryAddressId'));?>
                            <i></i>
                        </label>
                    </section>
                </div>

            </fieldset>

            <footer>
                <button type="submit" class="button"><i class="fa fa-check"></i> Save Changes</button>
            </footer>

        </form>
        <!-- /personal settings -->
    </div>

</div>