
<?php $this->headTitle('Add Category') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Category');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-product-category" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
	<i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/shop/category');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
	<i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php $this->form->setAttributes([
	'method' => 'post',
	'id' => 'form-product-category',
	'action' => $this->url('admin/shop/category/edit', [
		'action' => 'add',
	]),
]); ?>

<div id="product-category-edit" class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Add Category');?></h3>
	</div>
	<div class="panel-body">
		<?=$this->form($this->form);?>
	</div>
</div>

<?php $this->inlineScript()
	->appendFile($this->basePath('/js/admin/shop/category-edit.js'));?>

<script>
	$(document).ready(function() {
		$('#list-category-image').remove();
	});
</script>