
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'productCategory',
	'searchInputs'	=> [
		'Category' => 'category',
	],
]);?>

<a href="<?=$this->url('admin/shop/category/edit', [
    'action' => 'add',
]);?>" class="btn btn-default">Add Category</a>
<div class="clearfix">&nbsp;</div>


<div id="table-productCategory">
	<?=$this->partial('shop/product-category/list', [
	    'models' => $this->models
	]); ?>
</div>


<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-productCategory').dataGrid({
	    url : 'category/list',
	    query: { sort : 'lft' },
	    searchForm : $('#search-productCategory'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
