<?php $this->headScript()->appendFile($this->basePath() . '/js/admin/category.js'); ?>
<div class="tab-wrap">
<!-- 
	<ul id="categoryTabs" class="nav nav-tabs">
	    <li><a href="#admin-user">Categories</a></li>
	</ul>
	
	<div id="categoryTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-category">
	    -->
	    	<div class="row-fluid">
		    	<?=$this->partial('layout/search', array(
		    		'name'			=> 'category',
		    		'searchInputs'	=> array(
		    			'Category' => 'category',
		    		),
		    	));?>
	    	</div>
	    	
	    	<div id="table-category" class="row-fluid table-wrap">
		    	<?=$this->partial('shop/product-category/list', array(
		    	    'models' => $this->models
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>
