<div class="tab-wrap">
<!-- 
	<ul id="categoryTabs" class="nav nav-tabs">
	    <li><a href="#admin-user">Categories</a></li>
	</ul>
	
	<div id="categoryTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-category">
	    -->
	    	<div class="row-fluid">
		    	<?=$this->partial('partial/search', array(
		    		'name'			=> 'productCategory',
		    		'searchInputs'	=> array(
		    			'Category' => 'category',
		    		),
		    	));?>
	    	</div>
	    	
	    	<div id="table-productCategory" class="row-fluid table-wrap">
		    	<?=$this->partial('shop/product-category/list', array(
		    	    'models' => $this->models
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-productCategory').dataGrid({
	    url : 'category/list',
	    query: { sort : 'lft' },
	    searchForm : $('#search-productCategory'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->headScript()->captureEnd(); ?>
