<?php $this->headTitle('Product Categories') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->categories) > 0): ?>

<table id="productCategory-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
		    <th data-field="enabled">&nbsp;</th>
			<th data-field="productCategoryId">Product Category Id</th>
			<th data-field="category">Category</th>
			<th data-field="lft">Lft</th>
			<th data-field="rgt">Rgt</th>
			<th data-field="dateCreated">Date Created</th>
			<th data-field="dateModified">Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach($this->categories as $row): ?>
		<tr>
		    <td><?=$this->enabled($row, array(
		    	'table' => 'productCategory',
		        'route' => 'admin/shop/category/edit',
		    )); ?></td>
			<td><?=$this->escapeHtml($row->getProductCategoryId()); ?></td>
			<td><?=$this->escapeHtml($row->getCategory()); ?></td>
			<td><?=$this->escapeHtml($row->getLft()); ?></td>
			<td><?=$this->escapeHtml($row->getRgt()); ?></td>
			<td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
			<td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
			<td>
                <a href="<?=$this->url('admin/shop/category/edit', array(
                    'id' => $row->getProductCategoryId()
				)); ?>" class="btn">Edit</a>
				&nbsp;
				
				<!-- Button to trigger modal -->
                <a href="#categoryModel<?=$row->getProductCategoryId(); ?>" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="categoryModel<?=$row->getProductCategoryId(); ?>">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
				    <h3 id="categoryModel<?=$row->getProductCategoryId(); ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?=$this->url('admin/shop/category/edit', array(
				        'action' => 'delete',
				    )) ?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this category.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="productCategoryId" value="<?=$row->getProductCategoryId() ?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->categories,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/category/page')
); ?>

<?php else: ?>
<h4>No Categories where returned by search.</h4>
<?php endif; ?>
