<?php $this->headTitle('Add User') ?>
<?=$this->ztbFlashMessenger()->render(); ?>

<?=$this->partial('partial/add-edit-form', array(
	'form' 			=> $this->form,
	'formAction' 	=> 'edit',
	'formName'		=> 'User',
    'primaryKey'    => $this->model->getUserId(),
	'postRoute'		=> 'admin/user/edit',
	'cancelRoute'	=> 'admin/user',
	'formElements'	=> array(
		'firstname', 'lastname', 'email', 'passwd',
        'passwd-confirm', 'role', 'userId',
	),
)); ?>
