<?php $this->headScript()->appendFile($this->basePath() . '/js/admin/user.js'); ?>
<div class="tab-wrap">
<!-- 
	<ul id="userTabs" class="nav nav-tabs">
	    <li><a href="#admin-user">Users</a></li>
	</ul>
	
	<div id="userTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-user">
	    -->
	    	<div class="row-fluid">
		    	<form id="search-user" class="form-search" method="post">
		    	    <input type="email" name="email" placeholder="Email:">
		    	    <input type="text" name="user" placeholder="User:">
		    	    <button type="submit" class="btn btn-primary"><i class="icon-search icon-white"></i> Search</button>
		    	    <button type="reset" class="btn">Reset</button>
		    	</form>
	    	</div>
	    	
	    	<div id="table-user" class="row-fluid table-wrap">
		    	<?php echo $this->partial('user/admin/list', array(
		    	    'users' => $this->users
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>