
<div class="tab-wrap">
<!-- 
	<ul id="userTabs" class="nav nav-tabs">
	    <li><a href="#admin-user">Users</a></li>
	</ul>
	
	<div id="userTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-user">
	    -->
	    	<div class="row-fluid">
		    	<?=$this->partial('partial/search', array(
		    		'name'			=> 'user',
		    		'searchInputs'	=> array(
		    			'Email' => 'email',
                        'User'  => 'firstname-lastname',
		    		),
		    	));?>
	    	</div>
	    	
	    	<div id="table-user" class="row-fluid table-wrap">
		    	<?php echo $this->partial('user/admin/list', array(
		    	    'models' => $this->models
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-user').dataGrid({
    	url : 'user/list',
    	query: { sort : 'name' },
    	searchForm : $('#search-user'),
    	paging : 'links',
    	columnSort: true
	});
});
<?php $this->headScript()->captureEnd(); ?>
