<?php $this->headTitle('Users') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->users) > 0): ?>

<table class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="userId">User Id</th>
			<th data-field="name">Name</th>
			<th data-field="email">Email</th>
			<th data-field="role">Role</th>
			<th data-field="dateCreated">Date Created</th>
			<th data-field="dateModified">Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach($this->users as $row): ?>
		
		<tr>
			<td><?php echo $this->escapeHtml($row->getUserId()); ?></td>
			<td><?php echo $this->escapeHtml($row->getLastNameFirst()); ?></td>
			<td><?php echo $this->escapeHtml($row->getEmail()); ?></td>
			<td><?php echo $this->escapeHtml($row->getRole()); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
			<td>
				<a href="<?php echo $this->basepath(
					'/admin/user/edit/id/' . $this->escapeHtml($row->getUserId())
				) ?>" role="button" class="btn">Edit</a>
				&nbsp;
				<?php if ($this->identity()->getUserId() == $row->getUserId()):?>
				<a role="button" class="btn btn-danger disabled" data-toggle="modal">Delete</a>
				<?php else: ?>
				<!-- Button to trigger modal -->
                <a href="#userModel<?php echo $row->getUserId(); ?>" role="button" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="userModel<?php echo $row->getUserId(); ?>" tabindex="-1" role="dialog" aria-labelledby="userModel<?php echo $row->getUserId(); ?>" aria-hidden="true">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				    <h3 id="userModel<?php echo $row->getUserId(); ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?php echo $this->url('admin/user/edit', array(
				        'action' => 'delete',
				    )) ?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this user.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="userId" value="<?php echo $row->getUserId(); ?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
				<?php endif; ?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>


<?php echo $this->paginationControl(
    $this->users,
    'Elastic',
    'paginate',
	array('route' => 'admin/user/page')
); ?>

<?php else: ?>
<h4>No users where returned by search.</h4>
<?php endif; ?>

