<?php $this->headTitle('Users') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->models) > 0): ?>

<table class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="userId">User Id</th>
			<th data-field="name">Name</th>
			<th data-field="email">Email</th>
			<th data-field="role">Role</th>
			<th data-field="dateCreated">Date Created</th>
			<th data-field="dateModified">Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
	   <?php /* @var $row \User\Model\User */ ?>
		<?php foreach($this->models as $row): ?>
		
		<tr>
			<td><?php echo $this->escapeHtml($row->getUserId()); ?></td>
			<td><?php echo $this->escapeHtml($row->getLastNameFirst()); ?></td>
			<td><?php echo $this->escapeHtml($row->getEmail()); ?></td>
			<td><?php echo $this->escapeHtml($row->getRole()); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
			<td>
				<?=$this->partial('partial/edit-actions', array(
                	'pk'		=> 'userId',
                	'id'		=> $row->getUserId(),
		    		'tableName'	=> 'user',
                	'route'		=> 'admin/user/edit',
		    	));?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>


<?php echo $this->paginationControl(
    $this->models,
    'Elastic',
    'paginate',
	array('route' => 'admin/user/page')
); ?>

<?php else: ?>
<h4>No users where returned by search.</h4>
<?php endif; ?>

