<?php
$form = $this->form;
$routeArray = array('action' => $this->formAction);
if (isset($this->userId)) $routeArray['id'] = $this->userId;
?>
<div>
    <form class="form-horizontal"  method="post" action="<?php echo $this->url('admin/user/edit', $routeArray) ?>">
        <fieldset>
        <legend><?php echo ucwords($this->formAction); ?> User Form:</legend>
        <div class="control-group<?php if ($form->get('firstname')->getMessages()) echo ' error'; ?>">
            <label class="control-label" for="title">Forename:</label>
            <div class="controls">
                <?php echo $this->formInput($form->get('firstname')); ?>
                <span class="help-block">
                <?php echo $this->formElementErrors($form->get('firstname'), array(
                    'class' => 'unstyled'
                )); ?>
                </span>
            </div>
        </div>
        
        <div class="control-group<?php if ($form->get('lastname')->getMessages()) echo ' error'; ?>">
            <label class="control-label" for="title">Surname:</label>
            <div class="controls">
                <?php echo $this->formInput($form->get('lastname')); ?>
                <span class="help-block">
                <?php echo $this->formElementErrors($form->get('lastname'), array(
                    'class' => 'unstyled'
                )); ?>
                </span>
            </div>
        </div>
        
        <div class="control-group<?php if ($form->get('email')->getMessages()) echo ' error'; ?>">
            <label class="control-label" for="title">Email:</label>
            <div class="controls">
                <?php echo $this->formEmail($form->get('email')); ?>
                <span class="help-block">
                <?php echo $this->formElementErrors($form->get('email'), array(
                    'class' => 'unstyled'
                )); ?>
                </span>
            </div>
        </div>
        
        <div class="control-group<?php if ($form->get('passwd')->getMessages()) echo ' error'; ?>">
            <label class="control-label" for="title">Password:</label>
            <div class="controls">
                <?php echo $this->formPassword($form->get('passwd')); ?>
                <label class="checkbox inline">
                	<input type="checkbox" id="showPassword"> Show Password
                </label>
                <span class="help-block">
                <?php echo $this->formElementErrors($form->get('passwd'), array(
                    'class' => 'unstyled'
                )); ?>
                </span>
            </div>
        </div>
        
        <div class="control-group<?php if ($form->get('role')->getMessages()) echo ' error'; ?>">
            <label class="control-label" for="title">Role:</label>
            <div class="controls">
                <?php
                if ($this->identity()->userId == $this->userId) {
                    $form->get('role')
                        ->setAttribute('disabled', true);
                }
                ?>
                <?php echo $this->formSelect($form->get('role')); ?>
                <span class="help-block">
                <?php echo $this->formElementErrors($form->get('role'), array(
                    'class' => 'unstyled'
                )); ?>
                </span>
            </div>
        </div>
        
        <?php echo $this->formElement($form->get('userId')); ?>
        <?php echo $this->formElement($form->get('dateCreated')); ?>
       	
        <input type="hidden" name="action" value="<?php echo $this->formAction; ?>">
        
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary" 
                data-loading-text="Please wait...">Submit</button>
                <button type="button" class="btn btn-warning" 
                data-loading-text="Please wait..." onClick="window.location = '<?php echo $this->url('admin/user') ?>';">Cancel</button>
            </div>
        </div>
        </fieldset>
    </form>
</div>

