
<?php
$post = $this->uthandoArticleGetPost('home-page');
$this->headTitle($this->escapehtml($post->getTitle()));
?>

<div id="blog" class="row">

    <!-- BLOG SIDEBAR -->
    <div class="col-md-3 col-sm-3">
        <?=$this->partial('shop/product-nav');?>
    </div>
    <!-- /BLOG SIDEBAR -->


    <div class="col-md-9 col-sm-9">

        <?=$this->partial('shop/catalog/new-products-carousel');?>

        <!-- BLOG ARTICLE -->
        <div class="row">

            <!-- article content -->
            <article>
                <?=$post->getContent();?>
            </article>

            <div class="divider"><!-- divider -->
                <i class="fa fa-angle-double-down"></i>
            </div>

        </div><!-- /BLOG ARTICLE -->

        <!-- PRODUCT CATEGORIES -->
        <div class="row">
            <?php /* @var $row \Shop\Model\ProductCategoryModel */ ?>
            <?php $c=0;?>
            <?php foreach ($this->Category()->getTopCategories() as $row): ?>
                <?php $c++;?>
                <div class="col-sm-4 col-md-4"><!-- category -->
                    <div class="box-content thumbnail text-center">
                        <a href="<?php echo $this->url('shop/catalog', [
                            'categoryIdent' => $row->getIdent()
                        ]); ?>" class="item-image"><!-- image -->
                            <?php if ($row->getShowImage()):?>
                                <img class="img-responsive" src="<?=$this->productCategoryImage($row);?>" alt="<?=$this->escapehtml($row->getCategory());?>">
                            <?php endif;?>
                        </a>
                        <div class="caption text-left"><!-- name -->
                            <h5 class="nomargin elipsis"><?=$this->escapehtml($row->getCategory());?></h5>
                        </div>
                    </div>
                </div><!-- /category -->
                <?php if (($c % 3) === 0):?>
                    <div class="clearfix"></div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

    </div>


</div>
