<?php $this->headTitle('Edit Post Level') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
	'form' 			=> $this->form,
	'formName'		=> 'Post Level',
    'postUrl'		=> $this->url('admin/shop/post/level/edit', [
        'id'    => $this->model->getPostLevelId(),
    ]),
    'cancelUrl'     => $this->url('admin/shop/post/level'),
	'formElements'	=> [
		'postLevel', 'postLevelId',
	],
]); ?>
