
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'postLevel',
	'searchInputs'	=> [
		'Post Level' => 'postLevel',
	],
]);?>
	    	
<div id="table-postLevel">
	<?=$this->partial('shop/post-level/list', [
	    'models' => $this->models
	]); ?>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-postLevel').dataGrid({
	    url : 'level/list',
	    query: { sort : 'postLevel' },
	    searchForm : $('#search-postLevel'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
