
<div class="tab-wrap">
<!-- 
	<ul id="postLevelTabs" class="nav nav-tabs">
	    <li><a href="#admin-postLevel">Post Levels</a></li>
	</ul>
	
	<div id="postLevelTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-postLevel">
	    -->
	    	<div class="row-fluid">
		    	<?=$this->partial('partial/search', array(
		    		'name'			=> 'postLevel',
		    		'searchInputs'	=> array(
		    			'Post Level' => 'postLevel',
		    		),
		    	));?>
	    	</div>
	    	
	    	<div id="table-postLevel" class="row-fluid table-wrap">
		    	<?=$this->partial('shop/post-level/list', array(
		    	    'models' => $this->models
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-postLevel').dataGrid({
	    url : 'level/list',
	    query: { sort : 'postLevel' },
	    searchForm : $('#search-postLevel'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->headScript()->captureEnd(); ?>
