<?php
$form = $this->form;
$routeArray = array('action' => $this->formAction);
if (isset($this->postLevelId)) $routeArray['id'] = $this->postLevelId;
?>
<div>
	<form class="form form-horizontal" method="post" action="<?=$this->url('admin/shop/post/level/edit', $routeArray) ?>">
		<fieldset>
			<legend><?=ucwords($this->formAction); ?> Post Level Form:</legend>
			<?=$this->ztbFormElement($form->get('postLevel'));?>
			
			<?=$this->ztbFormElement($form->get('postLevelId'));?>
			<input type="hidden" name="action" value="<?=$this->formAction;?>">
			
			<div class="control-group">
            	<div class="controls">
                	<button type="submit" class="btn btn-primary" data-loading-text="Please wait...">
                		Submit
                	</button>
                	<button type="button" class="btn btn-warning"  data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('admin/shop/post/level') ?>';">
                		Cancel
                	</button>
            	</div>
        	</div>
		</fieldset>
	</form>
</div>

