<?php $this->headTitle('Post Levels') ?>

<?php if (count($this->models) > 0): ?>
<div class="table-responsive">
    <table id="postLevel-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="postLevelId">Post Level Id</th>
    			<th data-field="postLevel">Post Level</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    		<?php /* @var $row \Shop\Model\Post\PostLevelModel */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getPostLevelId()); ?></td>
    			<td><?=$this->escapeHtml($row->getPostLevel()); ?></td>
    			<td>
                   <?=$this->partial('admin/partial/edit-actions', [
                    	'pk'		=> 'postLevelId',
                    	'id'		=> $row->getPostLevelId(),
    		    		'tableName'	=> 'postLevel',
                    	'route'		=> 'admin/shop/post/level/edit',
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>
<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
    ['route' => 'admin/shop/post/level/page']
); ?>

<?php else: ?>
<h4>No Post Levels where returned by search.</h4>
<?php endif; ?>
