<?php $this->headTitle('Post Levels') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->models) > 0): ?>

<table id="postLevel-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="postLevelId">Post Level Id</th>
			<th data-field="postLevel">Post Level</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php /* @var $row \Shop\Model\Post\Level */ ?>
		<?php foreach($this->models as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getPostLevelId()); ?></td>
			<td><?=$this->escapeHtml($row->getPostLevel()); ?></td>
			<td>
               <?=$this->partial('partial/edit-actions', array(
                	'pk'		=> 'postLevelId',
                	'id'		=> $row->getPostLevelId(),
		    		'tableName'	=> 'postLevel',
                	'route'		=> 'admin/shop/post/level/edit',
		    	));?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/post/level/page')
); ?>

<?php else: ?>
<h4>No Post Levels where returned by search.</h4>
<?php endif; ?>
