
<h4>Recent <strong>Tweets</strong></h4>
<?php if (!isset($this->tweets['errors'])):?>
<ul class="list-unstyled fsize13">
    <?php /* @var $tweet \UthandoTwitter\Model\Tweet */ ?>
    <?php foreach($this->tweets as $tweet): ?>
    <li>
        <i class="fa fa-twitter"></i>&nbsp;
        <a href="https://twitter.com/intent/user?user_id=<?=$tweet->getUserId(); ?>">
            @<?=$tweet->getScreenName(); ?>
        </a>&nbsp;
        <?=$tweet->getText($this->tweets->getShowTweetLinks()); ?>&nbsp;
        <small class="ago"><?=$tweet->getRelativeTime(); ?></small>
    </li>
    <?php endforeach; ?>
</ul>
<?php else: ?>
<dl>
    <?php foreach($this->tweets['errors'] as $error):?>
    <dt> <?=$error->code;?></dt>  <dd>  <?=$error->message;?></dd>
    <?php endforeach; ?>
</dl>
<?php endif; ?>