
<?php if (null === $this->error):?>
    <pre><?=$this->escapeHtml(Zend\Json\Json::prettyPrint($this->payment->toJson(), array("indent" => "  ")));?></pre>
<?php else: ?>
<table class="table table-bordered table-pre-wrap">
    <tr>
        <th>Code</th>
        <td><?=$this->escapeHtml($this->code);?></td>
    </tr>
    <tr>
        <th>Data</th>
        <td><pre><?=$this->escapeHtml(Zend\Json\Json::prettyPrint($this->data, array("indent" => "  ")));?></pre></td>
    </tr>
    <tr>
        <th>Message</th>
        <td><?=$this->escapeHtml($this->error);?></td>
    </tr>
</table>
<?php endif;?>
