<?php $this->headTitle('Edit Tax Code') ?>
<?=$this->ztbFlashMessenger()->render(); ?>

<?=$this->partial('partial/add-edit-form', array(
	'form' 			=> $this->form,
	'formAction' 	=> 'edit',
	'primaryKey'	=> $this->model->getTaxCodeId(),
	'formName'		=> 'Tax Code',
	'postRoute'		=> 'admin/shop/tax/code/edit',
	'cancelRoute'	=> 'admin/shop/tax/code',
	'formElements'	=> array(
		'taxCode', 'description', 'taxRateId', 'taxCodeId',
	),
)); ?>
