<?php $this->headTitle('Edit Tax Code') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
	'form' 			=> $this->form,
	'formName'		=> 'Tax Code',
    'postUrl'		=> $this->url('admin/shop/tax/code/edit', [
        'id'    => $this->model->getTaxCodeId(),
    ]),
    'cancelUrl'     => $this->url('admin/shop/tax/code'),
	'formElements'	=> [
		'taxCode', 'description', 'taxRateId', 'taxCodeId',
	],
]); ?>
