  	
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'taxCode',
	'searchInputs'	=> [
		'Tax Code' => 'taxCode-description',
	],
]);?>

	    	
<div id="table-taxCode">
	<?=$this->partial('shop/tax-code/list', [
	    'models' => $this->models
	]); ?>
</div>


<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-taxCode').dataGrid({
	    url : 'code/list',
	    query: { sort : 'taxCodeId' },
	    searchForm : $('#search-taxCode'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.dataTable.rowClick
	});
});
<?php $this->inlineScript()->captureEnd(); ?>


