<?php $this->headTitle('Tax Codes') ?>

<?php if (count($this->models) > 0): ?>
<div class="table-responsive">
    <table id="taxCode-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="taxCodeId">Tax Code Id</th>
    			<th data-field="taxRate">Tax Rate</th>
    			<th data-field="taxCode">Tax Code</th>
    			<th data-field="description">Description</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    		<?php /* @var $row \Shop\Model\Tax\TaxCodeModel */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getTaxCodeId()); ?></td>
    			<td><?=$this->escapeHtml($this->percentFormat($row->getTaxRate()->getTaxRate(true))); ?></td>
    			<td><?=$this->escapeHtml($row->getTaxCode()); ?></td>
    			<td><?=$this->escapeHtml($row->getDescription()); ?></td>
    			<td>
                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                    	'pk'		=> 'taxCodeId',
                    	'id'		=> $row->getTaxCodeId(),
    		    		'tableName'	=> 'taxCode',
                    	'route'		=> 'admin/shop/tax/code/edit',
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>
<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/shop/tax/code/page']
); ?>

<?php else: ?>
<h4>No Tax Codes where returned by search.</h4>
<?php endif; ?>
