<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Navigation\Module'                    => __DIR__ . '/Module.php',
  'Navigation\Controller\MenuController' => __DIR__ . '/src/Navigation/Controller/MenuController.php',
  'Navigation\Controller\PageController' => __DIR__ . '/src/Navigation/Controller/PageController.php',
  'Navigation\Form\Menu'                 => __DIR__ . '/src/Navigation/Form/Menu.php',
  'Navigation\Form\Page'                 => __DIR__ . '/src/Navigation/Form/Page.php',
  'Navigation\Hydrator\Menu'             => __DIR__ . '/src/Navigation/Hydrator/Menu.php',
  'Navigation\Hydrator\Page'             => __DIR__ . '/src/Navigation/Hydrator/Page.php',
  'Navigation\InputFilter\Menu'          => __DIR__ . '/src/Navigation/InputFilter/Menu.php',
  'Navigation\InputFilter\Page'          => __DIR__ . '/src/Navigation/InputFilter/Page.php',
  'Navigation\Mapper\Menu'               => __DIR__ . '/src/Navigation/Mapper/Menu.php',
  'Navigation\Mapper\Page'               => __DIR__ . '/src/Navigation/Mapper/Page.php',
  'Navigation\Model\Menu'                => __DIR__ . '/src/Navigation/Model/Menu.php',
  'Navigation\Model\Page'                => __DIR__ . '/src/Navigation/Model/Page.php',
  'Navigation\Service\Form\PageFactory'  => __DIR__ . '/src/Navigation/Service/Form/PageFactory.php',
  'Navigation\Service\Menu'              => __DIR__ . '/src/Navigation/Service/Menu.php',
  'Navigation\Service\Page'              => __DIR__ . '/src/Navigation/Service/Page.php',
  'Navigation\View\AclMenu'              => __DIR__ . '/src/Navigation/View/AclMenu.php',
  'Navigation\View\NavigationForm'       => __DIR__ . '/src/Navigation/View/NavigationForm.php',
);
