<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Article\Module'                       => __DIR__ . '/Module.php',
  'Article\Controller\ArticleController' => __DIR__ . '/src/Article/Controller/ArticleController.php',
  'Article\Form\Article'                 => __DIR__ . '/src/Article/Form/Article.php',
  'Article\Hydrator\Article'             => __DIR__ . '/src/Article/Hydrator/Article.php',
  'Article\InputFilter\Article'          => __DIR__ . '/src/Article/InputFilter/Article.php',
  'Article\Mapper\Article'               => __DIR__ . '/src/Article/Mapper/Article.php',
  'Article\Model\Article'                => __DIR__ . '/src/Article/Model/Article.php',
  'Article\Service\Article'              => __DIR__ . '/src/Article/Service/Article.php',
);
