<?php $this->headTitle('Edit Group Price') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
	'form' 			=> $this->form,
	'formAction' 	=> 'edit',
    'primaryKey'	=> $this->model->getProductGroupId(),
	'formName'		=> 'Group Price',
	'postRoute'		=> 'admin/shop/group-price/edit',
	'cancelRoute'	=> 'admin/shop/group-price',
	'formElements'	=> [
		'productGroupId', 'group', 'price',
	],
]); ?>
