
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'productGroupPrice',
	'searchInputs'	=> [
		'Group'		=> 'group',
	],
]);?>

	    	
<div id="table-productGroupPrice">
	<?=$this->partial('shop/product-group-price/list', [
	    'models' => $this->models
	]); ?>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-productGroupPrice').dataGrid({
	    url : 'group-price/list',
	    query: { sort : 'productGroupId' },
	    searchForm : $('#search-productGroupPrice'),
	    paging : 'links',
	    columnSort: true
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
