
<?php 
$pages = $this->container->findBy('label', 'Products');
$iterator = new RecursiveIteratorIterator($pages,
    RecursiveIteratorIterator::SELF_FIRST); 
    
$minDepth = 0;
?>
    
<ul class="dropdown-menu">

<?php foreach ($iterator as $page):?>
    <?php $currDepth = $iterator->getDepth();?>
    <?php if ($currDepth > $minDepth || !$this->uthandoNavigation()->accept($page)) continue; ?>
    <li>
        <a href="<?=$page->getHref();?>">
            <?=$page->getLabel();?>
        </a>
    </li>
<?php endforeach;?>
    
    <li class="divider"></li>
    <li><a href="#" id="get-product-list-link" data-toggle="modal" data-target="#product-list-model">
        Export Product List
    </a></li>
</ul>

<div id="product-list-model" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Export Product List</h4>
            </div>
            <div class="modal-body">
                <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button id="get-product-list" type="button" class="btn btn-primary">Download List</button>
            </div>
        </div>
    </div>
</div>

<script>

    $('#product-list-model').on('show.bs.modal', function () {
        $(this).find('.modal-body').load('<?=$this->url('admin/shop/report', [
            'action'    => 'index',
        ]);?>');
    });

    $('#product-list-model').on('hide.bs.modal', function () {
        $(this).find('.modal-body').html('<i class="fa fa-spinner fa-spin"></i>&nbsp;Loading');
        $(this).find('.modal-content').loadingOverlay('remove');
    });

    var errorCount = 0;

    $('#get-product-list').on('click', function () {
        var url = '<?=$this->url('admin/shop/report', [
            'action'    => 'product-list',
        ]);?>';
        
        var el = $(this).parent().parent().parent().parent();
        var cat = el.find('select').val();

        $.ajax({
           url: url,
           data:  $('#product-report').serialize(),
           type: 'POST',
           beforeSend: function() {
               el.find('.modal-content').loadingOverlay({
            	   loadingText: 'Please wait while I prepare your report'
               });
           },
           success: function (response) {
               el.modal('hide');
               if (response.status == 'success') {
                   message = '<h5>Please click on link below to download your report</h5>'
                   + '<a href="' + response.url + '" target="_blank">' + response.report + '</a>';
               } else {
                   message = '<h5 class="text-danger">Error!</h5><span class="text-danger">' + response.message + '</span>';
               }

               bootbox.dialog({
            	   title: "Product List Download",
            	   message: message,
            	   buttons: {
                       main: {
                           label: "Close",
                           className: "btn-default"
                       }
                   }
        	   });
           },
           error: function (response) {
               if (errorCount < 3) {
            	   admin.addAlert('An error occured, trying again', 'info');
            	   $('#get-product-list').trigger('click');
            	   errorCount++;
               } else {
            	   admin.addAlert(response.error, 'danger');
            	   el.modal('hide');
            	   errorCount = 0;
               }
           }
        });
    });

</script>
