<?php
$form = $this->form;
$routeArray = ['action' => $this->formAction];
if (isset($this->advertId)) $routeArray['id'] = $this->advertId;
?>
<div class="row">
	<form class="form-horizontal col-md-12" method="post" action="<?=$this->url('admin/shop/advert/edit', $routeArray) ?>">
		<fieldset>
			<legend><?=ucwords($this->formAction); ?> Advert Form:</legend>
			
			<div class="row">
                <div class="col-md-6">
    			    <div class="col-md-offset-4 col-md-12">
    			        <label>
    			            <?=$this->FormCheckbox($form->get('enabled'));?>
    			        </label>
    			    </div>
    			    
    			    <div class="form-group<?php if ($form->get('advert')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="category"><?=$form->get('advert')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formText($form->get('advert')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                                <?=$this->formElementErrors($form->get('advert'), [
                                    'class' => 'list-unstyled'
                                ]); ?>
                            </span>
                        </div>
                    </div>
                </div>
		    </div>
		    
		    <?=$this->formHidden($form->get('advertId'));?>
			<input type="hidden" name="action" value="<?=$this->formAction;?>">
			<div class="row">
    			<div class="form-group">
                    <div class="col-md-offset-2 col-md-12">
                        <button type="submit" class="btn btn-primary" data-loading-text="Please wait...">
                        	Submit
                        </button>
                        <button type="button" class="btn btn-warning"  data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('admin/shop/category') ?>';">
                        	Cancel
                        </button>
                    </div>
                </div>
            </div>
		</fieldset>
	</form>
</div>