<?php $this->headTitle('Edit Advert') ?>
<?php $this->layout()->pageTitle = $this->translate('Edit Advert'); ?>

<?php $this->placeholder('header-buttons')->captureStart(); ?>
    <button type="submit" form="form-advert" data-toggle="tooltip" title="<?= $this->translate('Save'); ?>"
            class="btn btn-primary">
        <i class="fa fa-save"></i>
    </button>
    <a href="<?= $this->url('admin/shop/advert'); ?>" data-toggle="tooltip" title="<?= $this->translate('Cancel'); ?>"
       class="btn btn-default">
        <i class="fa fa-reply"></i>
    </a>
<?php $this->placeholder('header-buttons')->captureEnd(); ?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-advert',
    'action' => $this->url('admin/shop/advert/edit', [
        'action'    => 'edit',
        'id'        => $this->model->getAdvertId(),
    ]),
]); ?>

    <div id="advert-edit" class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><i class="fa fa-pencil"></i> <?= $this->translate('Edit Advert'); ?></h3>
        </div>
        <div class="panel-body">
            <?= $this->form($this->form); ?>
        </div>
    </div>
