<?php $this->headTitle('Adverts') ?>
<?php $this->layout()->pageTitle = $this->translate('Adverts');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<a href="<?=$this->url('admin/shop/advert/edit', [
    'action' => 'add'
]);?>" data-toggle="tooltip" title="<?=$this->translate('Add Tax Code');?>" class="btn btn-primary" id="advert-add">
    <i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('List Adverts');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('admin/partial/search', [
            'name'			=> 'advert',
            'searchInputs'	=> [
                'Advert'	=> 'advert',
            ],
            'params' 		=> $this->params,
        ]);?>
    </div>
    <div id="table-advert" class="admin-table">
        <?=$this->partial('shop/advert/list', [
            'models' => $this->models,
        ]); ?>
    </div>
</div>

<?php $this->placeholder('js-scripts')->captureStart();?>
<script>
    $('#table-advert').dataGrid({
        url: 'advert/list',
        query: {sort: 'advertId'},
        searchForm: $('#search-advert'),
        columnSort: true
    });
</script>
<?php $this->placeholder('js-scripts')->captureEnd();?>
