

<style>
#footer {
	margin-top: 5px;
	margin-bottom: 5px;
	text-align: center;
	font-size: 12px;
	color: #999;
}

.advert-container {
	box-sizing: border-box;
	width: 100%;
	height: 270px;
	padding: 20px 15px 15px 15px;
	border: 1px solid #ddd;
	background: #fff;
	background: linear-gradient(#f6f6f6 0, #fff 50px);
	background: -o-linear-gradient(#f6f6f6 0, #fff 50px);
	background: -ms-linear-gradient(#f6f6f6 0, #fff 50px);
	background: -moz-linear-gradient(#f6f6f6 0, #fff 50px);
	background: -webkit-linear-gradient(#f6f6f6 0, #fff 50px);
	box-shadow: 0 3px 10px rgba(0,0,0,0.15);
	-o-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
	-ms-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
	-moz-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
	-webkit-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
}

.advert-placeholder {
	width: 100%;
	height: 100%;
	font-size: 10px;
	line-height: 1em;
}
</style>

<script src="<?=$this->themePath('/assets/js/flot/jquery.flot.js');?>"></script>
<script src="<?=$this->themePath('/assets/js/flot/jquery.flot.categories.js');?>"></script>

<div class="advert-container">
	<div id="placeholder" class="advert-placeholder"></div>
</div>

<div id="footer"></div>

<script type="text/javascript">

	$(function() {

		var data = <?=$this->stats;?>;

		$.plot("#placeholder", [ data ], {
			series: {
				bars: {
					show: true,
					barWidth: 0.6,
					align: "center"
				}
			},
			xaxis: {
				mode: "categories",
				tickLength: 0
			}
		});

		// Add the Flot version string to the footer

		$("#footer").prepend("Flot " + $.plot.version);
	});

</script>