
<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('shop/parallax', [
    'title' => 'View Cart',
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>
<div id="cart-content">
    <a href="<?=$this->url('shop');?>" class="btn btn-primary">Continue Shopping</a>

    <form class="cartContent margin-top20 clearfix" method="post" action="<?=$this->url('shop/cart', [
        'action' => 'update'
    ]);?>">

        <?=$this->partial('shop/cart', [
            'checkout' => false,
            'countryId' => $this->countryId
        ]); ?>
    </form>

    <div class="row margin-top60">

        <div class="col-md-7 col-sm-7">

            <!-- shipping -->
            <form method="post" class="sky-form boxed cartContent">
                <header class="styleColor">Calculate Shipping</header>

                <fieldset>
                    <section>
                        <label class="select">
                            <?=$this->formSelect($this->countrySelect($this->countryId)->setAttribute('class', 'pointer'));?>
                            <i></i>
                        </label>
                        <i></i>
                    </section>

                </fieldset>
                <footer>
                    <button type="submit" class="btn btn-default pull-right">UPDATE TOTALS</button>
                </footer>
            </form>
            <!-- /shipping -->

            <!-- promotional code -->
            <div id="voucher-code">
                <?=$this->partial('shop/voucher-codes/add-voucher', [
                    'url' => $this->url('shop/cart'),
                ]);?>
            </div>
            <!-- /promotional code -->
        </div>

        <div class="col-md-5 col-sm-5">

            <!-- cart totals -->
            <div class="sky-form boxed cartContent">
                <header class="styleColor">Cart Totals</header>

                <fieldset>

                    <section class="clearfix cart_totals">
                        <span class="pull-right fsize16"><?=$this->cart()->getSubTotal();?></span>
                        <span class="bold">Cart Subtotal</span>
                    </section>

                    <section class="clearfix cart_totals">
                        <span class="pull-right fsize16"><?=$this->cart()->getShippingTotal($this->countryId);?></span>
                        <span class="bold">Shipping</span>
                    </section>

                    <?php if ($this->shopOption('vatState')): ?>
                    <section class="clearfix cart_totals">
                        <span class="pull-right fsize16"><?=$this->cart()->getTaxTotal();?></span>
                        <span class="bold">VAT</span>
                    </section>
                    <?php endif;?>

                    <section class="clearfix cart_totals">
                        <span class="pull-right fsize16"><?=$this->cart()->getDiscount();?></span>
                        <span class="bold">
                            Coupon Discount
                        </span>
                    </section>

                    <section class="clearfix cart_totals noborder">
                        <span class="pull-right fsize20 bold styleColor"><?=$this->cart()->getTotal();?></span>
                        <span class="bold fsize18">ORDER TOTAL</span>
                    </section>

                    <p class="fsize12">
                        Please note that shipping will be calculated on total order
                        <?=($this->cartOption('shippingByWeight')) ? 'weight' : 'value'; ?>
                        and destination, and will be applied when shipping information is finalised.
                    </p>

                </fieldset>

                <footer>
                    <a href="<?=$this->url('shop/checkout');?>" class="btn btn-primary pull-right">PROCEED TO CHECKOUT &rarr;</a>
                </footer>
            </div>
            <!-- /cart totals -->

        </div>
    </div>

</div>