
<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('layout/page-title', [
    'pageTitle' => 'Change Password'
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<div class="row">
    <!-- password form -->
	<form action="<?=$this->url('user', [
	    'action' => 'forgot-password',
	]);?>" method="post" class="sky-form boxed col-md-6 col-md-offset-3">
		<header>Password Forgot</header>
		
		<fieldset>					
			<section>
				<div class="row<?php if ($this->form->get('email')->getMessages()) echo ' has-error'; ?>">
					<label class="label col col-md-4">E-mail</label>
					<div class="col col-md-8">
						<label class="input">
							<i class="icon-append fa fa-user"></i>
							<?=$this->formEmail($this->form->get('email'));?>
						</label>
						<div class="note">Please type your account email.</div>
						<span class="help-block">
                            <?=$this->formElementErrors($this->form->get('email'), [
                                'class' => 'list-unstyled note note-error'
                            ]); ?>
                        </span>
					</div>
				</div>
				
				<div class="row">
                    <div class="form-group">
                        <div class="col-md-12<?php if ($this->form->get('captcha')->getMessages()) echo ' has-error'; ?>">
                            <label>Please verify you are human *</label>
                            <?=$this->formCaptcha($this->form->get('captcha')->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                                <?=$this->formElementErrors($this->form->get('captcha'), [
                                    'class' => 'list-unstyled note note-error'
                                ]); ?>
                            </span>
                        </div>
                    </div>
                </div>
			</section>

		</fieldset>
		<footer>
		    <?=$this->formhidden($this->form->get('security'));?>
			<button type="submit" class="button">Reset Password</button>
		</footer>
	</form>
	<!-- /password form -->
</div>