
<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('layout/page-title', [
    'pageTitle' => 'Change Password'
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<?php \FB::info(get_class($this->form));?>

<div class="row">

    <div class="col-md-4">
        <?=$this->uthandoNavigation()
            ->uthandoTbDbMenu('user-menu')
            ->setUlClass('side-nav list-group')
            ->setAddClassToListItem();?>
    </div>

    <div class="col-md-8">
        <!-- password -->
        <form action="<?php echo $this->url('user', [
            'action' => 'password'
        ]); ?>" method="post" class="sky-form boxed">
            <header>Change Password</header>

            <fieldset>

                <section>
                    <label class="label">New Password</label>
                    <label class="input<?php if ($this->form->get('passwd')->getMessages()) echo ' state-error'; ?>">
                        <i class="icon-append fa fa-lock"></i>
                        <?=$this->formPassword($this->form->get('passwd')); ?>
                        <b class="tooltip tooltip-bottom-right">Type a new password (min.3 chr.)</b>
                        <span class="help-block">
                            <?=$this->formElementErrors($this->form->get('passwd'), [
                                'class' => 'list-unstyled note note-error'
                            ]); ?>
                        </span>
                    </label>
                </section>

                <section>
                    <label class="label">Confirm New Password</label>
                    <label class="input<?php if ($this->form->get('passwd-confirm')->getMessages()) echo ' state-error'; ?>">
                        <i class="icon-append fa fa-lock"></i>
                        <?=$this->formPassword($this->form->get('passwd-confirm')); ?>
                        <b class="tooltip tooltip-bottom-right">Type the new password again</b>
                        <span class="help-block">
                            <?=$this->formElementErrors($this->form->get('passwd-confirm'), [
                                'class' => 'list-unstyled note note-error'
                            ]); ?>
                        </span>
                    </label>
                </section>
            </fieldset>

            <footer>
                <button type="submit" class="button"><i class="fa fa-check"></i> Change Password</button>
            </footer>
            <?=$this->formElement($this->form->get('security')); ?>
            <input type="hidden" name="action" value="password">
        </form>
        <!-- /password -->
    </div>
</div>