<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Admin\Controller\IndexController'             => __DIR__ . '/src/Admin/Controller/IndexController.php',
    'Admin\View\PhpInfo'                           => __DIR__ . '/src/Admin/View/PhpInfo.php',
    'Admin\View\FormElement'                       => __DIR__ . '/src/Admin/View/FormElement.php',
    'Admin\View\DatePicker'                        => __DIR__ . '/src/Admin/View/DatePicker.php',
    'Admin\View\TextEditor'                        => __DIR__ . '/src/Admin/View/TextEditor.php',
    'Admin\Service\AdminNavigationFactory'         => __DIR__ . '/src/Admin/Service/AdminNavigationFactory.php',
    'Admin\Service\AdminUserNavigationFactory'     => __DIR__ . '/src/Admin/Service/AdminUserNavigationFactory.php',
    'Admin\AdminException'                         => __DIR__ . '/src/Admin/AdminException.php',
    'Admin\Module'                                 => __DIR__ . '/Module.php',
);
