<?php $this->headTitle('Sessions') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->sessions) > 0): ?>

<table class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="id">User Id</th>
			<th data-field="name">Name</th>
			<th data-field="modified">Modified</th>
			<th data-field="lifetime">Expires</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach($this->sessions as $row): ?>
		
		<tr>
			<td><?php echo $this->escapeHtml($row->getId()); ?></td>
			<td><?php echo $this->escapeHtml($row->getName()); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate('@'.$row->getModified())); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate('@'.($row->getModified() + $row->getLifetime()))); ?></td>
			<td>
				<a data-toggle="modal" class="btn" href="<?php echo $this->url('admin/session/view', array(
					'id' => $row->getId()
				)); ?>" data-target="#viewSession<?php echo $row->getId(); ?>">View Data</a>
				<!-- Modal -->
				<div id="viewSession<?php echo $row->getId(); ?>" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="viewSession<?php echo $row->getId(); ?>" aria-hidden="true">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="myModalLabel">Session Data</h3>
					</div>
					<div class="modal-body">
						<p>Loading…</p>
					</div>
					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
					</div>
				</div>
				&nbsp;
				<!-- Button to trigger modal -->
                <a href="#sessionModel<?php echo $row->getId(); ?>" role="button" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="sessionModel<?php echo $row->getId(); ?>" tabindex="-1" role="dialog" aria-labelledby="sessionModel<?php echo $row->getId(); ?>" aria-hidden="true">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				    <h3 id="sessionModel<?php echo $row->getId(); ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?php echo $this->url('admin/session/delete') ?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this user.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="id" value="<?php echo $row->getId() ?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>


<?php echo $this->paginationControl(
    $this->sessions,
    'Elastic',
    'paginate',
	array('route' => 'admin/session/page')
); ?>

<?php else: ?>
<h4>No sessions where returned by search.</h4>
<?php endif; ?>


