
<div id="alerts" class="col-md-12">
    <?=$this->tbFlashMessenger()->render(); ?>
</div>

<div class="col-md-12">
    <?=$this->partial('uthando-admin/partial/add-edit-form', array(
        'form' 			=> $this->form,
        'formAction' 	=> 'edit',
        'formName'		=> 'Product Image',
        'formElements'	=> array(
            'productImageId', 'productId', 'thumbnail',
            'full', 'isDefault',
        ),
        'helperOptions' => [
            'labelWidth'    => '4',
            'elementWidth'  => '8',
        ],
    )); ?>
</div>
