
<div class="tab-wrap">
<!-- 
	<ul id="imageTabs" class="nav nav-tabs">
	    <li><a href="#admin-image">Images</a></li>
	</ul>
	
	<div id="imageTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-image">
	    -->
	    	<div class="row-fluid">
		    	<?=$this->partial('partial/search', array(
		    		'name'			=> 'productImage',
		    		'searchInputs'	=> array(
		    			'Image'		=> 'full-thumbnail',
						'Product'	=> 'name',
		    		),
		    	));?>
	    	</div>
	    	
	    	<div id="table-productImage" class="row-fluid table-wrap">
		    	<?=$this->partial('shop/product-image/list', array(
		    	    'models' => $this->models
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-productImage').dataGrid({
	    url : 'image/list',
	    query: { sort : 'productImageId' },
	    searchForm : $('#search-productImage'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->headScript()->captureEnd(); ?>
