
<?=$this->partial('admin/partial/search', [
	'name'			=> 'productImage',
	'searchInputs'	=> [
		'Image'		=> 'full-thumbnail',
		'Product'	=> 'name',
	],
]);?>
	    	
<div id="table-productImage">
	<?=$this->partial('shop/product-image/list', [
	    'models' => $this->models
	]); ?>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-productImage').dataGrid({
	    url : 'image/list',
	    query: { sort : 'productImageId' },
	    searchForm : $('#search-productImage'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
