
<?php if (count($this->models) > 0): ?>
<div class="panel panel-default">
    <table id="productImage-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th>Id</th>
    			<th>Image</th>
    			<th>Default</th>
    			<th>Date Created</th>
    			<th>Date Modified</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    	<?php /* @var $row \Shop\Model\ProductImageModel */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getProductImageId()); ?></td>
    			<td><?=$this->escapeHtml($row->getFull()); ?></td>
    			<td><?=$this->escapeHtml($row->isDefaultImage()); ?></td>
    			<td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
    			<td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
    			<td>
                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                    	'pk'		=> 'productImageId',
                    	'id'		=> $row->getProductImageId(),
    		    		'tableName'	=> 'productImage',
                    	'route'		=> 'admin/shop/product/image',
                        'routeParams'   => [
                            'action'    => 'edit'
                        ],
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>

<?php else: ?>
<h4>No Images have been uploaded yet.</h4>
<?php endif; ?>
