<?php $this->headTitle('Product Images') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->images) > 0): ?>

<table id="productCategory-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="productImageId">Product Image Id</th>
			<th data-field="name">Product</th>
			<th data-field="full">Image</th>
			<th data-field="isDefault">Default</th>
			<th data-field="dateCreated">Date Created</th>
			<th data-field="dateModified">Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach($this->images as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getProductImageId()); ?></td>
			<td><?=$this->escapeHtml($row->getName()); ?></td>
			<td><?=$this->escapeHtml($row->getFull()); ?></td>
			<td><?=$this->escapeHtml($row->getIsDefault()); ?></td>
			<td><?=$this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
			<td><?=$this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
			<td>
                <a href="<?=$this->url('admin/shop/image/edit', array(
                    'id' => $row->getProductImageId()
				)); ?>" role="button" class="btn">Edit</a>
				&nbsp;
				
				<!-- Button to trigger modal -->
                <a href="#imageModel<?=$row->getProductImageId(); ?>" role="button" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="imageModel<?=$row->getProductImageId(); ?>">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
				    <h3 id="imageModel<?=$row->getProductImageId(); ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?=$this->url('admin/shop/image', array(
				        'action' => 'delete',
				    )) ?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this image.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="productImageId" value="<?=$row->getProductImageId(); ?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->images,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/image/page')
); ?>

<?php else: ?>
<h4>No Images where returned by search.</h4>
<?php endif; ?>
