
<?php
$form = $this->formManager(\Shop\Form\Voucher\Voucher::class);
$defaultValue = $this->cart()->getVoucherCode();
$form->get('code')->setValue($defaultValue);
?>

<!-- promotional code -->
<form action="<?=$this->url;?>" method="post" id="voucher-code-form" class="sky-form boxed
cartContent">
    <header class="styleColor">Have A Promotional Code?</header>

    <fieldset>
        <section>
            <label class="input">
                <input type="text" placeholder="Coupon Code" name="code" value="<?=$form->get('code')->getValue();?>" />
                <span class="help-block">
                    <?=$this->formElementErrors($form->get('code'), [
                        'class' => 'list-unstyled text-danger'
                    ]); ?>
                </span>
            </label>
        </section>

    </fieldset>
    <footer>
        <button type="submit" class="btn btn-default pull-right">APPLY</button>
    </footer>
</form>
<!-- /promotional code -->