<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'user/admin/add'       => __DIR__ . '/view/user/admin/add.phtml',
    'user/admin/delete'    => __DIR__ . '/view/user/admin/delete.phtml',
    'user/admin/edit'      => __DIR__ . '/view/user/admin/edit.phtml',
    'user/admin/index'     => __DIR__ . '/view/user/admin/index.phtml',
    'user/admin/list'      => __DIR__ . '/view/user/admin/list.phtml',
    'user/admin/user-form' => __DIR__ . '/view/user/admin/user-form.phtml',
    'user/auth/login'      => __DIR__ . '/view/user/auth/login.phtml',
    'user/user/edit'       => __DIR__ . '/view/user/user/edit.phtml',
    'user/user/index'      => __DIR__ . '/view/user/user/index.phtml',
    'user/user/register'   => __DIR__ . '/view/user/user/register.phtml',
    'user/user/thank-you'  => __DIR__ . '/view/user/user/thank-you.phtml',
    'user/user/user-form'  => __DIR__ . '/view/user/user/user-form.phtml',
);
