<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('layout/page-title', [
    'pageTitle' => 'Events'
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<?php
/* @var \UthandoEvents\Options\EventsOptions $options */
$options = $this->options;
?>

<div class="row">
    <div class="col-md-3 col-sm-3">
        <?=$this->partial('shop/product-nav');?>
    </div>

    <div class="col-md-9 col-sm-9">
        <!-- Timeline -->
        <div class="timeline clearfix">
            <div class="timeline-centered clearfix">

                <?php $c=0;?>
                <?php /* @var \UthandoEvents\Model\EventModel $event */ ?>
                <?php foreach ($this->events as $event): ?>
                    <?php $c++;?>
                    <?php $leftRight = (($c % 2) === 0) ? 'right' : 'left'; ?>
                <div class="item pull-<?=$leftRight;?> col-md-6 col-sm-6"><!-- item -->
                    <h3 class="timeline-centered-title"><a href="#"><?=$this->escapeHtml($event->getTitle());?></a></h3>
                    <h4><b><?=$this->formatDate($event->getDateTime(), $options->getDateFormat());?></b></h4>
                    <p><?=nl2br($this->escapeHtml($event->getDescription()));?></p>
                    <?php if ($event->getHtml()): ?>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <?=$event->getHtml();?>
                        </div>
                    </div>
                    <?php endif; ?>
                </div><!-- /item -->
                <?php endforeach; ?>

            </div>
        </div>
        <!-- /Timeline -->

        <!--
        <div class="text-center"><!-- load more -->
            <!--<a href="#" class="btn btn-default">LOAD MORE</a>
        </div>-->
    </div>
</div>