<?php $this->headtitle($this->escapehtml($this->category->category)); ?>

<h2><?php echo $this->escapehtml($this->category->category); ?></h2>

<?php \FB::info($this->category); ?>

<?php \FB::info($this->bread, 'crumbs'); ?>

<?php \FB::info($this->products); ?>

<?php echo $this->breadcrumbs(); ?>

<div class="row">
	<div class="span2">
		
		<?php $subCats = $this->category()->getChildCategories($this->category->productCategoryId); ?>
		<?php if ($subCats->count() > 0): ?>
		<h5>In This Category</h5>
		<?php foreach ($subCats as $cat):?>
		<p><a href="<?php echo $this->url('shop/catalog', array(
    		'categoryIdent' => $cat->ident
    	)); ?>"><?php echo $this->escapehtml($cat->category); ?></a></p>
		<?php endforeach; ?>
		<?php endif; ?>
		
		<h5>Categories</h5>
		<?php foreach ($this->category()->getChildCategories() as $cat): ?>
		
		<p><a href="<?php echo $this->url('shop/catalog', array(
		    'categoryIdent' => $cat->ident
		)); ?>"><?php echo $this->escapehtml($cat->category); ?></a></p>
		
		<?php endforeach; ?>
	</div>
	
	<div class="span10">
		<ul class="thumbnails">
	
		<?php foreach ($this->products as $row): ?>
		    <li class="span3">
		    	<div class="thumbnail text-center">
		    		<img data-src="holder.js/200x100/auto" alt="">
		    		<h5><?php echo $this->escapehtml($row->name);?></h5>
		    		<a href="<?php echo $this->url('shop/catalog', array(
		    			'categoryIdent' => $this->category->ident
		    		)); ?>" class="btn">Click to see all Products in this Category</a>
		    	</div>
		    	
		    </li>
		<?php endforeach; ?>
	
		</ul>
	</div>
</div>
