<?php $this->headtitle($this->escapehtml($this->category->getCategory())); ?>

<h2>
    <?=$this->escapehtml($this->category->getCategory()); ?>
</h2>
<div>
    <?=$this->breadcrumbs(); ?>
</div>

<ul class="thumbnails">
<?php foreach ($this->products as $row): ?>
<?php \FB::info($row)?>
    <li class="span3">
    	<div class="thumbnail text-center product-item-box">
    		<img data-src="holder.js/200x100/auto" alt="<?=$this->escapehtml($row->getName()); ?>">
    		<h5><?=$this->escapehtml($row->getName());?> <?=$this->escapehtml($row->getSize()); ?></h5>
    		<p><?=$this->escapehtml($row->getShortDescription()); ?></p>
    		<p><b><?=$this->priceFormat($row->getPrice()); ?></b> for <?=$this->escapehtml(number_format($row->getPostUnit())); ?>g</p>
    		<?php $form = $this->cart()->addForm($row); ?>
		    <?=$this->form()->openTag($form); ?>
			    <div class="input-append">
			    <?=$this->formInput($form->get('qty')); ?>
			    <?=$this->formButton($form->get('buy-item')); ?>
			    </div>
			    <?=$this->formHidden($form->get('productId')); ?>
			    <?=$this->formHidden($form->get('returnTo')); ?>
		    <?=$this->form()->closeTag(); ?>
    	</div>
    </li>
<?php endforeach; ?>
</ul>

<?=$this->paginationControl(
    $this->products,
    'Elastic',
    'paginate',
	array(
		'route'		=> 'shop/catalog/page',
		'params' 	=> array(
			'categoryIdent' => $this->category->getIdent()
		)
	)
); ?>
		
