<?php $this->headtitle($this->escapehtml($this->category->getCategory())); ?>
<h2>
    <?=$this->escapehtml($this->category->getCategory()); ?>
</h2>

<?=$this->breadcrumbs(); ?>

<?php if (count($this->products) > 0):?>
<div class="row">
<?php /* @var $row \Shop\Model\Product\Product */ ?>
<?php foreach ($this->products as $row): ?>
    <div class="col-xs-4">
    	<div class="thumbnail text-center product-item-box">
    		<img src="<?=$this->basePath('/userfiles/shop/images/'.$row->getProductImage()[0]->getThumbnail());
            ?>" data-src="holder.js/200x100" alt="<?=$this->escapehtml($row->getName()); ?>">
    		<h5><?=$this->escapehtml($row->getName());?> <?=$this->escapehtml($row->getProductSize()->getSize()); ?></h5>
    		<p><?=$this->escapehtml($row->getShortDescription()); ?></p>
    		<?=$this->productPrice($row); ?>
    		<?php $form = $this->cart()->addForm($row); ?>
		    <?=$this->form()->openTag($form); ?>
			    <div class="input-group">
    			    <?=$this->formInput($form->get('qty')->setAttribute('class', 'form-control')); ?>
    			    <span class="input-group-btn">
        			    <button type="submit" name="buy-item" class="btn btn-default" value="">
                            add to <i class="glyphicon glyphicon-shopping-cart"></i>
                        </button>
                    </span>
			    </div>
			    <?=$this->formHidden($form->get('productId')); ?>
			    <?=$this->formHidden($form->get('returnTo')); ?>
		    <?=$this->form()->closeTag(); ?>
    	</div>
    </div>
<?php endforeach; ?>
</div>

<?=$this->paginationControl(
    $this->products,
    'Elastic',
    'application/partial/paginate',
	[
		'route'		=> 'shop/catalog/page',
		'routeParams' 	=> [
			'categoryIdent' => $this->category->getIdent()
		]
	]
); ?>

<?php else: ?>
<h4>There are no products in this category.</h4>
<?php endif; ?>
		
