<?php $this->headtitle('Shop Search'); ?>

<h2>Product Search Results</h2>

<?php if (count($this->products) > 0):?>
<div class="row">
<?php /* @var $row \Shop\Model\Product */ ?>
<?php foreach ($this->products as $row): ?>
    <div class="col-md-4">
    	<div class="thumbnail text-center product-item-box">
    		<img data-src="holder.js/200x100/auto" alt="<?=$this->escapehtml($row->getName()); ?>">
    		<h5><?=$this->escapehtml($row->getName());?> <?=$this->escapehtml($row->getProductSize()->getSize()); ?></h5>
    		<p><?=$this->escapehtml($row->getShortDescription()); ?></p>
    		<p><b><?=$this->productPrice($row); ?></b> for <?=$this->escapehtml(number_format($row->getPostUnit()->getPostUnit())); ?>g</p>
    		<?php $form = $this->cart()->addForm($row); ?>
		    <?=$this->form()->openTag($form); ?>
			    <div class="input-group">
    			    <?=$this->formInput($form->get('qty')->setAttribute('class', 'form-control')); ?>
    			    <span class="input-group-btn">
        			    <button type="submit" name="buy-item" class="btn btn-default" value="">
                            add to <i class="glyphicon glyphicon-shopping-cart"></i>
                        </button>
                    </span>
			    </div>
			    <?=$this->formHidden($form->get('productId')); ?>
			    <?=$this->formHidden($form->get('returnTo')); ?>
		    <?=$this->form()->closeTag(); ?>
    	</div>
    </div>
<?php endforeach; ?>
</div>
<?=$this->paginationControl(
    $this->products,
    'Elastic',
    'application/partial/paginate',
	['route' => 'shop/search/page']
); ?>
<?php else: ?>
<h4>No Products returned from your search.</h4>
<?php endif; ?>
<div class="loading ajax-loading"><!-- Place at bottom of page --></div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
    $('#content').searchForm({
        url : 'search',
        searchForm : $('#search-catalog'),
        paging : 'links'
    });
});
<?php $this->inlineScript()->captureEnd(); ?>

