<?php $this->headtitle('Shop Search'); ?>

<h2>Product Search Results</h2>

<?php if (count($this->products) > 0):?>
<ul class="thumbnails">
<?php foreach ($this->products as $row): ?>
    <li class="span3">
    	<div class="thumbnail text-center product-item-box">
    		<img data-src="holder.js/200x100/auto" alt="<?=$this->escapehtml($row->getName()); ?>">
    		<h5><?=$this->escapehtml($row->getName());?> <?=$this->escapehtml($row->getSize()); ?></h5>
    		<p><?=$this->escapehtml($row->getShortDescription()); ?></p>
    		<p><b><?=$this->productPrice($row); ?></b> for <?=$this->escapehtml(number_format($row->getPostUnit())); ?>g</p>
    		<?php $form = $this->cart()->addForm($row); ?>
		    <?=$this->form()->openTag($form); ?>
			    <div class="input-append">
			    <?=$this->formInput($form->get('qty')); ?>
			    <button type="submit" name="buy-item" class="btn" value="">
                    add to<i class="icon-shopping-cart"></i>
                </button>
			    </div>
			    <?=$this->formHidden($form->get('productId')); ?>
			    <?=$this->formHidden($form->get('returnTo')); ?>
		    <?=$this->form()->closeTag(); ?>
    	</div>
    </li>
<?php endforeach; ?>
</ul>
<?=$this->paginationControl(
    $this->products,
    'Elastic',
    'paginate',
	array('route' => 'shop/search/page')
); ?>
<?php else: ?>
<h4>No Products returned from your search.</h4>
<?php endif; ?>
<div class="loading ajax-loading"><!-- Place at bottom of page --></div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
    $('#content').searchForm({
        url : 'search',
        searchForm : $('#search-catalog'),
        paging : 'links'
    });
});
<?php $this->headScript()->captureEnd(); ?>

