
<?php $this->placeholder('header')->captureStart();?>
<?=$this->partial('shop/options', [
    'title' => $this->escapehtml($this->category->getCategory()),
    'bread' => $this->bread,
    'category' => $this->category,
]);?>
<?php $this->placeholder('header')->captureEnd();?>

<div class="row">
    <div class="col-md-3">
        <?=$this->partial('shop/product-nav');?>
    </div>
    <div class="col-md-9">
        <!-- PRODUCT LIST -->
        <div class="row">
            <?php /* @var $row \Shop\Model\Product\Product */ ?>
            <?php $c=0;?>
            <?php foreach ($this->products as $row): ?>
            <?php $c++;?>
            <div class="col-md-3 col-sm-3 shop-item-list"><!-- item -->
                <a href="<?=$this->url('shop/catalog/product', [
                    'categoryIdent' => $row->getProductCategory()->getIdent(),
                    'productIdent' => $row->getIdent(),
                ]);?>">
                    <?php if ($row->getShowImage()):?>
                    <figure><!-- image -->
                        <img class="" src="<?=$this->productImage($row);?>" alt="" />
                    </figure><!-- /image -->
                    <?php endif;?>
                    <?php if ($row->inStock()) : ?>
                    <span class="shop-stock-info stock-yes"><!-- stock -->
                        <span class="text-muted"><?=$this->escapehtml($row->getSku());?></span>
                        <i class="fa fa-check"></i>
                        <span class="text-muted">
                            <?=($row->getQuantity() > 0) ? $row->getQuantity() :'';?>
                        </span> in stock
                    </span><!-- /stock -->
                    <?php else: ?>
                    <span class="shop-stock-info stock-no"><!-- stock -->
                        <span class="text-muted"><?=$this->escapehtml($row->getSku());?></span>
                        <i class="fa fa-times"></i> out of stock
                    </span><!-- /stock -->
                    <?php endif; ?>
                    <div class="product-info"><!-- title and price -->
                        <h2>
                            <span class="product-name"><?=$row->getName();?></span>
                            <?=$this->productPrice($row)
                                ->setFormat('<span class="bold">%s</span> %s %s ')
                                ->setDiscountFormat('<span class="line-through">%s</span>'); ?>

                        </h2>
                    </div><!-- /title and price -->
                </a>
                
                <?php $form = $this->cart()->addForm($row)->setAttribute('class', 'margin-top10 nopadding clearfix'); ?>
                
                <?php if ($row->inStock()):?>
                <?=$this->form()->openTag($form); ?>
                    <?=$this->formHidden($form->get('productId')); ?>
                    <?=$this->formHidden($form->get('returnTo')); ?>
                    
                    <?php if ($row->getProductOption()): ?>
                    <div class="row">
                        <div class="col-md-12">
                            <?=$this->productOptions($row);?>
                        </div><!-- /btn-group -->
                    </div>
                    <?php endif; ?>
                    
                    <?=$this->formInput($form->get('qty')->setAttribute('class', 'form-control')); ?>
                    
                    <button type="submit" name="buy-item" class="btn btn-primary col-sm-12 col-md-12">
                        ADD TO CART
                        <?=$this->cart()->hasProductInCart($row);?>
                    </button>
                    
                <?=$this->form()->closeTag(); ?>
                <?php endif; ?>
            </div><!-- /item -->
            <?php if (($c % 4) === 0):?>
    	    <div class="clearfix"></div>
    	    <?php endif;?>
            <?php endforeach; ?>
        </div><!-- /PRODUCT LIST -->
    </div>
</div>

<!-- PAGINATION -->
<?=$this->paginationControl(
    $this->products,
    'Elastic',
    'application/partial/paginate',
    [
        'route'		=> 'shop/catalog/page',
        'routeParams' 	=> [
            'categoryIdent' => $this->category->getIdent()
        ]
    ]
); ?><!-- /PAGINATION -->
