
<?php $this->placeholder('header')->captureStart();?>
<?=$this->partial('shop/options', [
    'title' => 'Product Search'
]);?>
<?php $this->placeholder('header')->captureEnd();?>
<div id="search-content">
    <div class="row">
        <div class="col-md-3 hidden-sm">
            <?=$this->partial('shop/product-nav');?>
        </div>
        <div class="col-md-9">
            <!-- PRODUCT LIST -->
            <div class="row">
                <?php /* @var $row \Shop\Model\Product\Product */ ?>
                <?php foreach ($this->products as $row): ?>
                    <div class="col-md-4 col-sm-4 shop-item-list"><!-- item -->
                        <a href="<?=$this->url('shop/catalog/product', [
                            'categoryIdent' => $row->getProductCategory()->getIdent(),
                            'productIdent' => $row->getIdent(),
                        ]);?>">
                            <figure><!-- image -->
                                <img class="" src="<?=$this->productImage($row);?>" alt="" />
                            </figure><!-- /image -->
                            <?php if ($row->inStock()) : ?>
                            <span class="shop-stock-info stock-yes"><!-- stock -->
                                <span class="text-muted"><?=$this->escapehtml($row->getSku());?></span>
                                <i class="fa fa-check"></i>
                                <span class="text-muted">
                                    <?=($row->getQuantity() > 0) ? $row->getQuantity() :'';?>
                                </span> in stock
                            </span><!-- /stock -->
                            <?php else: ?>
                            <span class="shop-stock-info stock-no"><!-- stock -->
                                <span class="text-muted"><?=$this->escapehtml($row->getSku());?></span>
                                <i class="fa fa-times"></i> out of stock
                            </span><!-- /stock -->
                            <?php endif; ?>
                            <div class="product-info"><!-- title and price -->
                                <h2>
                                    <span class="product-name"><?=$row->getName();?></span>
                                    <?=$this->productPrice($row)
                                        ->setFormat('<span class="bold">%s</span> %s for %s gms ')
                                        ->setDiscountFormat('<span class="line-through">%s</span>'); ?>
        
                                </h2>
                            </div><!-- /title and price -->
                        </a>
                        
                        <?php $form = $this->cart()->addForm($row)->setAttribute('class', 'margin-top10 nopadding clearfix'); ?>
                        
                        <?=$this->form()->openTag($form); ?>
                            <?=$this->formHidden($form->get('productId')); ?>
                            <?=$this->formHidden($form->get('returnTo')); ?>
                            
                            <?php if ($row->getProductOption()): ?>
                            <div class="row">
                                <div class="col col-md-12">
                                    <?=$this->productOptions($row);?>
                                </div><!-- /btn-group -->
                            </div>
                            <?php endif; ?>
                            
                            <div class="input-group">
                                <?=$this->formInput($form->get('qty')->setAttribute('class', 'form-control')); ?>
                                <span class="input-group-btn">
                                    <button type="submit" name="buy-item" class="btn btn-primary">
                                        ADD TO CART
                                    </button>
                                </span>
                            </div>
                            
                        <?=$this->form()->closeTag(); ?>
                    </div><!-- /item -->
                <?php endforeach; ?>
            </div><!-- /PRODUCT LIST -->
        </div>
    </div>

    <!-- PAGINATION -->
    <?=$this->paginationControl(
        $this->products,
        'Elastic',
        'application/partial/paginate',
        ['route' => 'shop/search/page']
    ); ?><!-- /PAGINATION -->
</div>

<?php $this->inlineScript()->appendFile($this->basePath('/js/jquery.searchForm.js')) ?>
<?php $this->inlineScript()->captureStart(); ?>
    $(document).ready(function(){
        $('#search-content').searchForm({
            url : '<?=$this->url('shop/search');?>',
            searchForm : $('#search-catalog'),
            paging : 'links'
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>