<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Charisma Beads Ltd')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
        				->prependFile($this->basePath() . '/js/site.js')
        				->prependFile($this->basePath() . '/js/jquery.placeholder.min.js')
        				->prependFile($this->basePath() . '/js/holder.js')
        				->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        				->prependFile($this->basePath() . '/js/bootstrap.min.js')
                        ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
    	<div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div id="top-bar-nav" class="container">
                    <div class="dropdown">
                    	<?php if ($this->identity()): ?>
	                    <ul class="nav pull-right">
	                	    <li>
	                	        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	    					        <?php echo $this->ztbIcon()->user(); ?> <?php echo $this->identity()->getFullName(); ?> 
	    					        <b class="caret"></b>
	    				        </a>
	    				        
	                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
	                                <li>
	                                    <a href="<?php echo $this->url('user/default', array(
	                	                    'action' => 'edit'
	            	                    )); ?>">Edit Profile
	    				                </a>
	                                </li>
	                                <li>
	                                    <a href="<?php echo $this->url('user/logout'); ?>">Logout</a>
	                                </li>
	                            </ul>
	
	                	    </li>
	                	</ul>
	                	<?php endif; ?>
                	</div>
                </div>
            </div>
        </div>
        <div id="main-content" class="container">
			
            <div id="header">
                <a><img alt="Charisma Beads Ltd" src="<?php echo $this->basepath('/img/layout/logo.png'); ?>"></a>
            </div>
            <div class="navbar">
				<div class="navbar-inner">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
					<div class="nav-collapse">
	            		<?php echo $this->aclMenu('model', 'top menu', 'navigation/tb-nested-menu', false); ?>
	            		<ul class="nav pull-right">
							<li class="divider-vertical"></li>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-search"></i></a>
									<div class="dropdown-menu">
										<form class="form-search">
											<div class="input-append">
												<input type="text" class="search-query" placeholder="Type your search...">
												<button class="btn">ok</button>
											</div>
										</form> 
									</div>
							</li>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-envelope"></i></a>
								<div class="dropdown-menu">
									<address>
										<strong>CompanyName</strong><br>
										Address 123<br>
										Zipcode, State and City
									</address>
									<hr>
									<strong>Phone</strong>: 012-345 67 89<br>
									<a href="contact.html"><strong>E-mail</strong>: info@example.com</a>
								</div>
							</li>
							<li class="dropdown shop-summary">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">
									<i class="icon-shopping-cart"></i>
									<span class="badge badge-inverse"><?php echo $this->cart()->countItems(); ?></span>
								</a>
								<div class="dropdown-menu">
									<?php echo $this->cart()->getSummary(); ?>
								</div>
							</li>
						</ul>
					</div>
            	</div>
            </div>
            <div class="row">
            	<div class="span12">
            		<?php echo $this->ztbFlashMessenger()->render(); ?>
            	</div>
            	<div class="span12">
            		<?php echo $this->content; ?>
            	</div>
            </div>
            
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Charisma Beads Ltd. All rights reserved.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
