<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?=$this->headTitle('Charisma Beads Ltd')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?=$this->headMeta()->appendName('X-UA-Compatible', 'IE=edge') ?>

        <!-- Le styles -->
        <?=$this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basepath() . '/css/glyphicons.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
            ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?=$this->headScript()
			->prependFile($this->basePath() . '/js/site.js')
			->prependFile($this->basePath() . '/js/jquery.placeholder.min.js')
			->prependFile($this->basePath() . '/js/holder.js')
			->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/js/bootstrap.js')
            ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js') ?>

    </head>
    <body>
    	<div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div id="top-bar-nav" class="container">
                    <form class="form-search navbar-search pull-left">
                        <div class="input-append">
							<input type="text" class="search-query" placeholder="Type your search...">
						  <button class="btn"><i class="icon-search"></i></button>
						</div>
                    </form>
                    <div class="dropdown">
                    	<?php if ($this->identity()): ?>
	                    <ul class="nav pull-right">
	                	    <li>
	                	        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	    					        <?=$this->ztbIcon()->user(); ?> <?=$this->identity()->getFullName(); ?> 
	    					        <b class="caret"></b>
	    				        </a>
	    				        
	                            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
	                                <li>
	                                    <a href="<?=$this->url('user/default', array(
	                	                    'action' => 'edit'
	            	                    )); ?>">Edit Profile
	    				                </a>
	                                </li>
	                                <li>
	                                    <a href="<?=$this->url('user/logout'); ?>">Logout</a>
	                                </li>
	                            </ul>
	
	                	    </li>
	                	</ul>
	                	<?php endif; ?>
                	</div>
                </div>
            </div>
        </div>
        <div id="main-content" class="container">
			
            <div id="header" class="row">
                    <h2 class="span12">
                        <a><img alt="Charisma Beads Ltd" src="<?=$this->basepath('/img/layout/logo.png'); ?>"></a>
                        <span class="pull-right"><i class="glyphicons phone_alt">&nbsp;</i>01462 454054</span>
                    </h2>
            </div>
            <div class="navbar">
				<div class="navbar-inner">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
					<div class="nav-collapse">
	            		<?=$this->aclMenu('model', 'top menu'); ?>
	            		<ul class="nav pull-right">
							<li class="divider-vertical"></li>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-envelope"></i></a>
								<div class="dropdown-menu">
									<address>
										<strong>CompanyName</strong><br>
										Address 123<br>
										Zipcode, State and City
									</address>
									<hr>
									<strong>Phone</strong>: 012-345 67 89<br>
									<a href="contact.html"><strong>E-mail</strong>: info@example.com</a>
								</div>
							</li>
							<li class="dropdown shop-summary">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#">
									<i class="icon-shopping-cart"></i>
									<span class="badge badge-inverse"><?=$this->cart()->countItems(); ?></span>
								</a>
								<div class="dropdown-menu">
									<?=$this->cart()->getSummary(); ?>
								</div>
							</li>
						</ul>
					</div>
            	</div>
            </div>
            
            <div class="row">
                <div class="span12">
            		<?=$this->ztbFlashMessenger()->render(); ?>
            	</div>
                <div id="product-nav" class="span3">	
            		<h5>Categories</h5>
            		<ul class="nav nav-list">
            		<?php foreach ($this->category()->getChildCategories() as $cat): ?>
                        <?php $liClass = ($cat->getDepth() == 0) ? 'nav-header' : ''; ?>
                		<li class="<?=$liClass; ?>"><a href="<?=$this->url('shop/catalog', array(
                		    'categoryIdent' => $cat->getIdent()
                		)); ?>"><?=$this->escapehtml($cat->getCategory()); ?></a></li>
            		
            		<?php endforeach; ?>
            		</ul>
            	</div>
            	
            	<div class="span9">
            		<?=$this->content; ?>
            	</div>
            </div>
            
            <hr>
            <footer>
                <p>&copy; 2005 - <?=date('Y'); ?> by Charisma Beads Ltd. All rights reserved.</p>
            </footer>
        </div> <!-- /container -->
        <?=$this->inlineScript() ?>
    </body>
</html>
