<?php $this->headTitle('Add Tax Rate') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Tax Rate'); ?>

<?php $this->placeholder('header-buttons')->captureStart(); ?>
    <button type="submit" form="form-tax-rate" data-toggle="tooltip" title="<?= $this->translate('Save'); ?>"
            class="btn btn-primary">
        <i class="fa fa-save"></i>
    </button>
    <a href="<?= $this->url('admin/shop/tax/rate'); ?>" data-toggle="tooltip" title="<?= $this->translate('Cancel'); ?>"
       class="btn btn-default">
        <i class="fa fa-reply"></i>
    </a>
<?php $this->placeholder('header-buttons')->captureEnd(); ?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-tax-rate',
    'action' => $this->url('admin/shop/tax/rate/edit', [
        'action' => 'add',
    ]),
]); ?>

<div id="tax-rate-add" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?= $this->translate('Add Tax Rate'); ?></h3>
    </div>
    <div class="panel-body">
        <?= $this->form($this->form); ?>
    </div>
</div>
