<?php $this->headTitle('Tax Rates') ?>

<?php if (count($this->models) > 0): ?>
<div class="table-responsive">
    <table id="taxCode-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="taxRateId">Tax Rate Id</th>
    			<th data-field="taxRate">Tax Rate</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    		<?php /* @var $row \Shop\Model\TaxCodeModel */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getTaxRateId()); ?></td>
    			<td><?=$this->escapeHtml($this->percentFormat($row->getTaxRate(true))); ?></td>
    			<td>
                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                    	'pk'		=> 'taxRateId',
                    	'id'		=> $row->getTaxRateId(),
    		    		'tableName'	=> 'taxRate',
                    	'route'		=> 'admin/shop/tax/rate/edit',
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>
<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/shop/tax/rate/page']
); ?>

<?php else: ?>
<h4>No Tax Rates where returned by search.</h4>
<?php endif; ?>
