
<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('layout/page-title', [
    'pageTitle' => '500 Server Error',
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<?php if($this->shopOption('developmentMode')): ?>

    <h1><?=$this->translate('An error occurred') ?></h1>
    <h2><?=$this->message; ?></h2>

    <?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>

        <?php if(isset($this->exception)
            && ($this->exception instanceof \Exception || $this->exception instanceof \Error)): ?>
            <hr/>
            <h2><?=$this->translate('Additional information') ?>:</h2>
            <h3><?=get_class($this->exception); ?></h3>
            <dl>
                <dt><?=$this->translate('File') ?>:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?=$this->exception->getFile() ?>:<?=$this->exception->getLine() ?></pre>
                </dd>
                <dt>Message:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?=$this->exception->getMessage() ?></pre>
                </dd>
                <dt>Stack trace:</dt>
                <dd>
                    <pre class="prettyprint linenums"><?=$this->exception->getTraceAsString() ?></pre>
                </dd>
            </dl>
            <?php
            $e = $this->exception->getPrevious();
            if ($e) :
                ?>
                <hr/>
                <h2>Previous exceptions:</h2>
                <ul class="unstyled">
                    <?php while($e) : ?>
                        <li>
                            <h3><?=get_class($e); ?></h3>
                            <dl>
                                <dt><?=$this->translate('File') ?>:</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?=$e->getFile() ?>:<?=$e->getLine() ?></pre>
                                </dd>
                                <dt><?=$this->translate('Message') ?>:</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?=$e->getMessage() ?></pre>
                                </dd>
                                <dt><?=$this->translate('Stack trace') ?>:</dt>
                                <dd>
                                    <pre class="prettyprint linenums"><?=$e->getTraceAsString() ?></pre>
                                </dd>
                            </dl>
                        </li>
                        <?php
                        $e = $e->getPrevious();
                    endwhile;
                    ?>
                </ul>
            <?php endif; ?>

        <?php else: ?>

            <h3>No Exception available</h3>

        <?php endif ?>

    <?php endif ?>

<?php else: ?>

<div class="row default-e404">

    <div class="col-md-9">

        <span class="default-404"><i class="fa fa-file"></i> 500</span>
        <p class="text-center lead">
            We're sorry, but something seems to have gone wrong. We have been notified and will look into it.
        </p>
        <p class="text-center">
            If the error happened while attempting to pay for items in your shopping cart,
            please check your order history to see if your order in payment pending.
            <a href="<?=$this->url('shop/order');?>">Order History</a>
        </p>
    </div>

    <div class="col-md-3">

        <h4>Useful Links</h4>

        <!-- SIDE NAV -->
        <?=$this->partial('shop/product-nav');?>
        <!-- /SIDE NAV -->

    </div>
</div>

<?php endif; ?>