<?php $this->headTitle('Orders') ?>
<?php $this->layout()->pageTitle = $this->translate('Orders');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<a href="<?=$this->url('admin/shop/order/edit', [
	'action' => 'add'
]);?>" data-toggle="tooltip" title="<?=$this->translate('Add Order');?>" class="btn btn-primary" id="order-add">
	<i class="fa fa-plus"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-list"></i> <?=$this->translate('Orders List');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->partial('uthando-admin/partial/search', [
            'name'			=> 'order',
            'searchInputs'	=> [
                $this->translate('Order') => 'orderNumber',
            ],
        ]);?>
    </div>
    <div id="table-order" class="admin-table">
        <?=$this->partial('shop/order/list', [
            'models' => $this->models
        ]); ?>
    </div>
</div>

<?php $this->inlineScript()
    ->appendFile($this->basePath('js/admin/shop/typeahead.bundle.min.js'))
    ->appendFile($this->basePath('js/admin/shop/shop.js'))
    ->appendFile($this->basePath('js/admin/shop/orders.js'));?>

<script>
    $(document).ready(function(){
        $('#table-order').dataGrid({
            url : 'order/list',
            query: { sort : '-orderDate' },
            searchForm : $('#search-order'),
            paging : 'links',
            columnSort: true,
        });
    });
</script>
