<?php $this->headTitle('Orders'); ?>

<?php if (count($this->models) > 0): ?>
<div class="panel panel-default">
    <table id="order-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="orderId">Order Id</th>
    			<th data-field="orderNumber">Order Number</th>
    			<th data-field="orderStatus">Order Status</th>
    			<th data-field="total">Total</th>
    			<th data-field="orderDate">Order Date</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    		<?php /* @var $row \Shop\Model\Order */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getOrderId());?></td>
    			<td><?=$this->escapeHtml($row->getOrderNumber());?></td>
    			<td><?=$this->escapehtml($row->getOrderStatus()->getOrderStatus());?></td>
    			<td><?=$this->priceFormat($this->escapeHtml($row->getTotal()));?></td>
    			<td><?=$this->formatDate($row->getOrderDate());?>
    			<td>
                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                    	'pk'		=> 'orderId',
                    	'id'		=> $row->getOrderId(),
    		    		'tableName'	=> 'order',
                    	'route'		=> 'admin/shop/order/edit',
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>
<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/shop/order/page']
); ?>

<?php else: ?>
<h4>No Orders where returned by search.</h4>
<?php endif; ?>
