<?php $this->headTitle('Orders') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->models) > 0): ?>

<table id="order-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="orderId">Order Id</th>
			<th data-field="total">Total</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php /* @var $row \Shop\Model\Order */ ?>
		<?php foreach($this->models as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getOrderId()); ?></td>
			<td><?=$this->priceFormat($this->escapeHtml($row->getTotal())); ?></td>
			<td>
                <?=$this->partial('partial/edit-actions', array(
                	'pk'		=> 'orderId',
                	'id'		=> $row->getOrderId(),
		    		'tableName'	=> 'order',
                	'route'		=> 'admin/shop/order/edit',
		    	));?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/order/page')
); ?>

<?php else: ?>
<h4>No Orders where returned by search.</h4>
<?php endif; ?>
