
<?php
$statusFormElement = $this->formManager(\Shop\Form\Element\OrderStatusList::class);
$statusFormElement->setName('orderStatusId');
?>

<?php if (count($this->models) > 0): ?>
<div class="table-responsive">
    <table id="order-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="orderId">Order Id</th>
    			<th data-field="orderNumber">Order Number</th>
                <th>Payment Id</th>
    			<th data-field="orderStatus">Order Status</th>
    			<th data-field="total">Total</th>
    			<th data-field="orderDate">Order Date</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    		<?php /* @var $row \Shop\Model\Order\OrderModel */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getOrderId());?></td>
    			<td><?=$this->escapeHtml($row->getOrderNumber(false));?></td>
				<td>
                    <a class="paypal-payment-lookup" href="<?=$this->url('admin/shop/paypal', [
                        'action' => 'search',
                        'paymentId' => $this->escapeHtml($row->getMetadata()->getPaymentId()),
                    ]);?>">
                        <?=$this->escapeHtml($row->getMetadata()->getPaymentId());?>
                    </a>
                </td>
    			<td>
                    <?=$this->formSelect(
                        $statusFormElement->setValue($row->getOrderStatusId())
                            ->setAttribute('class', 'form-control input-sm order-status-select')
                    );?>
                    <input type="hidden" name="orderNumber" value="<?=$row->getOrderNumber(false);?>">
                </td>
    			<td><?=$this->priceFormat($this->escapeHtml($row->getTotal() + $row->getTaxTotal()));?></td>
    			<td><?=$this->formatDate($row->getOrderDate());?>
    			<td>
                    <?=$this->partial('shop/order/partial/edit-actions', [
                    	'pk'		=> 'orderId',
                    	'order'		=> $row,
    		    		'tableName'	=> 'order',
                    	'route'		=> 'admin/shop/order/edit',
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>
<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/shop/order/page']
); ?>

<?php else: ?>
<h4>No Orders where returned by search.</h4>
<?php endif; ?>
