<style>
    #totals-footer {
        margin-top: 5px;
        margin-bottom: 5px;
        text-align: center;
        font-size: 12px;
        color: #999;
    }

    .totals-container {
        box-sizing: border-box;
        width: 100%;
        height: 270px;
        padding: 20px 15px 15px 15px;
        border: 1px solid #ddd;
        background: #fff;
        background: linear-gradient(#f6f6f6 0, #fff 50px);
        background: -o-linear-gradient(#f6f6f6 0, #fff 50px);
        background: -ms-linear-gradient(#f6f6f6 0, #fff 50px);
        background: -moz-linear-gradient(#f6f6f6 0, #fff 50px);
        background: -webkit-linear-gradient(#f6f6f6 0, #fff 50px);
        box-shadow: 0 3px 10px rgba(0,0,0,0.15);
        -o-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
        -ms-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
        -moz-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
        -webkit-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
    }

    .totals-placeholder {
        width: 100%;
        height: 100%;
        font-size: 10px;
        line-height: 1em;
    }

    .totals-container {
        position : relative;
    }

</style>

<script src="<?=$this->basePath('js/flot/jquery.flot.js');?>"></script>
<script src="<?=$this->basePath('js/flot/jquery.flot.resize.js');?>"></script>

<div class="totals-container">
    <div id="totals-placeholder" class="totals-placeholder"></div>
</div>

<div id="totals-footer"></div>

<script type="text/javascript">

    $(function() {

        var mtData = <?=$this->monthlyTotals;?>;

        var ticks = [
            ["01", "Jan"], ["02", "Feb"], ["03", "Mar"], ["04", "Apr"], ["05", "May"], ["06", "June"],
            ["07", "July"], ["08", "Aug"], ["09", "Sept"], ["10", "Oct"], ["11", "Nov"], ["12", "Dec"]
        ];

        var totalsPlaceholder = $("#totals-placeholder");

        $.plot(totalsPlaceholder, mtData, {
            series : {
                lines: {
                    show: true
                },
                points:{
                    show: true,
                    radius: 3
                }
            },
            xaxis: {
                ticks : ticks
            },
            grid : {
                hoverable: true
            }
        });

        // Add the Flot version string to the footer

        $("#totals-footer").prepend("Flot " + $.plot.version);
    });

</script>