
<div class="plot-container">
    <div id="totals-placeholder" class="plot-placeholder"></div>
</div>

<script type="text/javascript">

    $(function() {

        var mtData = <?=$this->monthlyTotals;?>;

        var i = 0;
        $.each(mtData, function(key, val) {
            val.color = i;
            ++i;
        });

        var totalsPlaceholder = $("#totals-placeholder");

        var totalsPlot = $.plot(totalsPlaceholder, mtData, {
            series : {
                lines: {
                    show: true
                },
                points:{
                    show: true,
                    radius: 3
                }
            },
            xaxis: {
                mode: 'categories',
                tickLength: 0
            },
            grid : {
                hoverable: true,
                clickable: true
            }
        });

        totalsPlaceholder.bind("plotclick plothover", function (event, pos, item) {

            var previousPoint = null, previousLabel = null;

            if (item) {
                if ((previousPoint != item.dataIndex) || (previousLabel != item.series.label)) {
                    previousPoint = item.dataIndex;
                    previousLabel = item.series.label;
                    $("#tooltip").remove();

                    var month = item.series.data[item.datapoint[0]][0];
                    var currentTotal = item.datapoint[1];

                    var nextSeries = totalsPlot.getData()[item.seriesIndex + 1];
                    var increaseDecrease = 0;

                    if (nextSeries) {
                        var nextTotal = nextSeries.data[item.dataIndex][1];

                        if (nextTotal > 0) {
                            increaseDecrease = ((currentTotal - nextTotal) / nextTotal) * 100;
                        } else {
                            increaseDecrease = currentTotal;
                        }
                    }

                    var color = item.series.color;

                    showTooltip(item.pageX,
                        item.pageY,
                        color,
                        "<strong>" + item.series.label + "</strong><br>" + month
                        + " : <strong>&pound;" + currentTotal + "</strong> +&#92;- (" + increaseDecrease.toFixed(2) + "%)");
                }
            } else {
                $("#tooltip").remove();
                previousPoint = null;
                previousLabel = null;
            }

        });

        function showTooltip(x, y, color, contents) {
            $('<div id="tooltip">' + contents + '</div>').css({
                position: 'absolute',
                display: 'none',
                top: y - 40,
                left: x - 120,
                border: '2px solid ' + color,
                padding: '3px',
                'font-size': '9px',
                'border-radius': '5px',
                'background-color': '#fff',
                'font-family': 'Verdana, Arial, Helvetica, Tahoma, sans-serif',
                opacity: 0.9
            }).appendTo("body").fadeIn(200);
        }
    });

</script>