<style>
    #totals-footer {
        margin-top: 5px;
        margin-bottom: 5px;
        text-align: center;
        font-size: 12px;
        color: #999;
    }

    .totals-container {
        box-sizing: border-box;
        width: 100%;
        height: 270px;
        padding: 20px 15px 15px 15px;
        border: 1px solid #ddd;
        background: #fff;
        background: linear-gradient(#f6f6f6 0, #fff 50px);
        background: -o-linear-gradient(#f6f6f6 0, #fff 50px);
        background: -ms-linear-gradient(#f6f6f6 0, #fff 50px);
        background: -moz-linear-gradient(#f6f6f6 0, #fff 50px);
        background: -webkit-linear-gradient(#f6f6f6 0, #fff 50px);
        box-shadow: 0 3px 10px rgba(0,0,0,0.15);
        -o-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
        -ms-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
        -moz-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
        -webkit-box-shadow: 0 3px 10px rgba(0,0,0,0.1);
    }

    .totals-placeholder {
        width: 100%;
        height: 100%;
        font-size: 10px;
        line-height: 1em;
    }

    .totals-container {
        position : relative;
    }

</style>

<div class="totals-container">
    <div id="totals-placeholder" class="totals-placeholder"></div>
</div>

<div id="totals-footer"></div>

<script type="text/javascript">

    $(function() {

        var mtData = <?=$this->monthlyTotals;?>;

        var monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

        var ticks = [
            ["01", monthNames[0]], ["02", monthNames[1]], ["03", monthNames[2]], ["04", monthNames[3]],
            ["05", monthNames[4]], ["06", monthNames[5]], ["07", monthNames[6]], ["08", monthNames[7]],
            ["09", monthNames[8]], ["10", monthNames[9]], ["11", monthNames[10]], ["12", monthNames[11]]
        ];

        var totalsPlaceholder = $("#totals-placeholder");
        var previousPoint = null, previousLabel = null;

        $(this).bind("plotclick plothover", function (event, pos, item) {
            if (item) {
                if ((previousPoint != item.dataIndex) || (previousLabel != item.series.label)) {
                    previousPoint = item.dataIndex;
                    previousLabel = item.series.label;
                    $("#tooltip").remove();

                    var month = item.datapoint[0] - 1;
                    var currentTotal = item.datapoint[1];

                    var nextSeries = totalsPlot.getData()[item.seriesIndex + 1];
                    var increaseDecrease = 0;

                    if (nextSeries) {
                        var nextTotal = nextSeries.data[item.dataIndex][1];
                        increaseDecrease = ((currentTotal - nextTotal) / nextTotal) * 100;
                    }

                    var color = item.series.color;

                    showTooltip(item.pageX,
                        item.pageY,
                        color,
                        "<strong>" + item.series.label + "</strong><br>" + monthNames[month]
                        + " : <strong>&pound;" + currentTotal + "</strong> +&#92;- (" + increaseDecrease.toFixed(2) + "%)");
                }
            } else {
                $("#tooltip").remove();
                previousPoint = null;
                previousLabel = null;
            }

        });

        function showTooltip(x, y, color, contents) {
            $('<div id="tooltip">' + contents + '</div>').css({
                position: 'absolute',
                display: 'none',
                top: y - 40,
                left: x - 120,
                border: '2px solid ' + color,
                padding: '3px',
                'font-size': '9px',
                'border-radius': '5px',
                'background-color': '#fff',
                'font-family': 'Verdana, Arial, Helvetica, Tahoma, sans-serif',
                opacity: 0.9
            }).appendTo("body").fadeIn(200);
        }

        var totalsPlot = $.plot(totalsPlaceholder, mtData, {
            series : {
                lines: {
                    show: true
                },
                points:{
                    show: true,
                    radius: 3
                }
            },
            xaxis: {
                ticks : ticks
            },
            grid : {
                hoverable: true,
                clickable: true
            }
        });

        // Add the Flot version string to the footer

        $("#totals-footer").prepend("Flot " + $.plot.version);
    });

</script>