
<html>
    <head>
        <?=$this->headTitle('Charisma Beads Ltd - Order #' . $this->order->getOrderNumber()) ?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <style type="text/css">
            body {
            	font-size: 12pt;
            }
            
            h4 {
            	font-weight: bold;
                line-height: 1.1;
            	font-size: 18px;
            }
            
            td, th {
            	vertical-align:top;
            }
            
            .col-12 {
            	width: 100%;
            }
            
            .col-6 {
            	width: 45%;
            }
            
            .panel {
            	margin-bottom: 20px;
            	background-color: #fff;
            	border: 1px solid transparent;
            	border-radius: 4px;
            	border-spacing: 0px;
            }
            
            .panel-body {
            	padding: 15px;
            }
            
            .panel-heading {
            	padding: 10px 15px;
            	border-bottom: 1px solid transparent;
            	border-top-left-radius: 3px;
            	border-top-right-radius: 3px;
            }
            
            .panel-title {
            	margin-top: 0;
            	margin-bottom: 0;
            	font-size: 16px;
            	color: inherit;
            }
            
            .panel-default {
            	border-color: #ddd;
            }
            
            .panel-default .panel-heading {
            	color: #333;
            	background-color: #f5f5f5;
            	border-color: #ddd;
            }
            
            .panel-default .panel-heading {
            	border-top-color: #ddd;
            }
            
            .address-heading, .address-body {
            	border: 1px solid #ddd;
            }
            
            .address-body {
            	border-top: none;
            	border-bottom-left-radius: 3px;
            	border-bottom-right-radius: 3px;
            }
            
            .panel .table {
            	margin-bottom: 0;
            }
            
            .table {
            	width: 100%;
            	max-width: 100%;
            	margin-bottom: 20px;
            	text-align: left;
            	border-spacing: 0;
                border-collapse: collapse;
            	padding: 0px;
            }
            
            .table th, .table td {
            	padding: 8px;
            	line-height: 1.42857143;
            	border: 1px solid #ddd !important;
            }
            
            .table tr:nth-child(odd) {
            	background-color: #f5f5f5;
            }
            
            .table .first-row th {
            	border-top: none;
            	text-align: left;
            }
            
            .text-right {
            	text-align: right;
            }
            
            .footer {
            	position: fixed;
            	bottom: 0px;
            	height: 30px;
            	font-size:10px;
            	text-align: center;
            }
        </style>
    </head>
    <body>
        <table class="col-12">
            <tr>
                <td class="col-6">
                    <img src="<?=APPLICATION_PATH . '/public/' . $this->themeOptions('logo');?>" height="50" alt="logo">
                    <img src="<?=APPLICATION_PATH . '/public/' . $this->themeOptions('logo2');?>" height="50" alt="logo" >
                </td>
                <td class="col-6 text-right">
                    <?=$this->contact('details.address.line1');?><br />
                    <?php if($this->contact('details.address.line2') != ''):?>
                    <?=$this->contact('details.address.line2');?>,<br />
                    <?php endif;?>
                    <?=$this->contact('details.address.town');?>,<br />
                    <?=$this->contact('details.address.county');?>, <?=$this->contact('details.address.postcode');?><br />
                    <?=$this->contact('details.phone');?><br />
                    <?=$this->contact('details.email');?>
                </td>
            </tr>
        </table>

        <table class="col-12 panel panel-default">
            <tr>
                <td class="panel-heading" colspan="3">
                    <h4 class="panel-title"> Order Details</h4>
                </td>                   
            </tr>
            <tr>
                <td class="col-6 panel-body">
                    Order No:&nbsp;<span><?=$this->escapeHtml($this->order->getOrderNumber());?></span><br>
                    Customer No:&nbsp;<span><?=$this->escapeHtml($this->order->getCustomer()->getNumber());?></span><br>
                    Date Ordered:&nbsp;<span><?=$this->formatDate($this->order->getOrderDate())->setFormat('d/m/Y');?></span>
                </td>
                <td>&nbsp;</td>
                <td class="col-6 panel-body">
                    Status: <span><?=$this->escapeHtml($this->order->getOrderStatus()->getOrderStatus());?></span><br>
                    Payment Method: <span><?=$this->escapeHtml($this->order->getMetaData()->getPaymentMethod());?></span><br>
                    Shipping Method: <span><?=$this->escapeHtml($this->order->getMetaData()->getShippingMethod());?></span>
                </td>
            </tr>
        </table>

        <table class="col-12 panel address">
            <tr class="panel panel-default">
                <td class="col-6 panel-heading address-heading">
                    <h4 class="panel-title"> Billing Address</h4>
                </td>                 
                <td>&nbsp;</td>  
                <td class="col-6 panel-heading address-heading">
                    <h4 class="panel-title"> Delivery Address</h4>
                </td>                     
            </tr>
            <tr class="panel panel-default">
                <td class="panel-body address-body">
                   <address>
                        <?=$this->customerAddress()
                            ->setOrder($this->order)
                            ->includeName()
                            ->includeEmail()
                            ->formatAddress(
                                $this->order->getMetadata()
                                    ->getBillingAddress()
                        );?>
                    </address>
                </td>
                <td>&nbsp;</td>
                <td class="panel-body address-body">
                   <address>
                        <?=$this->customerAddress()
                            ->setOrder($this->order)
                            ->includeName()
                            ->formatAddress(
                                $this->order->getMetadata()
                                    ->getBillingAddress()
                        );?>
                    </address>
                </td>
            </tr>
        </table>

        <table class="col-12 panel table">
            <tr class="first-row">
        		<th>Product</th>
        		<th>Description</th>
        		<th>Price</th>
        		<th>Quantity</th>
        		<th>Total</th>
        	</tr>
        	
        	<?php /* @var $item \Shop\Model\Order\Line */ ?>
        	<?php foreach ($this->order->getOrderlines() as $item): ?>
        	<tr>
        		<td><?=$item->getMetadata()->getSku();?></td>
        		<td>
        		  <?=$item->getMetadata()->getCategory();?> / <?=$item->getMetadata()->getName();?>
        		  <?php if ($item->getMetadata()->getPostUnit() > 0): ?><br />
                  &nbsp;(<?=$item->getMetadata()->getPostUnit();?> grams)
                  <?php endif; ?>
    		    </td>
        		<td><?=$this->priceFormat($item->getPrice());?></td>
        		<td><?=$item->getQty();?></td>
        		<td><?=$this->priceFormat($item->getPrice() * $item->getQty());?></td>
        	</tr>
        	<?php endforeach; ?>
        	<tr>
                <td colspan="2">&nbsp;</td>
        	    <th colspan="2" class="text-right">Postage:</th>
        	    <td><?=$this->priceFormat($this->order->getShipping());?></td>
        	</tr>
        	<tr>
                <td colspan="2">&nbsp;</td>
        	    <th colspan="2" class="text-right">Total:</th>
        	    <td><?=$this->priceFormat($this->order->getTotal());?></td>
        	</tr>
        </table>
        
        <table class="col-12 panel panel-default">
            <tr>
                <td class="panel-heading">
                    <h4 class="panel-title"> Requirements</h4>
                </td>                   
            </tr>
            <tr>
                <td class="panel-body">
                    <p><?=$this->escapeHtml($this->order->getMetaData()->getRequirements());?></p>
                </td>
            </tr>
        </table>
        
        <div class="footer">
            <p>
                Registered at Companies House, register number <?=$this->contact('company.number');?>.
            </p>
            <p>
                Registered office address:
                <?=$this->contact('company.address.line1');?>,
                <?php if($this->contact('company.address.line2') != ''):?>
                <?=$this->contact('company.address.line2');?>,
                <?php endif;?>
                <?=$this->contact('company.address.town');?>,
                <?=$this->contact('company.address.county');?>, <?=$this->contact('details.address.postcode');?>
            </p>
        </div>
    </body>
</html>
