<html>
    <head>
        <?=$this->headTitle($this->shopOption('merchantName') . ' - Order No. ' .$this->order->getOrderNumber()); ?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <?=$this->partial('shop/order/styles', [
            'print' => true,
        ]);?>
    </head>
    <body>
        <?=$this->partial('shop/order/table-view', [
            'order' => $this->order,
        ])?>

    </body>
</html>
