
<style type="text/css">
    body {
    	font-size: 12pt;
    }
    
    h4 {
    	font-weight: bold;
        line-height: 1.1;
    	font-size: 18px;
    }
    
    td, th {
    	vertical-align:top;
    }
    
    .col-12 {
    	width: 100%;
    }
    
    .col-6 {
    	width: 45%;
    }
    
    .panel {
    	margin-bottom: 20px;
    	background-color: #fff;
    	border: 1px solid transparent;
    	border-radius: 4px;
    	border-spacing: 0px;
    }
    
    .panel-body {
    	padding: 15px;
    }
    
    .panel-heading {
    	padding: 10px 15px;
    	border-bottom: 1px solid transparent;
    	border-top-left-radius: 3px;
    	border-top-right-radius: 3px;
    }
    
    .panel-title {
    	margin-top: 0;
    	margin-bottom: 0;
    	font-size: 16px;
    	color: inherit;
    }
    
    .panel-default {
    	border-color: #ddd;
    }
    
    .panel-default .panel-heading {
    	color: #333;
    	background-color: #f5f5f5;
    	border-color: #ddd;
    }
    
    .panel-default .panel-heading {
    	border-top-color: #ddd;
    }
    
    .address-heading, .address-body {
    	border: 1px solid #ddd;
    }
    
    .address-body {
    	border-top: none;
    	border-bottom-left-radius: 3px;
    	border-bottom-right-radius: 3px;
    }
    
    .panel .table {
    	margin-bottom: 0;
    }
    
    .table {
    	width: 100%;
    	max-width: 100%;
    	margin-bottom: 20px;
    	text-align: left;
    	border-spacing: 0;
        border-collapse: collapse;
    	padding: 0px;
    }
    
    .table th, .table td {
    	padding: 8px;
    	line-height: 1.42857143;
    	border: 1px solid #ddd !important;
    }
    
    .table tr:nth-child(odd) {
    	background-color: #f5f5f5;
    }
    
    .table .first-row th {
    	border-top: none;
    	text-align: left;
    }
    
    .text-right {
    	text-align: right;
    }
    
    .footer {
    	height: 30px;
    	font-size:10px;
    	text-align: center;
    }
</style>