
<style type="text/css">
    body {
    	font-size: <?=$this->invoiceOption('fontSize');?>;
    }
    
    td, th {
    	vertical-align:top;
    }
    
    .col-12 {
    	width: 100%;
    }
    
    .col-6 {
    	width: 50%;
    }

    .col-4 {
        width: 33.33333333%;
    }
    
    .panel {
    	margin-bottom: 10px;
    	background-color: #fff;
    	border: 1px solid transparent;
    	border-radius: 4px;
    	border-spacing: 0px;
    }
    
    .panel-body {
    	padding: 5px;
    }
    
    .panel-heading {
    	padding: 5px;
    	border-bottom: 1px solid transparent;
    	border-top-left-radius: 3px;
    	border-top-right-radius: 3px;
    }
    
    .panel-title {
        font-weight: bold;
    	margin-top: 0;
    	margin-bottom: 0;
    	font-size: <?=$this->invoiceOption('panelTitleFontSize');?>;
    	color: inherit;
    }
    
    .panel-default {
    	border-color: #ddd;
    }
    
    .panel-default .panel-heading {
    	color: #333;
    	background-color: #f5f5f5;
    	border-color: #ddd;
    }
    
    .panel-default .panel-heading {
    	border-top-color: #ddd;
    }
    
    .address-heading, .address-body {
    	border: 1px solid #ddd;
    }
    
    .address-body {
    	border-top: none;
    	border-bottom-left-radius: 3px;
    	border-bottom-right-radius: 3px;
    }

    .spacer-row {
        width: 10px;
    }
    
    .panel .table {
    	margin-bottom: 0;
    }
    
    .table {
    	width: 100%;
    	max-width: 100%;
    	margin-bottom: 10px;
    	text-align: left;
    	border-spacing: 0;
        border-collapse: collapse;
    	padding: 0px;
    }
    
    .table th, .table td {
    	padding: 4px;
    	border: 1px solid #ddd !important;
    }
    
    .table tr:nth-child(odd) {
    	background-color: #f5f5f5;
    }
    
    .table .first-row th {
    	border-top: none;
    	text-align: left;
    }

    .table .item-list td {
        page-break-before: always;
    }
    
    .text-right {
    	text-align: right;
    }
    
    .page-footer {
        width: 100%;
    	font-size: <?=$this->invoiceOption('footerFontSize');?>;
    	text-align: center;
    }

    .page-footer .company-details p {
        margin: 2px;
    }

    <?php if ($this->print): ?>
    .page-footer {
        display: none;
    }

    @page{
        margin: 0.2in 0.5in 0.2in 0.5in;
    }
    <?php endif; ?>
</style>