<table class="col-12">
    <tr>
        <td class="col-6">
            <img src="<?=APPLICATION_PATH . '/public' . $this->themeOptions('logo');?>" height="50" alt="logo">
            <img src="<?=APPLICATION_PATH . '/public' . $this->themeOptions('logo2');?>" height="50" alt="logo" >
        </td>
        <td class="col-6 text-right">
            <?=$this->contact('details.address.line1');?><br />
            <?php if($this->contact('details.address.line2') != ''):?>
            <?=$this->contact('details.address.line2');?>,<br />
            <?php endif;?>
            <?=$this->contact('details.address.town');?>,<br />
            <?=$this->contact('details.address.county');?>, <?=$this->contact('details.address.postcode');?><br />
            <?=$this->contact('details.phone');?><br />
            <?=$this->contact('details.email');?>
        </td>
    </tr>
</table>

<table class="col-12 panel panel-default">
    <tr>
        <td class="panel-heading" colspan="3">
            <h4 class="panel-title"> Order Details</h4>
        </td>                   
    </tr>
    <tr>
        <td class="col-6 panel-body">
            Order No:&nbsp;<span><?=$this->escapeHtml($this->order->getOrderNumber());?></span><br>
            Customer No:&nbsp;<span><?=$this->escapeHtml($this->order->getCustomer()->getNumber());?></span><br>
            Date Ordered:&nbsp;<span><?=$this->formatDate($this->order->getOrderDate())->setFormat('d/m/Y');?></span>
        </td>
        <td>&nbsp;</td>
        <td class="col-6 panel-body">
            Status: <span><?=$this->escapeHtml($this->order->getOrderStatus()->getOrderStatus());?></span><br>
            Payment Method: <span><?=$this->escapeHtml($this->order->getMetaData()->getPaymentMethod());?></span><br>
            Shipping Method: <span><?=$this->escapeHtml($this->order->getMetaData()->getShippingMethod());?></span>
        </td>
    </tr>
</table>

<table class="col-12 panel address">
    <tr class="panel panel-default">
        <td class="col-6 panel-heading address-heading">
            <h4 class="panel-title"> Billing Address</h4>
        </td>                 
        <td>&nbsp;</td>  
        <td class="col-6 panel-heading address-heading">
            <h4 class="panel-title"> Delivery Address</h4>
        </td>                     
    </tr>
    <tr class="panel panel-default">
        <td class="panel-body address-body">
           <address>
                <?=$this->customerAddress()
                    ->setOrder($this->order)
                    ->includeName()
                    ->includeEmail()
                    ->formatAddress(
                        $this->order->getMetadata()
                            ->getBillingAddress()
                );?>
            </address>
        </td>
        <td>&nbsp;</td>
        <td class="panel-body address-body">
           <address>
                <?=$this->customerAddress()
                    ->setOrder($this->order)
                    ->includeName()
                    ->formatAddress(
                        $this->order->getMetadata()
                            ->getBillingAddress()
                );?>
            </address>
        </td>
    </tr>
</table>

<table class="col-12 panel table">
    <tr class="first-row">
		<th>Product</th>
		<th>Description</th>
		<th>Price</th>
		<th>Quantity</th>
		<th>Total</th>
	</tr>
	
	<?php /* @var $item \Shop\Model\Order\Line */ ?>
	<?php foreach ($this->order->getOrderlines() as $item): ?>
	<tr>
		<td><?=$item->getMetadata()->getSku();?></td>
		<td>
		  <?=$item->getMetadata()->getCategory();?> / <?=$item->getMetadata()->getName();?>
		  <?php if ($item->getMetadata()->getPostUnit() > 0): ?><br />
          &nbsp;(<?=$item->getMetadata()->getPostUnit();?> grams)
          <?php endif; ?>
	    </td>
		<td><?=$this->priceFormat($item->getPrice());?></td>
		<td><?=$item->getQty();?></td>
		<td><?=$this->priceFormat($item->getPrice() * $item->getQty());?></td>
	</tr>
	<?php endforeach; ?>
	<tr>
        <td colspan="2">&nbsp;</td>
	    <th colspan="2" class="text-right">Postage:</th>
	    <td><?=$this->priceFormat($this->order->getShipping());?></td>
	</tr>
	<tr>
        <td colspan="2">&nbsp;</td>
	    <th colspan="2" class="text-right">Total:</th>
	    <td><?=$this->priceFormat($this->order->getTotal());?></td>
	</tr>
</table>

<table class="col-12 panel panel-default">
    <tr>
        <td class="panel-heading">
            <h4 class="panel-title"> Requirements</h4>
        </td>                   
    </tr>
    <tr>
        <td class="panel-body">
            <p><?=$this->escapeHtml($this->order->getMetaData()->getRequirements());?></p>
        </td>
    </tr>
</table>

<div class="footer">
    <p>
        Registered at Companies House, register number <?=$this->contact('company.number');?>.
    </p>
    <p>
        Registered office address:
        <?=$this->contact('company.address.line1');?>,
        <?php if($this->contact('company.address.line2') != ''):?>
        <?=$this->contact('company.address.line2');?>,
        <?php endif;?>
        <?=$this->contact('company.address.town');?>,
        <?=$this->contact('company.address.county');?>, <?=$this->contact('details.address.postcode');?>
    </p>
</div>
    