<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'newsletter/message/add'                    => __DIR__ . '/view/newsletter/message/add.phtml',
    'newsletter/message/edit'                   => __DIR__ . '/view/newsletter/message/edit.phtml',
    'newsletter/message/index'                  => __DIR__ . '/view/newsletter/message/index.phtml',
    'newsletter/message/list'                   => __DIR__ . '/view/newsletter/message/list.phtml',
    'newsletter/newsletter/add'                 => __DIR__ . '/view/newsletter/newsletter/add.phtml',
    'newsletter/newsletter/edit'                => __DIR__ . '/view/newsletter/newsletter/edit.phtml',
    'newsletter/newsletter/index'               => __DIR__ . '/view/newsletter/newsletter/index.phtml',
    'newsletter/newsletter/list'                => __DIR__ . '/view/newsletter/newsletter/list.phtml',
    'newsletter/preferences/index'              => __DIR__ . '/view/newsletter/preferences/index.phtml',
    'newsletter/subscriber/add-subscriber'      => __DIR__ . '/view/newsletter/subscriber/add-subscriber.phtml',
    'newsletter/subscriber/error'               => __DIR__ . '/view/newsletter/subscriber/error.phtml',
    'newsletter/subscriber/update-subscription' => __DIR__ . '/view/newsletter/subscriber/update-subscription.phtml',
    'newsletter/subscriber-admin/add'           => __DIR__ . '/view/newsletter/subscriber-admin/add.phtml',
    'newsletter/subscriber-admin/edit'          => __DIR__ . '/view/newsletter/subscriber-admin/edit.phtml',
    'newsletter/subscriber-admin/index'         => __DIR__ . '/view/newsletter/subscriber-admin/index.phtml',
    'newsletter/subscriber-admin/list'          => __DIR__ . '/view/newsletter/subscriber-admin/list.phtml',
    'newsletter/template/add'                   => __DIR__ . '/view/newsletter/template/add.phtml',
    'newsletter/template/edit'                  => __DIR__ . '/view/newsletter/template/edit.phtml',
    'newsletter/template/index'                 => __DIR__ . '/view/newsletter/template/index.phtml',
    'newsletter/template/list'                  => __DIR__ . '/view/newsletter/template/list.phtml',
);
