
<!-- NEW PRODUCTS -->

<h2 class="owl-featured"><?=$this->newProductsCarouselOption()->formatTitle();?></h2>

<div class="owl-carousel featured" data-plugin-options='{"items" : <?=$this->newProductsCarouselOption('numberItemsToDisplay');?>, "singleItem": false, "stopOnHover":true, "autoPlay":<?=($this->newProductsCarouselOption('autoPlay')) ? 'true' : 'false';?>, "autoHeight": false, "navigation": true, "pagination": false}'>
    <?php foreach ($this->productHelper()->getLatestProducts($this->newProductsCarouselOption('totalItems')) as $row):?>
        <div>
            <div class="shop-item-list"><!-- item -->
                <a href="<?=$this->url('shop/catalog/product', [
                    'categoryIdent' => $row->getProductCategory()->getIdent(),
                    'productIdent' => $row->getIdent(),
                ]);?>">
                    <?php if ($row->getShowImage()):?>
                        <figure><!-- image -->
                            <img class="img-responsive" src="<?=$this->productImage($row, 'thumb');?>" alt="" />
                        </figure><!-- /image -->
                    <?php endif;?>
                    <?php if ($row->inStock() && $row->isEnabled()) : ?>
                        <span class="shop-stock-info stock-yes"><!-- stock -->
                <span class="text-muted"><?=$this->escapehtml($row->getSku());?></span>
                <i class="fa fa-check"></i>
                <span class="text-muted">
                    <?=($row->getQuantity() > 0) ? $this->escapeHtml($row->getQuantity()) :'';?>
                </span> in stock
            </span><!-- /stock -->
                    <?php else: ?>
                        <span class="shop-stock-info stock-no"><!-- stock -->
                <span class="text-muted"><?=$this->escapehtml($row->getSku());?></span>
                <i class="fa fa-times"></i> out of stock
            </span><!-- /stock -->
                    <?php endif; ?>
                    <div class="product-info"><!-- title and price -->
                        <h2>
                    <span class="product-name">
                        <span><?=$this->escapeHtml($row->getProductCategory()->getCategory());?>&nbsp;
                            <?=$this->escapeHtml($row->getSku());?>&nbsp;
                            <?=$this->escapeHtml($row->getName());?></span><br>
                        Size:<?=$this->escapeHtml($row->getProductSize()->getSize());?>
                    </span>
                            <span>
                        <?=$this->productPrice($row)
                            ->setFormat('<span class="bold">%s</span> %s %s ')
                            ->setDiscountFormat(' was <span class="line-through">%s</span>'); ?>
                    </span>
                        </h2>
                    </div><!-- /title and price -->
                </a>

                <?php $form = $this->cart()->addForm($row)->setAttribute('class', 'margin-top10 nopadding clearfix'); ?>

                <?php if ($row->inStock() && $row->isEnabled()):?>
                    <?=$this->form()->openTag($form); ?>
                    <?=$this->formHidden($form->get('productId')); ?>
                    <?=$this->formHidden($form->get('returnTo')); ?>

                    <?php if ($row->getProductOption()): ?>
                        <div class="row">
                            <div class="col-md-12">
                                <?=$this->productOptions($row);?>
                            </div><!-- /btn-group -->
                        </div>
                    <?php endif; ?>

                    <?=$this->formInput($form->get('qty')->setAttribute('class', 'form-control')); ?>

                    <button type="submit" name="buy-item" class="btn btn-primary col-sm-12 col-md-12">
                        ADD TO CART <i class="fa fa-shopping-cart"></i>
                        <?=$this->cart()->hasProductInCart($row);?>
                    </button>

                    <?=$this->form()->closeTag(); ?>
                <?php endif; ?>
            </div><!-- /item -->
        </div>
    <?php endforeach; ?>
</div>
<!-- /NEW PRODUCTS -->
