
<?php
$previous = $this->productHelper()->getPrevious($this->model->getProductId());
$next = $this->productHelper()->getNext($this->model->getProductId());
?>

<?php $this->headTitle('Edit Product') ?>
<?php $this->layout()->pageTitle = $this->translate('Edit Product');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-product" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/shop/product');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-product',
    'action' => $this->url('admin/shop/product/edit', [
        'id' => $this->model->getProductId(),
    ]),
]); ?>

<div id="product-edit" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Edit Product');?></h3>
    </div>
    <div class="panel-body">
        <ul class="pager">
            <li class="previous<?php if (!$previous) echo " disabled"; ?>">
                <a href="<?=$this->url('admin/shop/product/edit', [
                    'id' => (!$previous) ? '' : $previous->getProductId()
                ]);?>">&larr; Previous</a>
            </li>
            <li class="next<?php if (!$next) echo " disabled"; ?>">
                <a href="<?=$this->url('admin/shop/product/edit', [
                    'id' => (!$next) ? '' : $next->getProductId()
                ]);?>">Next &rarr;</a>
            </li>
        </ul>
        <!-- Nav tabs -->
        <ul class="nav nav-tabs">
            <li class="active"><a href="#product" data-toggle="tab">Product</a></li>
            <li><a href="#product-option" data-toggle="tab">Options</a></li>
            <li><a href="#product-image" data-toggle="tab">Images</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="product">
                <div class="clearfix">&nbsp;</div>
                <?=$this->form($this->form);?>
            </div>

            <div class="tab-pane" id="product-option">
                <div class="clearfix">&nbsp;</div>
                <a href="<?=$this->url('admin/shop/product/option', [
                    'action'    => 'add',
                    'id'        => $this->model->getProductId(),
                ]);?>" id="add-product-option-button" class="btn btn-default">
                    Add Product Option
                </a>
                <div class="clearfix">&nbsp;</div>
                <div class="product-option-list">
                    <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading
                </div>

            </div>

            <div class="tab-pane" id="product-image">
                <div class="clearfix">&nbsp;</div>
                <a href="<?=$this->url('admin/uploader', [
                    'action'    => 'upload-form',
                ]);?>" id="add-product-image-button" class="btn btn-default">
                    Add Product Image
                </a>
                <div class="clearfix">&nbsp;</div>
                <div class="product-image-list">
                    <i class="fa fa-spinner fa-spin"></i>&nbsp;Loading
                </div>
            </div>
        </div>
    </div>
</div>

<?php $this->inlineScript()
    ->appendFile($this->basePath('js/admin/shop/products-edit.js'));?>

<script>
    $(document).ready(function() {
        product.productId = <?=$this->model->getProductId();?>;
    });
</script>
