

<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'product',
	'searchInputs'	=> [
		'Product'	=> 'sku-name-shortDescription',
		'Category'	=> 'category',
	    'Category List' => $this->formManager('ProductCategoryList')->setName('productCategoryId'),
	],
	'params' 		=> $this->params,
]);?>

<div id="table-product">
	<?=$this->partial('shop/product/list', [
	    'models' => $this->models,
	]); ?>
</div>


<script>

	$('#table-product').dataGrid({
	    url : 'product/list',
	    query: { sort : '<?=(isset($this->params['sort'])) ? $this->params['sort'] : 'sku';?>' },
	    searchForm : $('#search-product'),
	    columnSort: true
	});

</script>