
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'product',
	'searchInputs'	=> [
		'Product'	=> 'name-shortDescription',
		'Category'	=> 'category',
	],
]);?>

<div id="table-product">
	<?=$this->partial('shop/product/list', [
	    'models' => $this->models
	]); ?>
</div>


<script>

	$('#table-product').dataGrid({
	    url : 'product/list',
	    query: { sort : 'name' },
	    searchForm : $('#search-product'),
	    columnSort: true
	});

</script>