<?php $this->headTitle('Products') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->products) > 0): ?>

<table class="table table-hover table-bordered table-condensed">
	<thead>
		<tr>
			<th data-field="productId">Product Id</th>
			<th data-field="name">Name</th>
			<th data-field="description">Description</th>
			<th data-field="category">Category</th>
			<th data-field="dateCreated">Date Created</th>
			<th data-field="dateModified">Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach($this->products as $row): ?>
		
		<tr>
			<td><?=$this->escapeHtml($row->getProductId()); ?></td>
			<td><?=$this->escapeHtml($row->getName()); ?></td>
			<td><?=$this->escapeHtml($row->getShortDescription()); ?></td>
			<td><?=$this->escapeHtml($row->getCategory()); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate($row->getDateCreated())); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate($row->getDateModified())); ?></td>
			<td></td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>


<?=$this->paginationControl(
    $this->products,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/product/page')
); ?>

<?php else: ?>
<h4>No Products where returned by search.</h4>
<?php endif; ?>