<?php $this->headTitle('Products') ?>


<?php if (count($this->models) > 0): ?>
<div class="panel panel-default">
    <table id="product-list" class="table table-hover table-bordered table-condensed sortable-table">
        <thead>
            <tr>
                <th data-field="enabled">&nbsp;</th>
                <th data-field="productId">Product Id</th>
                <th data-field="name">Name</th>
                <th data-field="description">Description</th>
                <th data-field="price">Price</th>
                <th data-field="group">Group</th>
                <th data-field="category">Category</th>
                <th style="width:190px;">Actions</th>
            </tr>
        </thead>

        <tbody>
            <?php /* @var $row \Shop\Model\Product\Product */ ?>
            <?php foreach($this->models as $row): ?>
            <tr>
                <td><?=$this->enabled($row, [
                    'table' => 'product',
                    'route' => 'admin/shop/product/edit',
                ]); ?></td>
                <td><?=$this->escapeHtml($row->getProductId()); ?></td>
                <td><?=$this->escapeHtml($row->getName()); ?></td>
                <td><?=$this->escapeHtml($row->getShortDescription()); ?></td>
                <td><?=$this->priceFormat($row->getPrice(false)); ?>
                <td><?=$this->escapeHtml($row->getProductGroup()->getGroup()); ?>
                <td><?=$this->escapeHtml($row->getProductCategory()->getCategory()); ?></td>
                <td width="140">
                    <a href="<?=$this->url('admin/shop/product/edit', [
                        'action' => 'duplicate',
                        'id'     => $row->getProductId(),
                    ]);?>" class="btn btn-primary btn-sm">Duplicate</a>
                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                        'pk'		=> 'productId',
                        'id'		=> $row->getProductId(),
                        'tableName'	=> 'product',
                        'route'		=> 'admin/shop/product/edit',
                        'buttonSize'    => 'btn-sm',
                    ]);?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
    ['route' => 'admin/shop/product/page']
); ?>

<?php else: ?>
<h4>No Products where returned by search.</h4>
<?php endif; ?>

