
<div id="scrollable-typeahead-menu">
    <div class="input-group">
        <input type="text" class="form-control typeahead" placeholder="Type Search here...">
        <span class="input-group-btn">
            <button id="add-product-button" class="btn btn-default" type="button" data-toggle="tooltip" title="<?=$this->translate('Get product');?>">
                <span class="fa fa-check"></span>
            </button>
        </span>
    </div>
</div>