
<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('layout/page-title', [
    'pageTitle' => 'Commendations'
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<div class="row">
    <div class="col-md-3 col-sm-3">
        <?=$this->partial('shop/product-nav');?>
	</div>
	
	<div class="col-md-9 col-sm-9">
        <?php /* @var $row \UthandoTestimonial\Model\Testimonial */ ?>
        <?php $c=0;?>
        <?php foreach($this->models as $row):?>
        <?php $c++;?>
    	<div class="col-md-4">
    		<div class="testimonial classic female">
    			<?=$row->getText()?>
    			<cite><strong><?=$row->getName();?></strong>
    			<?php if ($row->getLocation()):?>
    			, <?=$row->getLocation();?>
    			<?php endif;?>
    			</cite>
    		</div>
    	</div>
    	<?php if (($c % 3) === 0):?>
    	<div class="clearfix"></div>
    	<?php endif; ?>
    	<?php endforeach; ?>
	</div>
</div>