
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'productSize',
	'searchInputs'	=> [
		'Size' => 'size',
	],
]);?>

<div id="table-productSize">
	<?=$this->partial('shop/product-size/list', [
	    'models' => $this->models
	]); ?>
</div>


<script>
$(document).ready(function(){
	$('#table-productSize').dataGrid({
	    url : '<?=$this->url('admin/shop/product/size/edit', ['action' => 'list']);?>',
	    query: { sort : 'productSizeId' },
	    searchForm : $('#search-productSize'),
	    paging : 'links',
	    columnSort: true
	});
});
</script>
