
<?php $this->placeholder('page-top')->captureStart();?>
<!-- REVOLUTION SLIDER -->
<div class="slider fullwidthbanner-container roundedcorners">
    <div class="fullwidthbanner">
        <ul class="hide">

            <!-- SLIDE  -->
            <li data-transition="fade" data-slotamount="7" data-masterspeed="300" data-saveperformance="off" >

                <img src="<?=$this->themePath('/assets/images/1x1.png');?>" data-lazyload="<?=$this->basePath('/userfiles/bead-museum.jpg');?>" alt="" data-bgfit="cover" data-bgposition="center center" data-bgrepeat="no-repeat" />

                <div class="tp-caption block_black sfl tp-resizeme"
                     data-x="70"
                     data-y="172"
                     data-speed="750"
                     data-start="1000"
                     data-easing="easeOutExpo"
                     data-splitin="none"
                     data-splitout="none"
                     data-elementdelay="0.1"
                     data-endelementdelay="0.1"
                     data-endspeed="300">Enjoy A Relaxed Shopping Experience
                </div>

                <div class="tp-caption block_black sfl tp-resizeme"
                     data-x="70"
                     data-y="216"
                     data-speed="750"
                     data-start="1400"
                     data-easing="easeOutExpo"
                     data-splitin="none"
                     data-splitout="none"
                     data-elementdelay="0.1"
                     data-endelementdelay="0.1"
                     data-endspeed="300">Take Time To Make Your Choices
                </div>

            </li>

            <!-- SLIDE  -->
            <li data-transition="fade" data-slotamount="14"  data-masterspeed="300" data-delay="10000">

                <!-- COVER IMAGE -->
                <img src="<?=$this->themePath('/assets/images/1x1.png');?>" data-lazyload="<?=$this->basePath('/userfiles/shop-area.jpg');?>" alt="" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat" />

                <div class="tp-caption block_black sfl tp-resizeme"
                     data-x="70"
                     data-y="216"
                     data-speed="750"
                     data-start="1900"
                     data-easing="easeOutExpo"
                     data-splitin="none"
                     data-splitout="none"
                     data-elementdelay="0.1"
                     data-endelementdelay="0.1"
                     data-endspeed="300">We Stock 1000s of Miyuki Beads
                </div>

                <div class="tp-caption block_black sfr tp-resizeme"
                     data-x="70"
                     data-y="260"
                     data-speed="750"
                     data-start="2200"
                     data-easing="easeOutExpo"
                     data-splitin="none"
                     data-splitout="none"
                     data-elementdelay="0.1"
                     data-endelementdelay="0.1"
                     data-endspeed="300">Specialist Miyuki Bead Stockist
                </div>

            </li>

        </ul>
        <div class="tp-bannertimer"></div>
    </div>
</div>
<!-- /REVOLUTION SLIDER -->
<?php $this->placeholder('page-top')->captureEnd();?>

<?php
$post = $this->uthandoArticleGetPost('home-page');
$this->headTitle($this->escapehtml($post->getTitle()));
?>

<?=$this->partial('shop/catalog/new-products-carousel');?>

<div id="blog" class="row">

    <!-- BLOG SIDEBAR -->
    <div class="col-md-3 col-sm-3">
        <?=$this->partial('shop/product-nav');?>
    </div>
    <!-- /BLOG SIDEBAR -->


    <div class="col-md-9 col-sm-9">

        <!-- BLOG ARTICLE -->
        <div class="row">

            <!-- article content -->
            <article>
                <?=$post->getContent();?>
            </article>

            <div class="divider"><!-- divider -->
                <i class="fa fa-angle-double-down"></i>
            </div>

        </div><!-- /BLOG ARTICLE -->

        <!-- PRODUCT CATEGORIES -->
        <div class="row">
            <?php /* @var $row \Shop\Model\Product\Category */ ?>
            <?php $c=0;?>
            <?php foreach ($this->Category()->getTopCategories() as $row): ?>
                <?php $c++;?>
                <div class="col-sm-4 col-md-4"><!-- category -->
                    <div class="box-content thumbnail text-center">
                        <a href="<?php echo $this->url('shop/catalog', [
                            'categoryIdent' => $row->getIdent()
                        ]); ?>" class="item-image"><!-- image -->
                            <?php if ($row->getShowImage()):?>
                                <img class="img-responsive" src="<?=$this->productCategoryImage($row);?>" alt="<?=$this->escapehtml($row->getCategory());?>">
                            <?php endif;?>
                        </a>
                        <div class="caption text-left"><!-- name -->
                            <h5 class="nomargin elipsis"><?=$this->escapehtml($row->getCategory());?></h5>
                        </div>
                    </div>
                </div><!-- /category -->
                <?php if (($c % 3) === 0):?>
                    <div class="clearfix"></div>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>

    </div>


</div>
