
<div>
    <p>
        Dear <?=$this->escapeHtml($this->data['name']);?>,
    </p>

    <p>
        We thank you for your enquiry and we will get back to you as soon as possible.
    </p>
    <p>
        <?=$this->escapeHtml($this->contact('details.name'));?>
    </p>
</div>

<div style="font-size: 10px; text-align: center;">
    Registered at Companies House, register number <?=$this->contact('company.number');?>.<br>
    Registered office address:
    <?=$this->contact()->formatAddress('company.address');?>
</div>

<div>
    <p>
        Here is a copy of your enquiry, for your records:
    </p>

    <p>
        <?=$this->escapeHtml($this->data['body']);?>
    </p>
</div>
