<?php $this->headTitle('Checkout - Comfirm Address') ?>

<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('shop/parallax', [
    'title' => 'Confirm Address', 
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<div class="col-md-9 checkout">

    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Billing Address
                </h4>
            </div>
            <div class="panel-body">
                <address>
                    <?=$this->customerAddress()
                        ->setCustomer($this->customer)
                        ->setAddress('billing')
                        ->includeName()
                        ->includeEmail()
                        ->render();?>
                </address>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Delivery Address
                </h4>
            </div>
            <div class="panel-body">
                <address>
                    <?=$this->customerAddress()
                        ->setCustomer($this->customer)
                        ->setAddress('delivery')
                        ->includeName()
                        ->render();?>
                    <br>
                </address>
            </div>
        </div>
    </div>
    
    <form class="col-md-12" method="post" action="<?=$this->url('shop/checkout', [
        'action' => 'confirm-address',
    ]) ?>">
        <a href="<?=$this->url('shop/checkout', [
            'action' => 'customer-details',
        ]);?>" class="btn btn-info">Change Details</a>
        <button type="submit" name="submit" class="btn btn-primary" value="confirmAddress">
            <i class="fa fa-check"></i>Check &amp; Confirm Order
        </button>
    </form>

</div>

<div class="col-md-3">

    <!-- cart totals -->
    <div class="sky-form boxed cartContent">
        <header class="styleColor">Cart Totals</header>

        <fieldset>

            <section class="clearfix cart_totals">
                <span class="pull-right fsize16"><?=$this->cart()->getSubTotal();?></span>
                <span class="bold">Cart Subtotal</span>
            </section>

            <section class="clearfix cart_totals">
                <span class="pull-right fsize16"><?=$this->cart()->getShippingTotal(
                        $this->customer->getDeliveryAddress()
                            ->getCountryId()
                );?></span>
                <span class="bold">Shipping</span>
            </section>

            <?php if ($this->shopOption('vatState')): ?>
                <section class="clearfix cart_totals">
                    <span class="pull-right fsize16"><?=$this->cart()->getTaxTotal();?></span>
                    <span class="bold">VAT</span>
                </section>
            <?php endif;?>

            <section class="clearfix cart_totals">
                <span class="pull-right fsize16"><?=$this->cart()->getDiscount();?></span>
                <span class="bold">Coupon Discount</span>
            </section>

            <section class="clearfix cart_totals noborder">
                <span class="pull-right fsize20 bold styleColor"><?=$this->cart()->getTotal();?></span>
                <span class="bold fsize18">ORDER TOTAL</span>
            </section>

        </fieldset>

    </div>
    <!-- /cart totals -->
</div>
