<!DOCTYPE html>
<html>
    <head>
        <?=$this->headTitle($this->contact('details.name'))->setSeparator(' - ');?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    </head>

    <body>
        <div style="text-align: center;">
            <img src="<?=APPLICATION_PATH . '/public' . $this->themeOptions('logo');?>" height="50" alt="logo">
            <img src="<?=APPLICATION_PATH . '/public' . $this->themeOptions('logo2');?>" height="50" alt="logo" >
        </div>
        <?=$this->content;?>
    </body>
</html>
