<?php $this->headTitle('Add Voucher') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Voucher'); ?>

<?php $this->placeholder('header-buttons')->captureStart(); ?>
    <button type="submit" form="form-voucher" data-toggle="tooltip" title="<?= $this->translate('Save'); ?>"
            class="btn btn-primary">
        <i class="fa fa-save"></i>
    </button>
    <a href="<?= $this->url('admin/shop/voucher'); ?>" data-toggle="tooltip" title="<?= $this->translate('Cancel'); ?>"
       class="btn btn-default">
        <i class="fa fa-reply"></i>
    </a>
<?php $this->placeholder('header-buttons')->captureEnd(); ?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-voucher',
    'action' => $this->url('admin/shop/voucher/edit', [
        'action' => 'add',
    ]),
    'class' => 'col-sm-12',
]); ?>

<div id="tax-rate-edit" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?= $this->translate('Add Voucher'); ?></h3>
    </div>
    <div class="panel-body">
        <?= $this->form($this->form); ?>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        /*$('.date-time-pick .input-group').datetimepicker({
            format : 'DD/MM/YYYY'
        });*/
    });
</script>
