<?php
$form = $this->form;
$routeArray = array('action' => $this->formAction);
if (isset($this->articleId)) $routeArray['id'] = $this->articleId;

?>
<div>
    <form class="form form-horizontal"  method="post" action="<?php echo $this->url('admin/article', $routeArray) ?>">
        <fieldset>
        <legend><?php echo ucwords($this->formAction); ?> Article Form:</legend>
        <div class="row-fluid">
            <div class="span6">
                <fieldset>
           	        <legend>Article Details</legend>
                    <?php echo $this->ztbFormElement($form->get('title')); ?>
                    
                    <?php echo $this->ztbFormElement($form->get('slug')); ?>
                    
                    <?php echo $this->ztbFormElement($form->get('keywords')); ?>
                    
                    <?php echo $this->ztbFormElement($form->get('description')); ?>
                </fieldset>
           	</div>
            
            <div class="span6">
                <fieldset>
           	        <legend>Menu</legend>
           	        
                    <?php echo $this->navigationForm(); ?>
           	        <div class="control-group">
                        <div class="controls">
                             <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType1" value="noInsert" checked >
                                do not add to menu/no change.
                            </label>
                       	    <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType2" value="insert">
                                insert after this page.
                            </label>
                            <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType3" value="insertSub">
                                insert as a subpage of this page.
                            </label>
                        </div>
                    </div>
                </div>
                </fieldset>
           	</div>
        </div>
        
        <div class="row-fluid">
                <div class="span12">
                <fieldset>
                    <legend>HTML Content</legend>
                    <?php echo $this->formElement($form->get('content')); ?>
                </fieldset>
            </div>
        </div>
                
        <?php echo $this->formElement($form->get('articleId')); ?>
        <?php echo $this->formElement($form->get('pageHits')); ?>
        <input type="hidden" name="action" value="<?php echo $this->formAction; ?>">
        
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary" 
                data-loading-text="Please wait...">Submit</button>
                <button type="button" class="btn btn-warning" 
                data-loading-text="Please wait..." onClick="window.location = '<?php echo $this->url('admin/article', array(
                        'action' => 'list',
                    )) ?>';">Cancel</button>
            </div>
        </div>
        </fieldset>
    </form>
</div>

<script type="text/javascript">
<!--
$(document).ready(function(){
	$('#article-content-textarea').liveEdit({
	    height: 350,
	    css: ['<?php echo $this->basePath(); ?>/css/bootstrap.min.css', '<?php echo $this->basePath(); ?>/css/bootstrap-extend.css'] /* Apply bootstrap css into the editing area */,
	    groups: [
	        ["group1", "", ["Bold", "Italic", "Underline", "ForeColor", "RemoveFormat"]],
	        ["group2", "", ["Bullets", "Numbering", "Indent", "Outdent"]],
	        ["group3", "", ["Paragraph", "FontSize", "FontDialog", "TextDialog"]],
	        ["group4", "", ["LinkDialog", "ImageDialog", "TableDialog", "Emoticons", "Snippets"]],
	        ["group5", "", ["Undo", "Redo", "FullScreen", "SourceDialog"]]
	    ] /* Toolbar configuration */
	});
	
	$('#article-content-textarea').data('liveEdit').startedit();
});
//-->
</script>
