<?php $this->headTitle('Articles') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->articles) > 0): ?>
<table class="table table-hover table-bordered table-condensed">
	<thead>
		<tr>
			<th data-field="articleId">Article Id</th>
			<th data-field="title">Title</th>
			<th data-field="slug">Slug</th>
			<th data-field="pageHits">Page Hits</th>
			<th data-field="dateCreated">Date Created</th>
			<th data-field="dateModified">Date Modified</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->articles as $row): ?>
		<tr>
			<td><?php echo $this->escapeHtml($row->articleId); ?></td>
			<td><?php echo $this->escapeHtml($row->title); ?></td>
			<td><?php echo $this->escapeHtml($row->slug); ?></td>
			<td><?php echo $this->escapeHtml($row->pageHits); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate($row->dateCreated)); ?></td>
			<td><?php echo $this->escapeHtml($this->formatDate($row->dateModified)); ?></td>
			<td>
				<a href="<?php echo $this->basepath(
					'/admin/article/edit/id/' . $this->escapeHtml($row->articleId)
				) ?>" role="button" class="btn">Edit</a>
				&nbsp;
				
				<!-- Button to trigger modal -->
                <a href="#articleModel<?php echo $row->articleId; ?>" role="button" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="articleModel<?php echo $row->articleId; ?>" tabindex="-1" role="dialog" aria-labelledby="articleModel<?php echo $row->articleId; ?>" aria-hidden="true">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				    <h3 id="articleModel<?php echo $row->articleId; ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?php echo $this->url('admin/article', array(
				        'action' => 'delete',
				    )) ?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this article.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="articleId" value="<?php echo $row->articleId ?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php else: ?>
<h4>There are no articles yet.</h4>
<?php endif; ?>

