<?php

return [
    'invokables' => [
        'ShopCartAdd'           => 'Shop\Form\Cart\Add',
        'ShopCatalogSearch'     => 'Shop\Form\Catalog\Search',
        'ShopCountry'           => 'Shop\Form\Country\Country',
        'ShopCountryProvince'   => 'Shop\Form\Country\Province',
        'ShopCustomer'          => 'Shop\Form\Customer\Customer',
        'ShopCustomerAddress'   => 'Shop\Form\Customer\Address',
        'ShopOrder'             => 'Shop\Form\Order\Order',
        'ShopOrderConfirm'      => 'Shop\Form\Order\Confirm',
        'ShopOrderLine'         => 'Shop\Form\Order\Line',
        'ShopOrderStatus'       => 'Shop\Form\Order\Status',
        'ShopPaymentCreditCard' => 'Shop\Form\Payment\CreditCard',
        'ShopPostCost'          => 'Shop\Form\Post\Cost',
        'ShopPostLevel'         => 'Shop\Form\Post\Level',
        'ShopPostUnit'          => 'Shop\Form\Post\Unit',
        'ShopPostZone'          => 'Shop\Form\Post\Zone',
        'ShopProduct'           => 'Shop\Form\Product\Product',
        'ShopProductCategory'   => 'Shop\Form\Product\Category',
        'ShopProductGroup'      => 'Shop\Form\Product\Group',
        'ShopProductImage'      => 'Shop\Form\Product\Image',
        'ShopProductOption'     => 'Shop\Form\Product\Option',
        'ShopProductSize'       => 'Shop\Form\Product\Size',
        'ShopTaxCode'           => 'Shop\Form\Tax\Code',
        'ShopTaxRate'           => 'Shop\Form\Tax\Rate',

        'CountryList'           => 'Shop\Form\Element\CountryList',
        'CountryProvinceList'   => 'Shop\Form\Element\CountryProvinceList',
        'CustomerAddressList'   => 'Shop\Form\Element\CustomerAddressList',
        'CustomerPrefixList'    => 'Shop\Form\Element\CustomerPrefixList',
        'OrderStatusList'       => 'Shop\Form\Element\OrderStatusList',
        'PayOptionsList'        => 'Shop\Form\Element\PayOptionsList',
        'PostLevelList'         => 'Shop\Form\Element\PostLevelList',
        'PostUnitList'          => 'Shop\Form\Element\PostUnitList',
        'PostZoneList'          => 'Shop\Form\Element\PostZoneList',
        'ProductCategoryList'   => 'Shop\Form\Element\ProductCategoryList',
        'ProductGroupList'      => 'Shop\Form\Element\ProductGroupList',
        'ProductOptionList'     => 'Shop\Form\Element\ProductOptionsList',
        'ProductSizeList'       => 'Shop\Form\Element\ProductSizeList',
        'TaxCodeList'           => 'Shop\Form\Element\TaxCodeList',
        'TaxRateList'           => 'Shop\Form\Element\TaxRateList',
    ],
];