<?php

namespace Shop;

return [
    'asset_manager' => [
        'resolver_configs' => [
            'collections' => [
                'css/admin.css' => [
                    'css/shop.css',
                    'css/typeaheadjs.css',
                ],
            ],
            'paths' => [
                'Shop' => __DIR__ . '/../public',
            ],
        ],
    ],
    'controllers' => [
        'invokables' => [
            Controller\AdvertController::class                => Controller\AdvertController::class,
            Controller\CartController::class                  => Controller\CartController::class,
            Controller\CatalogController::class               => Controller\CatalogController::class,
            Controller\CheckoutController::class              => Controller\CheckoutController::class,
            Controller\ConsoleController::class               => Controller\ConsoleController::class,
            Controller\CountryController::class               => Controller\CountryController::class,
            Controller\CountryProvinceController::class       => Controller\CountryProvinceController::class,
            Controller\CreateOrderController::class           => Controller\CreateOrderController::class,
            Controller\CustomerController::class              => Controller\CustomerController::class,
            Controller\CustomerAddressController::class       => Controller\CustomerAddressController::class,
            Controller\FaqController::class                   => Controller\FaqController::class,
            Controller\OrderController::class                 => Controller\OrderController::class,
            Controller\PaymentController::class               => Controller\PaymentController::class,
            Controller\PaypalController::class                => Controller\PaypalController::class,
            Controller\PostCostController::class              => Controller\PostCostController::class,
            Controller\PostLevelController::class             => Controller\PostLevelController::class,
            Controller\PostUnitController::class              => Controller\PostUnitController::class,
            Controller\PostZoneController::class              => Controller\PostZoneController::class,
            Controller\ProductAvailabilityController::class   => Controller\Factory\ProductAvailabilityControllerFactory::class,
            Controller\ProductCategoryController::class       => Controller\ProductCategoryController::class,
            Controller\ProductController::class               => Controller\ProductController::class,
            Controller\ProductGroupController::class          => Controller\ProductGroupController::class,
            Controller\ProductImageController::class          => Controller\ProductImageController::class,
            Controller\ProductOptionController::class         => Controller\ProductOptionController::class,
            Controller\ProductSizeController::class           => Controller\ProductSizeController::class,
            Controller\ReportController::class                => Controller\ReportController::class,
            Controller\SettingsController::class              => Controller\SettingsController::class,
            Controller\ShopController::class                  => Controller\ShopController::class,
            Controller\TaxCodeController::class               => Controller\TaxCodeController::class,
            Controller\TaxRateController::class               => Controller\TaxRateController::class,
            Controller\VoucherAdminController::class          => Controller\VoucherAdminController::class,
            Controller\VoucherCodesController::class          => Controller\VoucherCodesController::class,
        ],
    ],
    'controller_plugins' => [
        'aliases' => [
            'Order' => Controller\Plugin\Order::class,
        ],
        'invokables' => [
            Controller\Plugin\Order::class => Controller\Plugin\Order::class,
        ],
    ],
    'service_manager' => [
        'aliases'   => [
            'ExceptionMailer\ErrorHandling' => Exception\Mailer::class
        ],
        'invokables' => [
            Service\ReportService::class => Service\ReportService::class,
        ],
        'factories' => [
            Exception\Mailer::class                   => Exception\MailerFactory::class,

            Options\CartCookieOptions::class          => Service\Factory\CartCookieOptionsFactory::class,
            Options\CartOptions::class                => Service\Factory\CartOptionsFactory::class,
            Options\InvoiceOptions::class             => Service\Factory\InvoiceOptionsFactory::class,
            Options\OrderOptions::class               => Service\Factory\OrderOptionsFactory::class,
            Options\PaypalOptions::class              => Service\Factory\PaypalOptionsFactory::class,
            Options\ReportsOptions::class             => Service\Factory\ReportsOptionsFactory::class,
            Options\ShopOptions::class                => Service\Factory\ShopOptionsFactory::class,
            Options\NewProductsCarouselOptions::class => Service\Factory\NewProductsCarouselOptionsFactory::class,

            Service\CartCookieService::class          => Service\Factory\CartCookieFactory::class,
            Service\ProductAvailabilityService::class => Service\Factory\ProductAvailabilityServiceFactory::class,
            Service\ShippingService::class            => Service\Factory\ShippingServiceFactory::class,
            Service\TaxService::class                 => Service\Factory\TaxServiceFactory::class,
        ],
        'shared' => [
            Service\TaxService::class => false // will not be shared
        ],
    ],
    'uthando_services' => [
        'invokables' => [
            Service\AdvertHitService::class           => Service\AdvertHitService::class,
            Service\AdvertService::class              => Service\AdvertService::class,
            Service\CartItemService::class            => Service\CartItemService::class,
            Service\CartService::class                => Service\CartService::class,
            Service\CountryProvinceService::class     => Service\CountryProvinceService::class,
            Service\CountryService::class             => Service\CountryService::class,
            Service\CreditCardService::class          => Service\CreditCardService::class,
            Service\CustomerAddressService::class     => Service\CustomerAddressService::class,
            Service\CustomerPrefixService::class      => Service\CustomerPrefixService::class,
            Service\CustomerService::class            => Service\CustomerService::class,
            Service\FaqService::class                 => Service\FaqService::class,
            Service\OrderLineService::class           => Service\OrderLineService::class,
            Service\OrderService::class               => Service\OrderService::class,
            Service\OrderStatusService::class         => Service\OrderStatusService::class,
            Service\PaypalService::class              => Service\PaypalService::class,
            Service\PostCostService::class            => Service\PostCostService::class,
            Service\PostLevelService::class           => Service\PostLevelService::class,
            Service\PostUnitService::class            => Service\PostUnitService::class,
            Service\PostZoneService::class            => Service\PostZoneService::class,
            Service\ProductCategoryService::class     => Service\ProductCategoryService::class,
            Service\ProductGroupService::class        => Service\ProductGroupService::class,
            Service\ProductImageService::class        => Service\ProductImageService::class,
            Service\ProductOptionService::class       => Service\ProductOptionService::class,
            Service\ProductService::class             => Service\ProductService::class,
            Service\ProductSizeService::class         => Service\ProductSizeService::class,
            Service\TaxCodeService::class             => Service\TaxCodeService::class,
            Service\TaxRateService::class             => Service\TaxRateService::class,
            Service\VoucherCodeService::class         => Service\VoucherCodeService::class,
            Service\VoucherCustomerMapService::class  => Service\VoucherCustomerMapService::class,
        ],
    ],
    'view_helpers' => [
        'aliases' => [
            'ShopAlert'                 => View\Alert::class,
            'BreadCrumbs'               => View\Breadcrumb::class,
            'CartOption'                => View\CartOption::class,
            'Cart'                      => View\Cart::class,
            'Category'                  => View\Category::class,
            'CountrySelect'             => View\CountrySelect::class,
            'CustomerAddress'           => View\CustomerAddress::class,
            'MonthYearSelect'           => View\FormMonthSelect::class,
            'InvoiceOption'             => View\InvoiceOption::class,
            'NormaliseOrderNumber'      => View\NormaliseOrderNumber::class,
            'NewProductsCarouselOption' => View\NewProductsCarouselOption::class,
            'OrderStatus'               => View\OrderStatus::class,
            'PercentFormat'             => View\PercentFormat::class,
            'PriceFormat'               => View\PriceFormat::class,
            'ProductHelper'             => View\Product::class,
            'ProductCategoryImage'      => View\ProductCategoryImage::class,
            'ProductImage'              => View\ProductImage::class,
            'ProductOptions'            => View\ProductOptions::class,
            'ProductPrice'              => View\ProductPrice::class,
            'ProductSearch'             => View\ProductSearch::class,
            'ProductTableRowState'      => View\ProductTableRowState::class,
            'ShopOption'                => View\ShopOption::class,
            'StructuredData'            => View\StructuredData::class,
        ],
        'invokables'    => [
            View\Alert::class                     => View\Alert::class,
            View\Breadcrumb::class                => View\Breadcrumb::class,
            View\CartOption::class                => View\CartOption::class,
            View\Cart::class                      => View\Cart::class,
            View\Category::class                  => View\Category::class,
            View\CountrySelect::class             => View\CountrySelect::class,
            View\CustomerAddress::class           => View\CustomerAddress::class,
            View\FormMonthSelect::class           => View\FormMonthSelect::class,
            View\InvoiceOption::class             => View\InvoiceOption::class,
            View\NormaliseOrderNumber::class      => View\NormaliseOrderNumber::class,
            View\NewProductsCarouselOption::class => View\NewProductsCarouselOption::class,
            View\OrderStatus::class               => View\OrderStatus::class,
            View\PercentFormat::class             => View\PercentFormat::class,
            View\PriceFormat::class               => View\PriceFormat::class,
            View\Product::class                   => View\Product::class,
            View\ProductCategoryImage::class      => View\ProductCategoryImage::class,
            View\ProductImage::class              => View\ProductImage::class,
            View\ProductOptions::class            => View\ProductOptions::class,
            View\ProductPrice::class              => View\ProductPrice::class,
            View\ProductSearch::class             => View\ProductSearch::class,
            View\ProductTableRowState::class      => View\ProductTableRowState::class,
            View\ShopOption::class                => View\ShopOption::class,
            View\StructuredData::class            => View\StructuredData::class,
        ],
    ],
    'view_manager' => [
        'template_map' => [
            'mail/error'           => __DIR__ . '/../view/error/mail.phtml',
            'cart/summary'         => __DIR__ . '/../view/shop/cart/cart-summary.phtml',
            'shop/cart'            => __DIR__ . '/../view/shop/cart/cart.phtml',
            'shop/order/details'   => __DIR__ . '/../view/shop/order/order-details.phtml',
            'error/mail'           => __DIR__ . '/../view/error/mail.phtml', // Exception_Mailer
            'error/paypal'         => __DIR__ . '/../view/error/paypal-error.phtml', // Exception_Mailer
        ],
        'template_path_stack' => [
            'shop' => __DIR__ . '/../view'
        ],
    ],
];
