<?php

return array(
    'shared'        => array(
    	'Shop\Form\Country'						=> false,
        'Shop\Form\Customer'                    => false,
        'Shop\Form\CustomerAddress'             => false,
        'Shop\Form\Order'                       => false,
        'Shop\Form\OrderLine'                   => false,
        'Shop\Form\OrderStatus'                 => false,
    	'Shop\Form\PostCost'					=> false,
    	'Shop\Form\PostLevel'					=> false,
        'Shop\Form\PostUnit'					=> false,
    	'Shop\Form\PostZone'					=> false,
    	'Shop\Form\Product'						=> false,
    	'Shop\Form\ProductCategory'				=> false,
        'Shop\InputFilter\ProductGroupPrice'    => false,
    	'Shop\Form\ProductImage'				=> false,
    	'Shop\Form\TaxCode'						=> false,
    	'Shop\Form\TaxRate'						=> false,
    ),
	'invokables'    => array(
	    'Shop\Form\CatalogSearch'               => 'Shop\Form\Catalog\Search',
		'Shop\Form\Country'						=> 'Shop\Form\Country',
	    'Shop\Form\Customer'				    => 'Shop\Form\Customer',
		'Shop\Form\CustomerAddress'				=> 'Shop\Form\Customer\Address',
	    'Shop\Form\Order'                       => 'Shop\Form\Order',
	    'Shop\Form\OrderLine'                   => 'Shop\Form\Order\Line',
	    'Shop\Form\OrderStatus'                 => 'Shop\Form\Order\Status',
		'Shop\Form\PostCost'					=> 'Shop\Form\Post\Cost',
		'Shop\Form\PostLevel'					=> 'Shop\Form\Post\Level',
	    'Shop\Form\PostUnit'					=> 'Shop\Form\Post\Unit',
		'Shop\Form\PostZone'					=> 'Shop\Form\Post\Zone',
		'Shop\Form\Product'						=> 'Shop\Form\Product',
	    'Shop\Form\ProductCategory'				=> 'Shop\Form\Product\Category',
	    'Shop\Form\ProductGroupPrice'           => 'Shop\Form\Product\GroupPrice',
		'Shop\Form\ProductImage'				=> 'Shop\Form\Product\Image',
		'Shop\Form\TaxCode'						=> 'Shop\Form\Tax\Code',
		'Shop\Form\TaxRate'						=> 'Shop\Form\Tax\Rate',
		
	    'Shop\InputFilter\CatalogSearch'        => 'Shop\InputFilter\Catalog\Search',
		'Shop\InputFilter\Country'				=> 'Shop\InputFilter\Country',
	    'Shop\InputFilter\Customer'				=> 'Shop\InputFilter\Customer',
	    'Shop\InputFilter\CustomerAddress'		=> 'Shop\InputFilter\Customer\Address',
	    'Shop\InputFilter\Order'                => 'Shop\InputFilter\Order',
	    'Shop\InputFilter\OrderLine'            => 'Shop\InputFilter\Order\Line',
	    'Shop\InputFilter\OrderStatus'          => 'Shop\InputFilter\Order\Status',
		'Shop\InputFilter\PostCost'				=> 'Shop\InputFilter\Post\Cost',
		'Shop\InputFilter\PostLevel'			=> 'Shop\InputFilter\Post\Level',
	    'Shop\InputFilter\PostUnit'	            => 'Shop\InputFilter\Post\Unit',
		'Shop\InputFilter\PostZone'				=> 'Shop\InputFilter\Post\Zone',
	    'Shop\InputFilter\Product' 			    => 'Shop\InputFilter\Product',
		'Shop\InputFilter\ProductCategory'	    => 'Shop\InputFilter\Product\Category',
	    'Shop\InputFilter\ProductGroupPrice'    => 'Shop\InputFilter\Product\GroupPrice',
		'Shop\InputFilter\ProductImage'		    => 'Shop\InputFilter\Product\Image',
		'Shop\InputFilter\ProductOption'	    => 'Shop\InputFilter\Product\Option',
		'Shop\InputFilter\ProductSize'		    => 'Shop\InputFilter\Product\Size',
		'Shop\InputFilter\TaxCode'				=> 'Shop\InputFilter\Tax\Code',
		'Shop\InputFilter\TaxRate'				=> 'Shop\InputFilter\Tax\Rate',
	    
	    'Shop\Mapper\Cart'                      => 'Shop\Mapper\Cart',
	    'Shop\Mapper\CartItem'                  => 'Shop\Mapper\Cart\Item',
	    'Shop\Mapper\Country'                   => 'Shop\Mapper\Country',
	    'Shop\Mapper\Customer'                  => 'Shop\Mapper\Customer',
	    'Shop\Mapper\CustomerAddress'           => 'Shop\Mapper\Customer\Address',
	    'Shop\Mapper\CustomerPrefix'            => 'Shop\Mapper\Customer\Prefix',
	    'Shop\Mapper\Order'                     => 'Shop\Mapper\Order',
	    'Shop\Mapper\OrderLine'                 => 'Shop\Mapper\Order\Line',
	    'Shop\Mapper\OrderStatus'               => 'Shop\Mapper\Order\Status',
	    'Shop\Mapper\PostCost'                  => 'Shop\Mapper\Post\Cost',
	    'Shop\Mapper\PostLevel'                 => 'Shop\Mapper\Post\Level',
	    'Shop\Mapper\PostUnit'		            => 'Shop\Mapper\Post\Unit',
	    'Shop\Mapper\PostZone'                  => 'Shop\Mapper\Post\Zone',
		'Shop\Mapper\Product' 				    => 'Shop\Mapper\Product',
		'Shop\Mapper\ProductCategory'		    => 'Shop\Mapper\Product\Category',
	    'Shop\Mapper\ProductGroupPrice'         => 'Shop\Mapper\Product\GroupPrice',
		'Shop\Mapper\ProductImage'			    => 'Shop\Mapper\Product\Image',
		'Shop\Mapper\ProductOption'			    => 'Shop\Mapper\Product\Option',
		'Shop\Mapper\ProductSize'			    => 'Shop\Mapper\Product\Size',
		'Shop\Mapper\TaxCode'				    => 'Shop\Mapper\Tax\Code',
		'Shop\Mapper\TaxRate'				    => 'Shop\Mapper\Tax\Rate',
		
	    'Shop\Service\Cart'                     => 'Shop\Service\Cart',
	    'Shop\Service\CartItem'                 => 'Shop\Service\Cart\Item',
	    'Shop\Service\Country'                  => 'Shop\Service\Country',
	    'Shop\Service\Customer'                 => 'Shop\Service\Customer',
	    'Shop\Service\CustomerAddress'          => 'Shop\Service\Customer\Address',
	    'Shop\Service\CustomerPrefix'           => 'Shop\Service\Customer\Prefix',
	    'Shop\Service\Order'                    => 'Shop\Service\Order',
	    'Shop\Service\OrderLine'                => 'Shop\Service\Order\Line',
	    'Shop\Service\OrderStatus'              => 'Shop\Service\Order\Status',
	    'Shop\Service\PostCost'                 => 'Shop\Service\Post\Cost',
	    'Shop\Service\PostLevel'                => 'Shop\Service\Post\Level',
	    'Shop\Service\PostUnit'		            => 'Shop\Service\Post\Unit',
	    'Shop\Service\PostZone'                 => 'Shop\Service\Post\Zone',
		'Shop\Service\Product' 				    => 'Shop\Service\Product',
		'Shop\Service\ProductCategory'          => 'Shop\Service\Product\Category',
	    'Shop\Service\ProductGroupPrice'        => 'Shop\Service\Product\GroupPrice',
	    'Shop\Service\ProductImage'             => 'Shop\Service\Product\Image',
	    'Shop\Service\ProductOption'			=> 'Shop\Service\Product\Option',
	    'Shop\Service\ProductSize'			    => 'Shop\Service\Product\Size',
	    'Shop\Service\Tax'                      => 'Shop\Service\Tax',
	    'Shop\Service\TaxCode'                  => 'Shop\Service\Tax\Code',
	    'Shop\Service\TaxRate'                  => 'Shop\Service\Tax\Rate',
	),
    'factories' => array(
        'Shop\Options\CartCookieOptions'        => 'Shop\Service\Factory\CartCookieOptions',
        'Shop\Options\Checkout'                 => 'Shop\Service\Factory\CheckoutOptions',
        'Shop\Options\Paypal'                   => 'Shop\Service\Factory\PaypalOptions',
        'Shop\Options\Shop'                     => 'Shop\Service\Factory\ShopOptions',
        
        'Shop\Service\CartCookie'               => 'Shop\Service\Factory\CartCookie',
        'Shop\Service\Shipping'                 => 'Shop\Service\Factory\Shipping',
    ),
);