<?php

return [
    'uthando_user' => [
        'acl' => [
            'roles' => [
                'guest' => [
                    'privileges' => [
                        'allow' => [
                            'controllers' => [
                                \Shop\Controller\CartController::class => ['action' => 'all'],
                                \Shop\Controller\CatalogController::class => ['action' => 'all'],
                                \Shop\Controller\CheckoutController::class => ['action' => ['index']],
                                \Shop\Controller\FaqController::class => ['action' => ['faq']],
                                \Shop\Controller\ProductController::class=> ['action' => [ 'view']],
                                \Shop\Controller\ShopController::class => ['action' => ['shop-front']],
                                \Shop\Controller\VoucherCodesController::class => ['action' => ['add-voucher']],
                            ],
                        ],
                    ],
                ],
                'registered' => [
                    'privileges' => [
                        'allow' => [
                            'controllers' => [
                                \Shop\Controller\CheckoutController::class => ['action' => 'all'],
                                \Shop\Controller\CountryProvinceController::class => ['action' => ['country-province-list']],
                                \Shop\Controller\CustomerController::class => ['action' => ['my-details']],
                                \Shop\Controller\CustomerAddressController::class => ['action' => ['my-addresses', 'edit-address', 'add-address', 'delete-address']],
                                \Shop\Controller\OrderController::class => ['action' => ['cancel', 'my-orders', 'print', 'view']],
                                \Shop\Controller\PaymentController::class => ['action' => 'all'],
                                \Shop\Controller\PaypalController::class => ['action' => ['process', 'success', 'cancel']],
                            ],
                        ],
                    ],
                ],
                'admin' => [
                    'privileges' => [
                        'allow' => [
                            'controllers' => [
                                \Shop\Controller\AdvertController::class => ['action' => 'all'],
                                \Shop\Controller\CountryController::class => ['action' => 'all'],
                                \Shop\Controller\CountryProvinceController::class => ['action' => 'all'],
                                \Shop\Controller\CustomerController::class => ['action' => 'all'],
                                \Shop\Controller\CustomerAddressController::class => ['action' => 'all'],
                                \Shop\Controller\FaqController::class => ['action' => 'all'],
                                \Shop\Controller\OrderController::class => ['action' => 'all'],
                                \Shop\Controller\CreateOrderController::class => ['action' => 'all'],
                                \Shop\Controller\PaypalController::class=> ['action' => ['search']],
                                \Shop\Controller\PostCostController::class => ['action' => 'all'],
                                \Shop\Controller\PostLevelController::class => ['action' => 'all'],
                                \Shop\Controller\PostUnitController::class => ['action' => 'all'],
                                \Shop\Controller\PostZoneController::class => ['action' => 'all'],
                                \Shop\Controller\ProductController::class => ['action' => 'all'],
                                \Shop\Controller\ProductCategoryController::class=> ['action' => 'all'],
                                \Shop\Controller\ProductImageController::class => ['action' => 'all'],
                                \Shop\Controller\ProductGroupController::class => ['action' => 'all'],
                                \Shop\Controller\ProductOptionController::class => ['action' => 'all'],
                                \Shop\Controller\ProductSizeController::class => ['action' => 'all'],
                                \Shop\Controller\ShopController::class => ['action' => 'all'],
                                \Shop\Controller\TaxCodeController::class => ['action' => 'all'],
                                \Shop\Controller\TaxRateController::class => ['action' => 'all'],
                                \Shop\Controller\ReportController::class => ['action' => 'all'],
                                \Shop\Controller\SettingsController::class => ['action' => 'all'],
                                \Shop\Controller\VoucherAdminController::class => ['action' => 'all'],
                            ],
                        ],
                    ],
                ],
            ],
            'resources' => [
                \Shop\Controller\AdvertController::class,
                \Shop\Controller\CartController::class,
                \Shop\Controller\CatalogController::class,
                \Shop\Controller\CheckoutController::class,
                \Shop\Controller\CountryController::class,
                \Shop\Controller\CountryProvinceController::class,
                \Shop\Controller\CustomerController::class,
                \Shop\Controller\CustomerAddressController::class,
                \Shop\Controller\FaqController::class,
                \Shop\Controller\OrderController::class,
                \Shop\Controller\CreateOrderController::class,
                \Shop\Controller\PaymentController::class,
                \Shop\Controller\PaypalController::class,
                \Shop\Controller\PostCostController::class,
                \Shop\Controller\PostLevelController::class,
                \Shop\Controller\PostUnitController::class,
                \Shop\Controller\PostZoneController::class,
                \Shop\Controller\ProductController::class,
                \Shop\Controller\ProductCategoryController::class,
                \Shop\Controller\ProductImageController::class,
                \Shop\Controller\ProductGroupController::class,
                \Shop\Controller\ProductOptionController::class,
                \Shop\Controller\ProductSizeController::class,
                \Shop\Controller\ShopController::class,
                \Shop\Controller\TaxCodeController::class,
                \Shop\Controller\TaxRateController::class,
                \Shop\Controller\ReportController::class,
                \Shop\Controller\SettingsController::class,
                \Shop\Controller\VoucherAdminController::class,
                \Shop\Controller\VoucherCodesController::class,
            ],
        ],
    ],
];