
<?php
$postUrl = null;
$cancelUrl = null;
$helperOptions = null;
$formName = null;

if ($this->request()->isXmlHttpRequest()) {
    $helperOptions = [
        'labelWidth'    => '2',
        'elementWidth'  => '10',
    ];
} else {
    $this->headTitle('Add Post Unit');
    $postUrl = $this->url('admin/shop/post/unit/edit', [
        'action'    => 'add',
    ]);
    $cancelUrl = $this->url('admin/shop/post/unit');
    $formName = 'Post Unit';
}
?>

<?=$this->tbFlashMessenger()->render(); ?>

<?=$this->form($form);?>
