<?php $this->headTitle('Add Post Unit') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Post Unit'); ?>

<?php $this->placeholder('header-buttons')->captureStart(); ?>
<button type="submit" form="form-post-unit" data-toggle="tooltip" title="<?= $this->translate('Save'); ?>"
        class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?= $this->url('admin/shop/post/unit'); ?>" data-toggle="tooltip" title="<?= $this->translate('Cancel'); ?>"
   class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd(); ?>

<?php $this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-post-unit',
    'action' => $this->url('admin/shop/post/unit/edit', [
        'action' => 'add',
    ]),
]); ?>

<?php if (!$this->request()->isXmlHttpRequest()):?>
<div id="post-unit-add" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?= $this->translate('Add Post Unit'); ?></h3>
    </div>
    <div class="panel-body">
        <?= $this->form($this->form); ?>
    </div>
</div>
<?php else: ?>
<?= $this->form($this->form); ?>
<?php endif; ?>
