<?php $this->headTitle('Edit Post Unit') ?>
<?=$this->ztbFlashMessenger()->render(); ?>

<?=$this->partial('partial/add-edit-form', array(
	'form' 			=> $this->form,
	'formAction' 	=> 'edit',
	'primaryKey'	=> $this->model->getPostUnitId(),
	'formName'		=> 'Post Unit',
	'postRoute'		=> 'admin/shop/post/unit/edit',
	'cancelRoute'	=> 'admin/shop/post/unit',
	'formElements'	=> array(
		'postUnit', 'postUnitId',
	),
)); ?>
