
<div class="tab-wrap">
<!-- 
	<ul id="postUnitTabs" class="nav nav-tabs">
	    <li><a href="#admin-postUnit">Post Units</a></li>
	</ul>
	
	<div id="postUnitTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-postUnit">
	    -->
	    	<div class="row-fluid">
		    	<?=$this->partial('partial/search', array(
		    		'name'			=> 'postUnit',
		    		'searchInputs'	=> array(
		    			'Post Unit' => 'postUnit',
		    		),
		    	));?>
	    	</div>
	    	
	    	<div id="table-postUnit" class="row-fluid table-wrap">
		    	<?=$this->partial('shop/post-unit/list', array(
		    	    'models' => $this->models
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-postUnit').dataGrid({
	    url : 'unit/list',
	    query: { sort : 'postUnit' },
	    searchForm : $('#search-postUnit'),
	    paging : 'links',
	    columnSort: true,
	});
});
<?php $this->headScript()->captureEnd(); ?>
