
<!-- PAGE TOP -->
<!-- parallax -->
<div class="parallax parallax-1" style="background-image:url(<?=$this->basePath('/userfiles/bead_trays.jpg');?>);">
    <span class="parallax-overlay"></span>

    <div class="container parallax-content">

        <div class="row">
            <div class="col-md-5 col-sm-5">

                <h1 class="nomargin">One more step to <b>freedom</b></h1>

            </div>

            <div class="col-md-7 col-sm-7 text-right">


                <div class="hidden-xs">
                    <h4 class="nomargin">Need assistance?</h4>
                    <h2 class="nomargin"><?=$this->contact('details.phone');?></h2>
                </div>

            </div>
        </div>

    </div>

</div>
<!-- /parallax -->
<!-- /PAGE TOP -->
