<?php $this->headTitle('Edit Post Zone') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
	'form' 			=> $this->form,
	'formName'		=> 'Post Zone',
    'postUrl'		=> $this->url('admin/shop/post/zone/edit', [
        'id' => $this->model->getPostZoneId(),
    ]),
    'cancelUrl'     => $this->url('admin/shop/post/zone'),
	'formElements'	=> [
		'zone', 'taxCodeId', 'postZoneId',
	],
]); ?>
