<?php $this->headTitle('Post Zones') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->zones) > 0): ?>

<table id="postZone-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="postZoneId">Post Zone Id</th>
			<th data-field="zone">Zone</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach($this->zones as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getPostZoneId()); ?></td>
			<td><?=$this->escapeHtml($row->getZone()); ?></td>
			<td>
                <a href="<?=$this->url('admin/shop/post/zone/edit', array(
                    'id' => $row->getPostZoneId()
				)); ?>" class="btn">Edit</a>
				&nbsp;
				
				<!-- Button to trigger modal -->
                <a href="#postZoneModel<?=$row->getPostZoneId(); ?>" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="postZoneModel<?=$row->getPostZoneId(); ?>">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
				    <h3 id="postZoneModel<?=$row->getPostZoneId(); ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?=$this->url('admin/shop/post/zone/edit', array(
				        'action' => 'delete',
				    )) ?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this post zone.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="postZoneId" value="<?=$row->getPostZoneId() ?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->zones,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/post/zone/page')
); ?>

<?php else: ?>
<h4>No Post Zones where returned by search.</h4>
<?php endif; ?>
