<?php $this->headTitle('Post Zones') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->models) > 0): ?>

<table id="postZone-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="postZoneId">Post Zone Id</th>
			<th data-field="zone">Zone</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php /* @var $row \Shop\Model\Post\Zone */ ?>
		<?php foreach($this->models as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getPostZoneId()); ?></td>
			<td><?=$this->escapeHtml($row->getZone()); ?></td>
			<td>
                <?=$this->partial('partial/edit-actions', array(
                	'pk'		=> 'postZoneId',
                	'id'		=> $row->getPostZoneId(),
		    		'tableName'	=> 'postZone',
                	'route'		=> 'admin/shop/post/zone/edit',
		    	));?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/post/zone/page')
); ?>

<?php else: ?>
<h4>No Post Zones where returned by search.</h4>
<?php endif; ?>
