<?php $this->headTitle('Checkout - Comfirm Address') ?>

<div class="row">
    <h2 class="col-md-12">Comfirm Address</h2>
    
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Billing Address
                </h4>
            </div>
            <div class="panel-body">
                <address>
                    <?=$this->customerAddress()
                        ->setAddress('billing')
                        ->includeName()
                        ->includeEmail()
                        ->render();?>
                </address>
            </div>
            <div class="panel-footer">
                <a data-toggle="modal" href="<?=$this->url('shop/customer/address', [
                    'action'    => 'edit-address',
                    'id' => $this->customerAddress()->getAddress()->getCustomerAddressId(),
                ]) ?>" data-target="#addressModel" class="btn btn-primary">Edit Address</a>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    Delivery Address
                </h4>
            </div>
            <div class="panel-body">
                <address>
                    <?=$this->customerAddress()
                        ->setAddress('delivery')
                        ->includeName()
                        ->render();?>
                    <br>
                </address>
            </div>
            <div class="panel-footer">
                <a data-toggle="modal" href="<?=$this->url('shop/customer/address', [
                    'action'    => 'edit-address',
                    'id' => $this->customerAddress()->getAddress()->getCustomerAddressId(),
                ]) ?>" data-target="#addressModel" class="btn btn-primary">Edit Address</a>
            </div>
        </div>
    </div>
    
    <form class="col-md-12" method="post" action="<?=$this->url('shop/checkout', [
        'action' => 'confirm-order',
    ]) ?>">
        <button type="submit" name="submit" class="btn btn-primary" value="confirmAddress">Check &amp; Confirm Order</button>
    </form>
</div>

<div id="addressModel" class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>


