<?php $this->headTitle('Checkout - Login or Register') ?>
<div class="row">
    <div class="span5">
        <?php echo $this->partial('user/user/user-form', array(
            'form' => $this->register,
        	'formAction' => 'register',
            'legend' => ' New Customer',
            'returnTo'      => 'shop/checkout'
        )); ?>
    </div>
    
    <div class="span2 text-center">
        OR
    </div>
    
    <div class="span5">
        <?php echo $this->partial('user/auth/login-form', array(
	        'form' => $this->login,
	        'formAction' => 'register',
            'legend' => 'Login To Checkout',
            'returnTo'      => 'shop/checkout'
        )); ?>
    </div>
</div>