<?php $this->headTitle('Checkout - Login or Register') ?>

<div>
    <?php echo $this->partial('user/auth/login-form', array(
        'form' => $this->login,
        'formAction' => 'register',
        'legend' => 'Login To Checkout',
        'returnTo'      => 'shop/checkout'
    )); ?>
</div>

<div id="checkout-or">
    <span>OR</span>
</div>

<div class="">
    <?php echo $this->partial('user/user/user-form', array(
        'form' => $this->register,
    	'formAction' => 'register',
        'legend' => 'Register As New Customer',
        'returnTo'      => 'shop/checkout'
    )); ?>
</div>
