<?php $errors = $this->form->getMessages(); ?>
<form method="post" action="<?= $this->https; ?>/shop/credit_card.php">
    <table cellspacing="0" cellpadding="0" align="center">
        <tr>
            <td>
                <h2>Credit or Debit Card</h2>
                <p>
                    <b>Please enter your details below and we will process your order.</b>
                </p>

                <table width="100%" cellspacing="4" cellpadding="4">
                    <tr>
                        <td>
                            <b>Order Reference:</b>
                        </td>
                        <td>
                            <b><?= $this->invoiceNumber; ?></b>
                            <?= $this->form->getElement('oid'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Order Total:</b>
                        </td>
                        <td>
                            <b>&pound;<?= $this->form->getElement('total')->getValue(); ?></b>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Name of Card Holder:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('ccName'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Card Type:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('ccType'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Card Number:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('ccNumber'); ?><br />
                            <img src="/shop/html/img/logo_ccVisa.gif" />
                            <img src="/shop/html/img/logo_ccElectron.gif" />
                            <img src="/shop/html/img/logo_ccDelta.gif" />
                            <img src="/shop/html/img/logo_ccMC.gif" />
                            <img src="/shop/html/img/logo_ccSwitch.gif" />
                            <!--<img src="/shop/html/img/logo_ccSolo.gif" />
                            <img src="/shop/html/img/logo_ccAmex.gif" />
                            <img src="/shop/html/img/logo_ccDiscover.gif" />-->
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Expiry Date:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('ccExpiryMonth'); ?>
                            <?= $this->form->getElement('ccExpiryYear'); ?>
                            <ul class="errors">
                            	<? if (isset($errors['ccExpiryMonth'])): ?>
                            	<li><?=  $errors['ccExpiryMonth'][0]; ?></li>
                            	<?php endif; ?>
                            	<? if (isset($errors['ccExpiryYear'])): ?>
                            	<li><?=  $errors['ccExpiryYear'][0]; ?></li>
                            	<?php endif; ?>
                            </ul>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Card Verification Number:</b>
                        </td>
                        <td>
                            <span>
                                Last 3-digits on the back of your card.
                            </span><br />
                            <?= $this->form->getElement('ccCardVerificationNumber'); ?>
                            <img class="middle" src="/shop/html/img/mini_cvv2.gif" />
                            <span>
                                <a href="#" rel="threeDigit" class="viewCCHelp">Help finding your Card Verification Number</a> |
                                <!--<a href="#" rel="fourDigit" class="viewCCHelp">Using AmEx?</a>-->
                            </span>
                        </td>
                    </tr>
                    <tr class="amexFields">
                        <td>
                            <b>Issue Number:</b>
                        </td>
                        <td>
                            <span>(if applicable)</span><br />
                            <?= $this->form->getElement('ccIssueNumber'); ?>
                        </td>
                    </tr>
                    <tr class="amexFields">
                        <td>
                            <b>Start Date:</b>
                        </td>
                        <td>
                        	<?= $this->form->getElement('ccStartMonth'); ?>
                           	<?= $this->form->getElement('ccStartYear'); ?>
                           	<ul class="errors">
                            	<? if (isset($errors['ccStartMonth'])): ?>
                            	<li><?=  $errors['ccStartMonth'][0]; ?></li>
                            	<?php endif; ?>
                            	<? if (isset($errors['ccStartYear'])): ?>
                            	<li><?=  $errors['ccStartYear'][0]; ?></li>
                            	<?php endif; ?>
                            </ul>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <h2>Billing Address</h2>
                <p>
                    <b>Enter the address where you receive billing statements for this card.
                        To confirm your bank card number, the billing address must be the one
                        displayed on your statements.</b>
                </p>
                <?= $this->registeredBillingAddresses; ?>
                <?= $this->form->getElement('billing'); ?>
                
                <table id="ccNewBillingAddress" width="100%" cellspacing="4" cellpadding="4" style="display:none;">
                    <tr>
                        <td>
                            <b>Address Line 1:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('addressLine1'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Address Line 2:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('addressLine2'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Address Line 3:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('addressLine3'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Town/City</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('city'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>County:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('county'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Postcode:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('postcode'); ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <b>Country:</b>
                        </td>
                        <td>
                            <?= $this->form->getElement('country'); ?>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" class="submit" name="submit" value="Submit Details" />
                <input type="reset" class="submit" name="reset" value="Reset Form">
            </td>
        </tr>
    </table>
</form>


<div id="cardTips">
    <div id="threeDigit">
        <img class="close" src="/images/close.png" />
        <h3>Three Digit Card Security Code</h3>
        <p>For your safety and security, Charisma Beads Ltd requires that you enter your card's
            verification number. The verification number is a three-digit number printed
            on the back of your card. It appears after and to the right of your card number.</p>
        <img src="/shop/html/img/cv_card.gif" />
    </div>
    <div id="fourDigit">
        <img class="close" src="/images/close.png" />
        <h3>Four Digit Card Security Code</h3>
        <p>For your safety and security, Charisma Beads Ltd requires that you enter your card's
            security code. The American Express security code is a four-digit number printed
            on the front of your card. It appears after and to the right of your card number.</p>
        <img src="/shop/html/img/cv_amex_card.gif" />
    </div>
</div>