<?php
$form = $this->form;
$routeArray = array('action' => $this->formAction);
if (isset($this->postCostId)) $routeArray['id'] = $this->postCostId;
?>
<div>
	<form class="form form-horizontal" method="post" action="<?=$this->url('admin/shop/post/cost/edit', $routeArray) ?>">
		<fieldset>
			<legend><?=ucwords($this->formAction); ?> Post Cost Form:</legend>
			<?=$this->ztbFormElement($form->get('cost'));?>
			<?=$this->ztbFormElement($form->get('vatInc'));?>
			<?=$this->ztbFormElement($form->get('postLevelId'));?>
			<?=$this->ztbFormElement($form->get('postZoneId'));?>
			<input type="hidden" name="action" value="<?=$this->formAction;?>">
			
			<div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary" data-loading-text="Please wait...">
                	Submit
                </button>
                <button type="button" class="btn btn-warning"  data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('admin/shop/post/cost') ?>';">
                	Cancel
                </button>
            </div>
        </div>
		</fieldset>
	</form>
</div>

