<?php $this->headTitle('Edit Post Cost') ?>

<?=$this->partial('uthando-admin/partial/add-edit-form', [
	'form' 			=> $this->form,
	'formAction' 	=> 'edit',
	'primaryKey'	=> $this->model->getPostCostId(),
	'formName'		=> 'Post Level',
	'postRoute'		=> 'admin/shop/post/cost/edit',
	'cancelRoute'	=> 'admin/shop/post/cost',
	'formElements'	=> [
		'cost', 'vatInc', 'postLevelId', 'postZoneId', 'postCostId',
	],
]); ?>
