<?php $this->headTitle('Edit Post Cost') ?>
<?=$this->ztbFlashMessenger()->render(); ?>

<?=$this->partial('partial/add-edit-form', array(
	'form' 			=> $this->form,
	'formAction' 	=> 'edit',
	'primaryKey'	=> $this->model->getPostCostId(),
	'formName'		=> 'Post Level',
	'postRoute'		=> 'admin/shop/post/cost/edit',
	'cancelRoute'	=> 'admin/shop/post/cost',
	'formElements'	=> array(
		'cost', 'vatInc', 'postLevelId', 'postZoneId', 'postCostId',
	),
)); ?>
