
<div class="tab-wrap">
<!-- 
	<ul id="postCostTabs" class="nav nav-tabs">
	    <li><a href="#admin-postCost">Post Costs</a></li>
	</ul>
	
	<div id="postCostTabContent" class="tab-content">
	    <div class="tab-pane" id="admin-postCost">
	    -->
	    	<div class="row-fluid">
		    	<?=$this->partial('partial/search', array(
		    		'name'			=> 'postCost',
		    		'searchInputs'	=> array(
		    			'Cost' => 'cost',
		    		),
		    	));?>
	    	</div>
	    	
	    	<div id="table-postCost" class="row-fluid table-wrap">
		    	<?=$this->partial('shop/post-cost/list', array(
		    	    'models' => $this->models
		    	)); ?>
	    	</div>
	    <!-- </div>
	</div> -->
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-postCost').dataGrid({
	    url : 'cost/list',
	    query: { sort : 'postZoneId' },
	    searchForm : $('#search-postCost'),
	    paging : 'links',
	    columnSort: true,
	    //rowClick : admin.product.rowClick
	});
});
<?php $this->headScript()->captureEnd(); ?>
