<?php $this->headTitle('Post Costs') ?>
<?php echo $this->ztbFlashMessenger()->render(); ?>

<?php if (count($this->models) > 0): ?>

<table id="postCost-list" class="table table-hover table-bordered table-condensed sortable-table">
	<thead>
		<tr>
			<th data-field="postCostId">Post Level Id</th>
			<th data-field="cost">Cost</th>
			<th data-field="postLevel">Post Level</th>
			<th data-field="zone">Post Zone</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<?php /* @var $row \Shop\Model\Post\Cost */ ?>
		<?php foreach($this->models as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getPostCostId()); ?></td>
			<td><?=$this->escapeHtml($row->getCost()); ?></td>
			<td><?=$this->escapeHtml($row->getPostLevel()); ?></td>
			<td><?=$this->escapeHtml($row->getZone()); ?></td>
			<td>
                <?=$this->partial('partial/edit-actions', array(
                	'pk'		=> 'postCostId',
                	'id'		=> $row->getPostCostId(),
		    		'tableName'	=> 'postCost',
                	'route'		=> 'admin/shop/post/cost/edit',
		    	));?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'paginate',
	array('route' => 'admin/shop/post/cost/page')
); ?>

<?php else: ?>
<h4>No Post Costs where returned by search.</h4>
<?php endif; ?>
