<?php $this->headTitle('Post Costs') ?>

<?php if (count($this->models) > 0): ?>
<div class="table-responsive">
    <table id="postCost-list" class="table table-hover table-bordered table-condensed sortable-table">
    	<thead>
    		<tr>
    			<th data-field="postCostId">Post Level Id</th>
    			<th data-field="cost">Cost</th>
    			<th data-field="postLevel">Post Level</th>
    			<th data-field="zone">Post Zone</th>
    			<th>Actions</th>
    		</tr>
    	</thead>
    	
    	<tbody>
    		<?php /* @var $row \Shop\Model\Post\Cost */ ?>
    		<?php foreach($this->models as $row): ?>
    		<tr>
    			<td><?=$this->escapeHtml($row->getPostCostId()); ?></td>
    			<td><?=$this->escapeHtml($this->priceFormat($row->getCost())); ?></td>
    			<td><?=$this->escapeHtml($row->getPostLevel()->getPostLevel()); ?></td>
    			<td><?=$this->escapeHtml($row->getPostZone()->getZone()); ?></td>
    			<td>
                    <?=$this->partial('uthando-admin/partial/edit-actions', [
                    	'pk'		=> 'postCostId',
                    	'id'		=> $row->getPostCostId(),
    		    		'tableName'	=> 'postCost',
                    	'route'		=> 'admin/shop/post/cost/edit',
    		    	]);?>
    			</td>
    		</tr>
    		<?php endforeach; ?>
    	</tbody>
    </table>
</div>
<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/shop/post/cost/page']
); ?>

<?php else: ?>
<h4>No Post Costs where returned by search.</h4>
<?php endif; ?>
