<?php $this->headTitle('Contact');?>

<?php $this->placeholder('page-top')->captureStart();?>

<?=$this->partial('layout/page-title', [
    'pageTitle' => 'Contact Us'
]);?>

<?php $this->placeholder('page-top')->captureEnd();?>

<?php
$form = $this->form;
$this->form->setAttribute('action', $this->url('contact/process'));
?>

<div class="row">

    <!-- FORM -->
    <div class="col-md-9">
        <?php if ($this->contact('google_map.show_map')): ?>
        <div id="gmap" class="<?=$this->contact('google_map.color');?> gmap-half margin-bottom60"><!-- google map --></div>
        <script type="text/javascript">
            var	$googlemap_latitude 	= <?=$this->contact('google_map.latitude');?>,
                $googlemap_longitude	= <?=$this->contact('google_map.longitude');?>,
                $googlemap_zoom			= <?=$this->contact('google_map.zoom');?>;
        </script>
        <?php endif; ?>
        <h3>Drop us a line or just say <strong><em>Hello!</em></strong></h3>

        <?=$this->form($form);?>

    </div>
    <!-- /FORM -->

    <!-- INFO -->
    <div class="col-md-3">

        <h2>Visit Us</h2>

        <p><?=$this->contact('details.about_us_text');?></p>

        <div class="divider half-margins"><!-- divider --></div>

        <p class="nomargin-bottom">
            <span class="block">
                <strong><i class="fa fa-map-marker"></i> Address:</strong>&nbsp;
                <?=$this->contact()->formatAddress('details.address');?>
            </span>
            <span class="block">
                <strong><i class="fa fa-phone"></i> Phone:</strong>&nbsp;
                <a href="tel:<?=$this->contact()->formatPhoneNumber('phone');?>">
                    <?=$this->contact()->formatPhoneNumber('phone', true);?>
                </a>
            </span>
            <span class="block">
                <strong><i class="fa fa-envelope"></i> Email:</strong>&nbsp;
                <a href="<?=$this->url('contact');?>"><?=$this->contact('details.email');?></a>
            </span>
        </p>

        <div class="divider half-margins"><!-- divider --></div>

        <h4 class="font300">Business Hours</h4>
        <p><?=$this->contact()->businessHours();?></p>


    </div>
    <!-- /INFO -->
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function() {
    $('#contact-submit-button').on('click', function(){
        $('form').loadingOverlay({
            loadingText: 'Please wait while I try to send your message.'
        });
    });
});
<?php $this->inlineScript()->captureEnd(); ?>
