
<?=$this->headTitle($this->pageTitle);?>
<!-- PAGE TOP -->
<section class="page-title">
    <div class="container">

        <header>

            <ul class="breadcrumb"><!-- breadcrumb -->
                <li><a href="<?=$this->url('home');?>">Home</a></li>
                <li class="active"><?=$this->pageTitle;?></li>
            </ul><!-- /breadcrumb -->

            <h2><!-- Page Title -->
                <?=$this->pageTitle;?>
            </h2><!-- /Page Title -->

        </header>

    </div>
</section>
<!-- /PAGE TOP -->