
<?php
$routeParams = (is_array($this->routeParams)) ? $this->routeParams : [];
$edit = (is_bool($this->edit)) ? $this->edit : true;
$delete = (is_bool($this->delete)) ? $this->delete : true;
$buttonSize = ($this->buttonSize) ? ' ' . $this->buttonSize : '';
/* @var $order \Shop\Model\Order\OrderModel */
$order = $this->order;
?>

<a href="<?=$this->url($this->route, array_merge($routeParams, [
    'id' => $order->getOrderId(),
    'action' => 'print'
])); ?>" target="_blank" class="btn btn-default"><i class="fa fa-eye"></i></a>

<?php if ($order->getOrderStatus()->getOrderStatus() == 'Pending'):?>
<?php if ($edit):?>

<a href="<?=$this->url('admin/shop/order/create', [
    'id' => $order->getOrderId(),
    'action' => 'edit'
]); ?>" class="btn btn-primary" data-toggle="tooltip" title="<?= $this->translate('Edit'); ?>"><i class="fa fa-edit"></i></a>

<?php endif; ?>
&nbsp;
<?php if($delete):?>
<!-- Button to trigger modal -->
<a href="#<?=$this->tableName;?>Model<?=$order->getOrderId();?>" class="btn btn-danger btn-tooltip delete-button" data-toggle="modal" data-target="#<?=$this->tableName;?>Model<?=$order->getOrderId();?>">
    <i class="fa fa-trash"></i></a>
<!-- Modal -->
<div class="modal fade" id="<?=$this->tableName;?>Model<?=$order->getOrderId();?>">

    <div class="modal-dialog">
        <div class="modal-content">
        
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 id="<?=$this->tableName;?>Model<?=$order->getOrderId();?>Label">Warning</h3>
            </div>
            
            <form class="form-horizontal"  method="post" action="<?=$this->url($this->route, array_merge($routeParams, [
                'action' => 'delete',
            ])) ?>">
            <div class="modal-body">
                <p>Are you sure you want to delete this <?=$this->tableName;?>.</p>
                <p class="label label-important">This action cannot be undone</p>
            </div>
            <input type="hidden" name="<?=$this->pk;?>" value="<?=$order->getOrderId();?>">
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">No
                Don't
                 Do It</button>
                <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete
                It</button>
            </div>
            </form>
            
        </div>
    </div>
</div>
<?php endif; ?>
<?php endif; ?>