<?php $this->headTitle('Shop') ?>

<h2>Shop Front</h2>

<ul class="thumbnails">
<?php foreach ($this->cats as $row): ?>
    <li class="span3">
    	<div class="thumbnail text-center">
    		<img data-src="holder.js/200x100/auto" alt="">
    		<h5><?php echo $this->escapehtml($row->getCategory());?></h5>
    		<a href="<?php echo $this->url('shop/catalog', array(
    			'categoryIdent' => $row->getIdent()
    		)); ?>" class="btn">Click to see all Products in this Category</a>
    	</div>
    	
    </li>
<?php endforeach; ?>
</ul>

