<?php


namespace Shop\Controller;


use Zend\Mvc\Controller\AbstractActionController;

class ProductAvailabilityController extends AbstractActionController
{
    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function uploadAction()
    {
        
    }
}